// The questions here are pre-generated.
// See the Python script generate_data.py for details.
let questions = [
  "hi lo talmida, vehen?",
  "ani ba meuniversita o mibayt?",
  "imot ovdot im ima, veat?",
  "aten gam morot, veata?",
  "aten gam morot?",
  "morim leanglit lomdim, veat?",
  "ma morot lomdot birchov im morim?",
  "hu ba lesham, vehi?",
  "mora lomedet, vehen?",
  "talmid achshav ba lesham mikan?",
  "morim veabim lomdim?",
  "mora baa lekan?",
  "hu gam aba, vehem?",
  "hi baa mikan o merechov?",
  "ani lomed anglit im aba, vehem?",
  "abim baim mipo, vehen?",
  "abim baim meulpan o mibayt?",
  "aten baot mipo habayta?",
  "hen veaten baot mipo?",
  "abim baim lirchov o lepo?",
  "at baa misham, vehi?",
  "abim baim mipo, vehu?",
  "hem morim lerusit, veatem?",
  "aten veatem baim mibayt o meulpan?",
  "at baa leulpan o habayta?",
  "ani baa lesham mikan?",
  "talmida baa lepo misham?",
  "morim leivrit lomdim?",
  "aba ba mikan o mibayt?",
  "mora baa mikan o merechov?",
  "at mora, vehem?",
  "hu ba habayta, vehen?",
  "more leivrit ba lekan?",
  "aba achshav ba lepo?",
  "abim lomdim ivrit?",
  "ma aba lomed im anachnu veatem?",
  "talmid ba lirchov mipo o mibayt?",
  "abim baim lepo mibayt o misham?",
  "eyfo imot veabim ovdim?",
  "hu beakademja leivrit o bebayt?",
  "ani baa lirchov o lepo?",
  "mora lomedet rusit, vehi?",
  "ima baa mipo, vehem?",
  "eyfo anachnu ovdim?",
  "more ba lesham o lekan?",
  "mora baa mipo, vehen?",
  "ata achshav ba misham lepo?",
  "ani more, vehem?",
  "anachnu vehen baot mibayt o mipo?",
  "lean more lerusit ba meulpan?",
  "ata lomed anglit veivrit, vehu?",
  "ma aba lomed bebayt im atem?",
  "aten gam talmidot, veata?",
  "meayn abim baim lesham?",
  "abim achshav baim mikan, veat?",
  "aten talmidot o imot?",
  "abim umorim ovdim im aba, vehi?",
  "eyn more leanglit bebayt?",
  "more ba misham leulpan o lirchov?",
  "abim baim merechov o mipo?",
  "imot lomdot rusit im ima, veatem?",
  "atem morim, vehen?",
  "ata more leanglit, vehem?",
  "hen veanachnu ovdot, vehu?",
  "hi ima?",
  "hem morim leivrit, veatem?",
  "ata ba lirchov meulpan o mikan?",
  "morot vetalmidot ovdot, veat?",
  "hen baot leuniversita o lirchov?",
  "hen talmidot, veaten?",
  "anachnu morot lemuzika, vehem?",
  "aten talmidot, vehu?",
  "hen veatem lomdim ivrit im abim?",
  "talmida ovedet, vehem?",
  "abim umorot lomdim ivrit?",
  "abim baim mipo o misham?",
  "aten baot leuniversita o habayta?",
  "morot lomdot ivrit im aba, vehen?",
  "ata achshav ba lepo, vehu?",
  "hu lomed ivrit verusit, vehi?",
  "at baa lirchov mibayt o mipo?",
  "lean ata ba mipo?",
  "mi morot lemuzika?",
  "lean morim leanglit baim?",
  "ani baa habayta mipo, veaten?",
  "aba ba lirchov meulpan o misham?",
  "ani lomed?",
  "hi baa habayta misham?",
  "abim umorot baim misham lepo?",
  "hu ba lirchov o leuniversita?",
  "meayn atem baim?",
  "morot veimot baot misham, veaten?",
  "ata ba misham lekan, veat?",
  "atem baim lekan?",
  "hem veatem ovdim im imot, veata?",
  "mi baa misham?",
  "morim veimot ovdim, veaten?",
  "anachnu veaten lomdim, vehen?",
  "aba achshav ba lesham mipo?",
  "aba ba misham, vehem?",
  "hem abim, vehi?",
  "hem lo morim, vehi?",
  "morim veimot baim mipo, vehem?",
  "more ba mipo o merechov?",
  "ata ba lepo?",
  "hen morot, veaten?",
  "eyn abim beuniversita?",
  "ani ba habayta, vehem?",
  "ata lo more, vehem?",
  "morot veabim baim lepo, veata?",
  "aten gam morot leanglit, vehem?",
  "atem lo morim lerusit, vehem?",
  "morim baim lesham, vehi?",
  "hu more leivrit, vehi?",
  "atem veaten baim mipo, vehu?",
  "mora baa habayta misham?",
  "hu lomed rusit umuzika, veatem?",
  "ata lo more, veatem?",
  "ma abim lomdim birchov im ata?",
  "morot ovdot im imot, vehi?",
  "atem lomdim?",
  "ani baa lesham mikan, veat?",
  "hi lomedet ivrit, veata?",
  "anachnu lomdim, vehi?",
  "ma more lomed im aba?",
  "mora baa lekan mibayt o meulpan?",
  "hi mora lemuzika?",
  "talmida lomedet muzika im abim?",
  "hu lo talmid, veatem?",
  "more leivrit ba mipo, veaten?",
  "mora baa mibayt o misham?",
  "hen gam morot lerusit, vehu?",
  "ima lomedet muzika, veata?",
  "ata lomed ivrit im ima, veaten?",
  "talmidot baot lekan, veat?",
  "morim lomdim, veata?",
  "hen veatem lomdim, vehem?",
  "eyfo abim vetalmidot lomdim?",
  "morim ovdim, veatem?",
  "ani ba leakademja misham o mipo?",
  "mora lerusit ovedet, vehu?",
  "eyfo morim leanglit lomdim?",
  "aba ba lirchov Sverdlov o lepo?",
  "anachnu gam morim?",
  "more lemuzika ba lesham, vehem?",
  "ani ba misham leulpan o habayta?",
  "hi ovedet im imot, veatem?",
  "anachnu baim lepo o lirchov?",
  "hu gam more leanglit?",
  "mora leanglit ovedet, vehem?",
  "abim achshav baim mipo?",
  "mi ba habayta misham?",
  "lean more ba meakademja?",
  "ma more lerusit lomed im hi?",
  "aten vehem baim mipo?",
  "imot vetalmidot baot lepo, vehem?",
  "hen baot habayta, vehi?",
  "more lomed beakademja o beulpan?",
  "imot baot misham, vehi?",
  "ata talmid o more lerusit?",
  "ani baa mipo lesham, vehi?",
  "mora baa meulpan o merechov?",
  "ani talmida, veat?",
  "imot lomdot, vehu?",
  "ani baa leakademja mipo o meulpan?",
  "lean hen vehem baim mikan?",
  "hem beakademja leivrit o bebayt?",
  "ani ovedet, vehem?",
  "ata ba meulpan o meuniversita?",
  "hem morim leivrit, vehu?",
  "ma more lemuzika lomed im at?",
  "ani lo mora leanglit?",
  "ma mora lomedet?",
  "at talmida o mora?",
  "morim achshav baim mipo, vehu?",
  "anachnu lo morot, vehem?",
  "ani ba misham, vehem?",
  "more lomed ivrit, vehu?",
  "anachnu gam talmidot, veata?",
  "imot umorot leivrit ovdot?",
  "imot umorot lomdot rusit im aba?",
  "aten vehen lomdot anglit umuzika?",
  "morot lemuzika baot habayta?",
  "morot baot mikan lesham, veatem?",
  "hi baa misham o mikan?",
  "hi baa lesham, veatem?",
  "at mora, veata?",
  "hem vehen baim mipo habayta?",
  "ima baa merechov o mibayt?",
  "aten baot lekan, vehem?",
  "talmidot veimot ovdot, veat?",
  "lean mora baa mikan?",
  "imot achshav baot lepo?",
  "abim lomdim beulpan o beakademja?",
  "hen lomdot anglit im aba?",
  "mora baa mipo lesham, vehu?",
  "aba ba lesham mikan?",
  "ma aba lomed birchov im mora?",
  "hi baa lekan?",
  "talmidot baot misham o mipo?",
  "at baa meulpan o mipo?",
  "eyfo anachnu veaten garot?",
  "atem baim lesham mipo?",
  "more lomed ivrit im aba?",
  "talmid ba lirchov o habayta?",
  "hi lomedet rusit veanglit, veata?",
  "aba gar beakademja o beulpan?",
  "ma abim lomdim?",
  "hi baa mipo lesham, vehu?",
  "atem morim lemuzika, veata?",
  "mora baa mipo habayta?",
  "talmid lomed muzika verusit?",
  "atem vehen baim mipo, veat?",
  "aba oved im abim, veata?",
  "eyfo aba lomed anglit veivrit?",
  "abim baim mipo, vehi?",
  "hem veaten lomdim muzika im aba?",
  "abim baim mikan lesham, vehi?",
  "aba lomed ivrit, veaten?",
  "hem baim misham, veat?",
  "morot umorim lerusit ovdim?",
  "imot baot habayta o lekan?",
  "atem morim lerusit, veat?",
  "talmid lomed ivrit veanglit, vehi?",
  "ani mora o talmida?",
  "imot umorot ovdot?",
  "lean abim veimot baim meulpan?",
  "atem vehem achshav baim lepo?",
  "mi gar birchov?",
  "hi lomedet muzika?",
  "aba ba mikan, vehen?",
  "ma mora lerusit lomedet im imot?",
  "eyfo morot leivrit garot?",
  "hi mora lemuzika, vehu?",
  "anachnu gam morot, vehu?",
  "ani ovedet im aba, veatem?",
  "ani lomed, veata?",
  "ani lomed anglit im imot?",
  "at baa mikan o merechov?",
  "ani gam more, veaten?",
  "at ima?",
  "eyfo abim veimot lomdim rusit?",
  "aten baot lesham?",
  "meayn hi baa lirchov?",
  "hen ovdot im ima, veatem?",
  "hen lomdot anglit, veatem?",
  "hen lo morot leanglit, veatem?",
  "meayn atem vehen baim?",
  "morim lemuzika ovdim, veat?",
  "eyfo talmidot ovdot?",
  "ani mora?",
  "anachnu talmidim?",
  "at gam mora leanglit?",
  "atem baim lekan o leuniversita?",
  "hu lomed rusit im aba?",
  "ani ovedet im imot, vehi?",
  "ata ba meulpan o misham?",
  "more ba habayta mipo, veat?",
  "ani lomed muzika, veata?",
  "hen imot, veatem?",
  "hu achshav ba habayta, vehi?",
  "hen imot?",
  "aba ba mipo, vehem?",
  "eyn mora birchov?",
  "hem veaten ovdim, vehi?",
  "atem lomdim rusit veivrit, vehi?",
  "imot baot lepo, vehem?",
  "lean mora leivrit baa?",
  "aba lomed rusit veanglit, vehu?",
  "aba achshav ba lepo, vehen?",
  "hi baa mibayt o misham?",
  "hen talmidot, veatem?",
  "hu aba?",
  "meayn aten vehem baim?",
  "anachnu morot leanglit, vehem?",
  "morim lomdim muzika?",
  "morim umorot baim mipo, veata?",
  "hi baa mipo lesham, veat?",
  "at baa habayta mikan, vehen?",
  "talmida ovedet im abim, vehem?",
  "talmidim ovdim, vehem?",
  "ma talmida lomedet beulpan im hu?",
  "atem talmidim, veata?",
  "more ba lesham?",
  "anachnu morim lemuzika, vehen?",
  "hi lo mora leanglit, veata?",
  "morim veabim lomdim muzika, vehu?",
  "anachnu vehen baim mipo, veaten?",
  "talmidim ovdim?",
  "hu gam aba?",
  "atem abim, veata?",
  "ma morim lomdim im morot?",
  "ma imot lomdot bebayt im aten?",
  "hen veatem ovdim im imot?",
  "eyfo morot lemuzika ovdot?",
  "hu lomed muzika, vehi?",
  "abim umorot leanglit baim mipo?",
  "ani ba habayta, veat?",
  "ima baa leulpan mipo o misham?",
  "hu ba mipo lesham, vehen?",
  "hu talmid, vehi?",
  "eyfo mora lomedet?",
  "aten morot leivrit, vehi?",
  "ima baa habayta, veatem?",
  "hem baim misham lepo, vehi?",
  "at baa mipo lesham, vehem?",
  "atem baim mibayt o merechov?",
  "at ovedet?",
  "imot vetalmidim lomdim rusit?",
  "hu lomed muzika verusit, vehem?",
  "more ba lekan?",
  "hem baim lesham, vehu?",
  "ani baa mikan o mibayt?",
  "abim vetalmidot ovdim, vehi?",
  "anachnu lo morim lemuzika, veatem?",
  "more ba meuniversita o mipo?",
  "ima baa mibayt lesham o lepo?",
  "ani baa meulpan o mipo?",
  "at ovedet im abim?",
  "anachnu abim, veata?",
  "at achshav baa lekan, veata?",
  "aten baot habayta o lekan?",
  "hu ba habayta mikan, veat?",
  "morim baim misham?",
  "talmidim umorot baim mipo, vehen?",
  "eyn morot lemuzika bebayt?",
  "anachnu gam morim lerusit, veata?",
  "mi baa habayta mikan?",
  "hu lo more?",
  "eyfo hen veatem ovdim?",
  "hen baot lesham, vehu?",
  "talmid ba mipo, veat?",
  "ani talmid, veaten?",
  "abim baim lirchov o leulpan?",
  "anachnu gam talmidot, veat?",
  "hen gam imot, vehi?",
  "aba ba merechov leulpan o lesham?",
  "ani talmid, veatem?",
  "ata ba habayta mipo, vehem?",
  "atem lo talmidim?",
  "eyfo morot lomdot?",
  "hen veanachnu ovdot, veatem?",
  "meayn ani ba lekan?",
  "abim veimot lomdim anglit, vehi?",
  "abim umorim baim mipo?",
  "hem ovdim im ima, veat?",
  "hen vehem baim lepo, veat?",
  "lean hu ba?",
  "hen lo morot lemuzika, vehem?",
  "hen lo morot lerusit?",
  "meayn ata ba lekan?",
  "abim beakademja o beulpan?",
  "hem lo abim, veata?",
  "ma abim lomdim im hen veanachnu?",
  "atem lomdim ivrit umuzika, veat?",
  "at baa mipo lesham, veatem?",
  "hen baot lepo misham o mibayt?",
  "eyn abim beulpan?",
  "ata ba lepo misham?",
  "imot baot lekan misham?",
  "atem baim mipo, vehem?",
  "aba oved, veatem?",
  "hem baim lesham o lepo?",
  "hu oved im abim, vehem?",
  "meayn talmida baa lepo?",
  "hen baot lekan misham, vehu?",
  "more ba lepo, veaten?",
  "lean atem vehen baim?",
  "eyfo aten veatem garim?",
  "imot baot meulpan o mipo?",
  "hen baot lesham mikan, vehem?",
  "ima baa misham lepo, vehen?",
  "at lo mora?",
  "hi mora leanglit, vehen?",
  "hi mora leanglit, vehu?",
  "anachnu baim lesham, veata?",
  "atem vehem baim lepo o habayta?",
  "ani ovedet?",
  "atem vehen baim habayta, vehem?",
  "hem abim, veata?",
  "hu lomed anglit im abim?",
  "abim baim lesham meulpan o mipo?",
  "hu ba meulpan lesham o lekan?",
  "anachnu vehen lomdot, vehu?",
  "hi baa mikan, veaten?",
  "hen lomdot rusit?",
  "morim lomdim anglit im ima, vehem?",
  "hem baim lekan, veata?",
  "mora baa misham?",
  "morot baot mikan habayta?",
  "atem veaten ovdim im abim, veat?",
  "ata ba mikan lesham, vehen?",
  "morim lerusit veabim lomdim?",
  "hu ba lepo misham, veat?",
  "ata ba leulpan o lekan?",
  "morim umorot lomdim, veatem?",
  "talmid ba lesham mikan, vehen?",
  "hem vehen achshav baim lekan?",
  "lean more ba?",
  "ata lomed, veatem?",
  "ata gar beuniversita o beakademja?",
  "imot vetalmidot baot lekan?",
  "morot lomdot muzika im imot?",
  "more ba mikan lesham?",
  "ma mora lomedet bebayt im hem?",
  "ima baa mibayt lekan o lesham?",
  "ani oved im abim, veat?",
  "ani ba merechov o mipo?",
  "eyfo morim lomdim?",
  "atem abim, veat?",
  "aba ba mipo, veata?",
  "hu ba lepo o leulpan?",
  "hu lomed anglit im ima, vehen?",
  "abim umorim ovdim im aba, veata?",
  "meayn aten veanachnu baot?",
  "ata gam more lemuzika?",
  "aten veanachnu lomdot, veat?",
  "hen achshav baot lesham mipo?",
  "aten baot mikan?",
  "imot lomdot rusit?",
  "imot veabim baim lesham, veatem?",
  "imot veabim lomdim, vehem?",
  "more lerusit achshav ba misham?",
  "ma more lomed bebayt?",
  "anachnu baim mipo lesham, vehu?",
  "aten vehen baot misham?",
  "at mora lerusit, veaten?",
  "ima lomedet rusit umuzika, veat?",
  "imot veabim baim lepo, vehi?",
  "mi mora lemuzika?",
  "hen gam morot, veat?",
  "hi mora?",
  "hem vehen ovdim, veaten?",
  "ani lo talmida, veata?",
  "anachnu ovdot im aba?",
  "hen achshav baot lesham, vehi?",
  "at lo mora, vehu?",
  "eyfo morim leivrit garim?",
  "morot umorim baim mikan, veatem?",
  "morot ovdot im ima, veat?",
  "imot veabim ovdim, veat?",
  "at gam mora lerusit, veaten?",
  "morim baim mikan lesham?",
  "more oved im aba?",
  "eyn imot beulpan?",
  "mi oved beakademja?",
  "hu ba lepo, veata?",
  "ata oved im ima, vehem?",
  "hu lomed ivrit, veata?",
  "atem vehem baim lesham?",
  "hu ba mikan lesham, veata?",
  "morim veimot baim misham, vehu?",
  "imot veabim lomdim, veatem?",
  "anachnu gam morot, veat?",
  "ma talmid lomed beulpan im hen?",
  "aten vehen baot misham lekan?",
  "eyfo hen vehem garim?",
  "hem veatem baim misham lepo?",
  "abim umorot ovdim im imot, vehen?",
  "ani mora lerusit?",
  "atem veaten ovdim?",
  "atem baim lesham, vehi?",
  "anachnu veaten baot mikan?",
  "at mora lemuzika, vehen?",
  "eyfo ima lomedet muzika?",
  "at ovedet im aba?",
  "hen morot lerusit?",
  "hi baa leakademja mipo o mibayt?",
  "ani achshav baa mikan?",
  "hen bebayt o beakademja?",
  "meayn aba ba lepo?",
  "hi ovedet im ima, vehu?",
  "aba ba lepo, vehu?",
  "aten veatem baim lesham, vehi?",
  "ani lomed muzika veivrit, vehu?",
  "mora lomedet muzika?",
  "abim veimot baim mikan, veat?",
  "imot lomdot ivrit im ima, vehi?",
  "ani gam aba vegam more, veaten?",
  "eyfo ata lomed ivrit?",
  "aba ba mipo lirchov o habayta?",
  "atem baim mipo habayta?",
  "ani baa misham lepo, vehu?",
  "talmidim umorim lomdim, vehi?",
  "aba lomed rusit umuzika, vehu?",
  "atem baim mipo lesham, vehen?",
  "mi lomedet anglit umuzika bebayt?",
  "hem veaten baim lekan, vehu?",
  "hen veatem ovdim im ima, veat?",
  "talmidot ovdot im aba, vehi?",
  "hem vehen ovdim, veat?",
  "aten baot lirchov o lepo?",
  "ani aba o more leivrit?",
  "talmidim baim mipo o misham?",
  "lean hen veanachnu baot?",
  "morim veabim baim lekan, veata?",
  "eyfo hi lomedet muzika veanglit?",
  "ani ba lepo, veatem?",
  "anachnu lomdim ivrit, vehu?",
  "ima baa lepo, vehi?",
  "ma morim lomdim bebayt im at?",
  "atem baim misham, vehu?",
  "talmidim ovdim im imot?",
  "ani lomed ivrit, veat?",
  "ata lomed rusit veivrit?",
  "talmid achshav ba misham lepo?",
  "ma abim lomdim im more?",
  "hu lomed anglit umuzika?",
  "aten ovdot im aba?",
  "eyfo atem veaten garim?",
  "lean mora baa?",
  "at gam talmida?",
  "aba lomed anglit im ima, vehen?",
  "mi baa lepo meuniversita?",
  "mora baa habayta meulpan o mipo?",
  "morim baim lekan o leuniversita?",
  "ata more o aba?",
  "morim baim mikan lesham, veatem?",
  "eyn more beuniversita?",
  "ata lomed anglit veivrit, veat?",
  "hu beakademja o beulpan?",
  "talmidot baot lesham mipo?",
  "hem lomdim rusit, veaten?",
  "ata achshav ba lekan, vehen?",
  "atem vehen lomdim anglit im aba?",
  "ani lomedet ivrit, veat?",
  "ani ba lesham, veat?",
  "mi ba merechov?",
  "ima ovedet, vehen?",
  "hem morim lerusit?",
  "more lomed ivrit?",
  "imot veabim ovdim im ima?",
  "hen talmidot, veat?",
  "more lomed rusit, vehu?",
  "eyfo more lomed?",
  "talmidim baim habayta, vehem?",
  "at baa mibayt habayta o lepo?",
  "yesh mora lerusit birchov?",
  "talmidot umorim lomdim, vehem?",
  "ata aba, vehem?",
  "atem baim mibayt lekan o leulpan?",
  "lean ata ba meuniversita?",
  "hu ba mibayt lirchov o lesham?",
  "aten baot mipo, vehi?",
  "ma mora leanglit lomedet im hen?",
  "abim vetalmidim baim lepo, veat?",
  "anachnu baim habayta o lekan?",
  "atem lomdim anglit, vehem?",
  "aten veanachnu lomdot ivrit?",
  "anachnu abim?",
  "hi ima, vehu?",
  "ma ima lomedet birchov?",
  "morot lomdot anglit, veat?",
  "ani achshav baa misham, veata?",
  "atem abim?",
  "lean ima baa meakademja leivrit?",
  "hu ba mipo habayta o lesham?",
  "ani ba lesham mikan, vehem?",
  "ma more lomed beulpan im hi?",
  "abim baim lesham mipo o merechov?",
  "hu ba mikan habayta, vehem?",
  "aba lomed muzika im imot?",
  "aba ba merechov o mikan?",
  "at achshav baa lepo, vehu?",
  "ata ba meulpan habayta o lepo?",
  "ani baa mibayt lepo o leulpan?",
  "hi baa lekan misham o merechov?",
  "aba ba lepo, veata?",
  "ani more lerusit, vehu?",
  "atem gam morim?",
  "atem vehen ovdim, vehi?",
  "hi gam ima, veat?",
  "ima ovedet im aba, vehem?",
  "more ba lesham o habayta?",
  "talmid ba lepo meulpan o misham?",
  "hu lomed rusit im imot, veatem?",
  "mora baa lepo, vehen?",
  "ma more lomed birchov im atem?",
  "hu ba mikan, veatem?",
  "at mora leanglit o talmida?",
  "abim umorot lemuzika lomdim?",
  "atem veanachnu ovdim, vehu?",
  "aten gam morot leanglit?",
  "ani lomed rusit?",
  "hen ovdot?",
  "hi mora leivrit, veaten?",
  "ma talmidot lomdot im mora?",
  "lean mora baa misham?",
  "abim lomdim anglit, veata?",
  "meayn morot baot?",
  "ma more lomed im ani?",
  "morim ovdim im imot?",
  "ima baa lesham, vehi?",
  "aten ovdot im ima, vehem?",
  "talmida ovedet, vehen?",
  "hi baa misham lepo, veatem?",
  "talmidim umorot lerusit lomdim?",
  "ma more lomed im talmida?",
  "imot lomdot muzika, veaten?",
  "abim umorot ovdim im imot, vehi?",
  "at achshav baa lekan, veaten?",
  "ani lomedet rusit im aba, vehi?",
  "ani baa lekan misham, vehu?",
  "aba ba misham?",
  "anachnu ovdim im imot, vehem?",
  "ani ba mipo, veatem?",
  "aba lomed muzika, veaten?",
  "ma morim leivrit lomdim im ima?",
  "hu lomed ivrit?",
  "hen vehem lomdim ivrit?",
  "ani gam more lemuzika, veata?",
  "atem lo talmidim, veaten?",
  "imot umorot lerusit lomdot, veata?",
  "at lo mora, veata?",
  "eyfo more gar?",
  "ani ba lesham mipo?",
  "ani gam aba, vehi?",
  "morim baim misham lekan?",
  "aten lo morot leanglit, veat?",
  "ani ba habayta misham?",
  "at lomedet, vehi?",
  "hu lo more, veata?",
  "ata more leivrit, vehi?",
  "hen veanachnu baot lepo o lesham?",
  "ima achshav baa lepo, vehen?",
  "lean hem vehen baim merechov?",
  "atem lomdim anglit, vehi?",
  "hu ba mipo, veat?",
  "hi baa merechov lepo o leulpan?",
  "atem vehen baim lepo, veat?",
  "talmida baa lepo, veat?",
  "atem baim misham?",
  "aten lo morot?",
  "meayn hu ba habayta?",
  "atem lomdim muzika im imot?",
  "hu gam aba vegam talmid, vehem?",
  "morim vetalmidim baim lepo, veata?",
  "ata achshav ba mipo, vehu?",
  "hen morot, veata?",
  "mi baa lirchov?",
  "more leanglit lomed, veatem?",
  "more lomed, veata?",
  "more ba lesham, veata?",
  "atem lomdim rusit veivrit?",
  "ani baa lepo misham, veaten?",
  "talmidim achshav baim habayta?",
  "ata ba meulpan lesham o lekan?",
  "ani ba misham?",
  "abim umorim leivrit ovdim im ima?",
  "at lomedet muzika im abim, vehem?",
  "aten vehen baot lesham o lirchov?",
  "aba ba mipo habayta, vehen?",
  "hen veatem lomdim ivrit, vehu?",
  "abim veimot ovdim, veat?",
  "mi ba merechov Sverdlov?",
  "aten veanachnu lomdot?",
  "mora lemuzika lomedet, vehen?",
  "hem baim mipo, veata?",
  "ma aba lomed birchov im hem?",
  "at lomedet ivrit, veaten?",
  "aten baot habayta mipo, vehi?",
  "meayn morim baim leakademja?",
  "lean ani baa mipo?",
  "ma more lomed im talmidot?",
  "talmid ba mipo habayta?",
  "aba ba meulpan o mipo?",
  "eyfo talmidot garot?",
  "hu lo aba?",
  "at ovedet im abim, vehi?",
  "at lomedet rusit im imot?",
  "ani ovedet im imot, vehu?",
  "imot umorim lerusit lomdim?",
  "ani oved, veatem?",
  "ma talmida lomedet im ima?",
  "morot baot lesham o habayta?",
  "morot veimot lomdot rusit im abim?",
  "ani lo more lemuzika, veatem?",
  "imot baot lesham mipo, vehem?",
  "ata more, veat?",
  "ima baa habayta misham, vehu?",
  "anachnu baot lepo misham, veata?",
  "ima achshav baa lekan?",
  "atem baim mipo lesham, vehem?",
  "hen baot lesham mipo, vehem?",
  "hen veanachnu baim lepo?",
  "eyn more lemuzika birchov?",
  "morim achshav baim mipo?",
  "hi baa meulpan o misham?",
  "morot baot misham lepo, vehi?",
  "morim veabim baim lekan, vehem?",
  "ata gam talmid, vehem?",
  "hen baot habayta?",
  "ani mora leanglit, vehu?",
  "at lomedet ivrit umuzika im aba?",
  "lean morot baot meakademja?",
  "morot baot leulpan o lekan?",
  "aten lomdot, veata?",
  "talmidim umorim lemuzika ovdim?",
  "mora leivrit baa lepo, vehu?",
  "hi baa mipo lesham?",
  "aba ba lepo misham, vehu?",
  "ani lo mora lerusit?",
  "morot lemuzika veimot baot misham?",
  "ata lomed rusit im imot?",
  "imot baot habayta mipo o mibayt?",
  "meayn imot baot?",
  "at ima, vehen?",
  "at lo mora lemuzika, vehi?",
  "ani lo more lemuzika, vehen?",
  "morot leivrit baot misham lepo?",
  "hi baa mipo, veaten?",
  "ani ba lekan, vehen?",
  "at lomedet muzika im aba, vehu?",
  "eyfo aten vehen lomdot?",
  "morim ovdim, vehi?",
  "talmidim baim habayta, veat?",
  "morim leivrit veabim baim mipo?",
  "ima ovedet im imot, veat?",
  "hem achshav baim mikan, veata?",
  "at baa merechov o mikan?",
  "aba lomed gam rusit vegam muzika?",
  "ma morim lomdim im imot?",
  "talmid lomed rusit, vehu?",
  "ani lomed anglit im ima, vehem?",
  "ma more leanglit lomed im talmid?",
  "mora baa lekan misham, vehu?",
  "ani oved, veat?",
  "ata lomed muzika im aba?",
  "talmidot umorim baim lekan, vehen?",
  "hem baim mipo habayta, vehen?",
  "eyfo anachnu veaten garim?",
  "mi baa mipo?",
  "anachnu lo talmidot, vehu?",
  "eyfo ani lomed?",
  "hu lomed anglit, vehi?",
  "atem abim o morim lemuzika?",
  "talmid oved im ima, veatem?",
  "eyfo at lomedet muzika veivrit?",
  "mi baa merechov?",
  "ima baa meulpan o mikan?",
  "hen veatem lomdim anglit im ima?",
  "talmid ba mikan lesham, vehem?",
  "atem lo talmidim, veata?",
  "hu lomed, veatem?",
  "aten lomdot anglit, veatem?",
  "ani mora lerusit o ima?",
  "morot lomdot anglit verusit?",
  "talmida lomedet muzika im ima?",
  "abim baim mikan, vehi?",
  "imot umorim baim lepo, veat?",
  "ata ba lesham mikan o merechov?",
  "aten lomdot rusit im abim, vehem?",
  "mi ba lirchov misham?",
  "abim baim mikan habayta?",
  "imot umorim lerusit ovdim, veata?",
  "ata ba merechov lesham o habayta?",
  "aba ba lepo?",
  "abim baim misham lekan?",
  "talmida ovedet im aba, veata?",
  "more leivrit ba lepo misham, vehu?",
  "talmid ba lesham o leulpan?",
  "more lerusit oved im aba, vehi?",
  "hen ovdot im abim, veata?",
  "mi lomed muzika beuniversita?",
  "more lomed anglit verusit im aba?",
  "meayn anachnu baot lesham?",
  "talmida baa lekan?",
  "hi lo mora leivrit, veat?",
  "imot veabim baim lepo?",
  "meayn hem veaten baim habayta?",
  "ma imot lomdot beakademja im hu?",
  "imot umorot lomdot, veata?",
  "ima baa lepo o leulpan?",
  "morim veimot baim mipo, vehi?",
  "aten vehen baot mikan?",
  "aba ba misham lekan, vehu?",
  "talmid ba mikan o meulpan?",
  "abim baim habayta mikan?",
  "ani ba habayta mipo?",
  "ma talmid lomed birchov im hen?",
  "ima baa mibayt o mikan?",
  "hem baim lesham o habayta?",
  "hem lomdim ivrit verusit, veat?",
  "hen baot lepo merechov o misham?",
  "morot baot meulpan lepo o lesham?",
  "talmid oved im aba, vehem?",
  "at baa lepo o lesham?",
  "more oved, veaten?",
  "talmid ba habayta mipo, veata?",
  "hu aba o more?",
  "mi ba lesham?",
  "hi baa mibayt lekan o lesham?",
  "ani gam aba, vehu?",
  "anachnu baot lesham mipo, veata?",
  "morim umorot baim misham?",
  "ma morim lomdim im more?",
  "more lomed rusit im ima?",
  "ata ba lesham mikan, vehen?",
  "ima baa lesham mikan, veatem?",
  "talmida baa lepo?",
  "ma more lomed birchov im hem?",
  "more leanglit ba misham o mipo?",
  "ima lomedet, vehi?",
  "abim vetalmidim ovdim, vehu?",
  "morim baim habayta mipo, vehu?",
  "more ba mikan habayta, veatem?",
  "morim veimot lomdim rusit im ima?",
  "more ba lepo, veat?",
  "ani ba meulpan o mibayt?",
  "morot leivrit baot mikan?",
  "more leanglit lomed, vehu?",
  "imot ovdot im ima, veata?",
  "hen veanachnu baot mipo?",
  "morim veimot baim lekan?",
  "ani baa lirchov mibayt o meulpan?",
  "aten ovdot, veatem?",
  "abim umorot baim mipo, vehu?",
  "aba ba meuniversita o mibayt?",
  "mi more leanglit?",
  "aba ba mipo?",
  "aten veanachnu baim mikan, vehu?",
  "morot baot leuniversita o lepo?",
  "ani more leanglit, veata?",
  "more lomed muzika veivrit?",
  "aba gar bebayt o beakademja?",
  "ima baa mikan lesham, vehem?",
  "lean ani baa meakademja?",
  "ani mora leivrit, veat?",
  "hem veatem lomdim muzika veivrit?",
  "morot baot mipo, vehen?",
  "hem lomdim anglit, veaten?",
  "hi baa lekan o leulpan?",
  "morim veimot baim mipo, veat?",
  "aten vehen ovdot im imot, vehu?",
  "ani achshav baa mipo, vehen?",
  "anachnu ovdim im aba, veaten?",
  "ata ba lesham mibayt o meulpan?",
  "anachnu lomdot anglit im imot?",
  "more lemuzika ba merechov o mipo?",
  "more ba mikan lesham o habayta?",
  "talmidot baot lepo, vehen?",
  "aten lo morot lerusit?",
  "mi baa merechov habayta?",
  "more leivrit oved im ima, veaten?",
  "hen vehem baim lepo?",
  "ima lomedet, vehu?",
  "hi baa mipo o merechov?",
  "anachnu baim lekan, vehi?",
  "hu lomed ivrit im aba, veata?",
  "abim lomdim muzika, veaten?",
  "mora baa misham, veata?",
  "ma aba lomed beulpan im hu?",
  "mi ovedet im abim beakademja?",
  "abim vetalmidot baim misham?",
  "ma talmida lomedet im hu?",
  "ma aba lomed im morot lerusit?",
  "atem veaten baim mikan, vehi?",
  "mi lomed beulpan?",
  "hem gam morim leivrit, vehu?",
  "more lomed, vehu?",
  "eyn imot birchov Komsomolskaja?",
  "atem vehem baim mipo, veat?",
  "talmida lomedet anglit, vehem?",
  "more ba habayta o lepo?",
  "atem baim lekan, veat?",
  "aba achshav ba lepo, veat?",
  "morim baim misham o mipo?",
  "anachnu lo imot, veaten?",
  "ma imot lomdot bebayt im hu?",
  "aba ba lesham mikan, vehem?",
  "at baa lesham mikan?",
  "ani mora leivrit o talmida?",
  "aba lomed, veaten?",
  "hen baot mipo, vehem?",
  "hen baot habayta mikan?",
  "hen lomdot beulpan o bebayt?",
  "aten veanachnu lomdot muzika?",
  "at baa habayta o lirchov?",
  "hi lomedet muzika, vehu?",
  "hu ba merechov lesham o lepo?",
  "ani lo talmida, vehi?",
  "at lo ima?",
  "anachnu lo morim, vehem?",
  "talmida baa misham lekan?",
  "hen veanachnu ovdot im aba, veat?",
  "hem baim lepo, vehen?",
  "lean ata ba mibayt?",
  "atem baim lesham mikan, veat?",
  "mi lomed birchov Sverdlov?",
  "at baa habayta, vehu?",
  "talmidot ovdot im imot?",
  "hi baa misham, veat?",
  "aten veatem baim mikan, vehu?",
  "morot veimot lomdot?",
  "ma more lomed im aten vehen?",
  "morim umorot baim lepo, veaten?",
  "ima baa mikan, vehem?",
  "ani baa meulpan habayta o lesham?",
  "hu ba habayta o lesham?",
  "morot vetalmidim lomdim, vehen?",
  "anachnu lo morot, veat?",
  "morot ovdot im aba, vehem?",
  "more leivrit ba misham, veata?",
  "at achshav baa lesham?",
  "ani lo more leivrit, veata?",
  "talmida lomedet, veat?",
  "mora baa lesham, vehi?",
  "abim baim misham, vehem?",
  "ata ba meulpan lesham o lepo?",
  "morot lomdot, vehu?",
  "talmidim baim mibayt o misham?",
  "at baa mipo, vehem?",
  "anachnu ovdot im ima, veat?",
  "hi gam talmida?",
  "eyfo hem lomdim rusit?",
  "more lomed ivrit im aba, veatem?",
  "yesh mora beuniversita?",
  "aten baot mikan, veatem?",
  "more ba meulpan lepo o habayta?",
  "talmida ovedet, vehu?",
  "imot veabim lomdim anglit?",
  "ani ba merechov leulpan o lepo?",
  "imot vetalmidim baim mipo?",
  "aten lomdot rusit im ima, vehu?",
  "anachnu baot mipo habayta, veaten?",
  "ani ba lepo o habayta?",
  "abim achshav baim lepo, veat?",
  "at baa mikan, vehi?",
  "meayn hu ba?",
  "morim baim leulpan o lirchov?",
  "at achshav baa lesham, vehu?",
  "aba ba mipo lesham?",
  "talmid ba habayta, veaten?",
  "mi ba lepo meuniversita?",
  "mi lomed ivrit im ima beulpan?",
  "aten imot o morot lerusit?",
  "ata ba mipo, veaten?",
  "ani baa lesham mipo, vehem?",
  "aten veanachnu ovdim im aba?",
  "at lomedet rusit im aba, vehi?",
  "hen imot, vehem?",
  "mora gara beulpan o bebayt?",
  "hu gam talmid, veatem?",
  "at baa lesham mibayt o mipo?",
  "lean hen baot?",
  "ma morot lomdot im hen veaten?",
  "lean hen vehem baim?",
  "at lomedet anglit veivrit?",
  "imot lomdot ivrit umuzika?",
  "aten vehem baim mipo o merechov?",
  "ata lomed ivrit?",
  "ani lomed ivrit im abim?",
  "talmida baa mikan lesham, veata?",
  "aba lomed anglit im imot, veat?",
  "abim umorim ovdim im ima, veata?",
  "mora baa misham o merechov?",
  "more lomed rusit im imot, veatem?",
  "ma more lomed beulpan im aten?",
  "mi baa mibayt lesham?",
  "meayn ata ba leakademja?",
  "aten baot lirchov mibayt o mipo?",
  "meayn ata ba?",
  "more leanglit oved?",
  "morot veabim ovdim, vehu?",
  "ata ba habayta misham, vehu?",
  "talmidim baim lepo misham, vehem?",
  "aba gar beulpan o beuniversita?",
  "aten vehem lomdim rusit?",
  "talmidot umorot lomdot ivrit?",
  "hu ba meakademja lepo o lesham?",
  "hu lomed gam anglit vegam rusit?",
  "mora leivrit baa lekan?",
  "ima ovedet, veat?",
  "morot baot lesham?",
  "morot baot lekan, veat?",
  "mora lerusit baa lesham?",
  "atem baim misham lekan?",
  "ani ovedet im abim, vehen?",
  "anachnu veaten baim mikan?",
  "meayn talmida baa?",
  "meayn more lemuzika ba lekan?",
  "ani ima o mora?",
  "morim baim lirchov mipo o misham?",
  "at baa habayta misham?",
  "hu achshav ba lekan, veat?",
  "mora lomedet ivrit im abim?",
  "hi lomedet rusit veanglit?",
  "hem ovdim im ima?",
  "at achshav baa lekan, veatem?",
  "ani gam ima?",
  "morot baot habayta, veat?",
  "ani lo more leivrit, veat?",
  "hen vehem lomdim ivrit, veaten?",
  "ata lomed rusit veanglit im aba?",
  "anachnu gam imot?",
  "ma aba lomed im morot leanglit?",
  "anachnu veatem lomdim ivrit?",
  "ani ba lesham mikan, vehu?",
  "hu ba lekan misham, veat?",
  "morot lerusit ovdot, veat?",
  "ani lomed anglit im aba, veaten?",
  "hu lomed rusit im abim, vehem?",
  "eyn talmid beuniversita?",
  "more oved, veatem?",
  "abim veimot lomdim anglit im aba?",
  "hu ba misham habayta, veatem?",
  "hem baim leulpan merechov o mipo?",
  "hem baim habayta o lirchov?",
  "meayn more ba lepo?",
  "imot lomdot?",
  "abim veimot ovdim, vehu?",
  "hu ba leulpan o lesham?",
  "meayn mora baa leuniversita?",
  "hi gam ima, vehem?",
  "talmid ba lepo o habayta?",
  "talmidot umorot ovdot?",
  "ani lomed rusit im imot, vehu?",
  "ani baa lepo misham, veat?",
  "ani gam mora, veatem?",
  "ani lomedet anglit im imot?",
  "ani oved, veata?",
  "ata talmid, vehu?",
  "aten lo imot?",
  "morim ovdim im abim, vehen?",
  "mora baa mipo, vehu?",
  "lean mora baa merechov?",
  "hu achshav ba mipo, vehen?",
  "atem abim, vehem?",
  "lean hem baim mipo?",
  "abim baim lesham o leulpan?",
  "aten ovdot im abim, vehu?",
  "hi mora, veatem?",
  "anachnu veaten baot mikan, vehi?",
  "ani ba mipo, veat?",
  "meayn hu ba leulpan?",
  "talmid lomed muzika?",
  "at lomedet muzika?",
  "eyfo abim lomdim?",
  "hen baot lepo, vehi?",
  "abim lomdim muzika veivrit, vehu?",
  "eyfo hu lomed?",
  "ata lomed anglit, vehen?",
  "hem baim mipo o mibayt?",
  "imot umorim lomdim muzika, vehen?",
  "anachnu morim o abim?",
  "eyfo hu oved?",
  "ma more leanglit lomed im hem?",
  "hi achshav baa lepo, veatem?",
  "at baa lirchov mikan o mibayt?",
  "morim lemuzika baim misham?",
  "atem baim lepo o leulpan?",
  "hen baot lesham?",
  "hu more leivrit, vehen?",
  "at achshav baa lekan, vehi?",
  "ani lo mora, vehen?",
  "ani achshav ba lesham, vehem?",
  "aten baot lepo, vehu?",
  "ma ima lomedet beuniversita?",
  "anachnu gam abim, vehen?",
  "aten vehem lomdim, veata?",
  "ma talmida lomedet im atem?",
  "mi ba mipo leulpan?",
  "ata lomed?",
  "aten vehem baim habayta mikan?",
  "ma aba lomed beakademja im hu?",
  "abim veimot ovdim im aba, veat?",
  "hen baot lepo, veaten?",
  "abim baim habayta mipo o merechov?",
  "hen baot misham, vehi?",
  "at lomedet rusit?",
  "hen veaten baot lepo, veat?",
  "eyn talmidim beulpan?",
  "ima baa lesham o lirchov?",
  "ani ba lirchov o lepo?",
  "talmidot veabim baim mipo, veat?",
  "hen lomdot, vehu?",
  "at lomedet ivrit im aba?",
  "hem vehen lomdim muzika, veat?",
  "aba ba mibayt lesham o lirchov?",
  "hu ba habayta misham, vehi?",
  "hen imot o morot?",
  "hen veanachnu baot mikan?",
  "mora baa mibayt o meulpan?",
  "more lomed ivrit verusit?",
  "ata oved im ima, vehu?",
  "imot umorim baim lepo, veata?",
  "aba lomed anglit umuzika, vehu?",
  "aten ovdot, vehu?",
  "imot vetalmidot ovdot?",
  "morot lemuzika ovdot?",
  "ani talmida, vehi?",
  "imot baot habayta, veata?",
  "hi lomedet rusit im ima, vehen?",
  "ima baa lepo, veat?",
  "hi baa mikan o mibayt?",
  "ata ba misham, vehu?",
  "hen veanachnu lomdot, veatem?",
  "imot umorot baot lepo, veat?",
  "hen lo morot, vehu?",
  "ma ima lomedet im atem?",
  "ani oved im imot, vehem?",
  "hen lomdot anglit im ima?",
  "talmid ba mikan, vehen?",
  "hen morot leivrit?",
  "ani lomedet anglit umuzika, vehu?",
  "anachnu morot lerusit, vehem?",
  "mi baa meulpan leuniversita?",
  "aba lomed?",
  "ani oved im abim, veaten?",
  "mi baa merechov Sverdlov?",
  "aten ovdot im aba, veatem?",
  "ma more leivrit lomed im ima?",
  "hu ba habayta misham, veatem?",
  "anachnu imot o morot?",
  "more oved im ima, veata?",
  "talmidim veimot lomdim?",
  "ani baa lekan, vehu?",
  "mi mora lerusit?",
  "hu gam aba vegam talmid, vehi?",
  "atem gam talmidim, vehu?",
  "ima baa habayta o lekan?",
  "aten veanachnu ovdim, vehen?",
  "meayn aba ba?",
  "more leanglit achshav ba mikan?",
  "mi baa mibayt lekan?",
  "anachnu veaten lomdim, veata?",
  "ma talmida lomedet bebayt im imot?",
  "abim umorot lomdim, veat?",
  "imot lomdot ivrit?",
  "ani mora, vehen?",
  "ima lomedet anglit umuzika?",
  "hu ba lekan misham o merechov?",
  "ani baa mikan lesham, veatem?",
  "abim umorot baim mikan, vehem?",
  "hen talmidot, vehu?",
  "hi baa habayta?",
  "more lomed ivrit im ima, veatem?",
  "atem lomdim rusit veivrit, veat?",
  "hi mora, veaten?",
  "abim baim mibayt o merechov?",
  "ma aba lomed im ata?",
  "talmidot ovdot im ima, veat?",
  "morot umorim ovdim, vehi?",
  "imot ovdot im aba, vehi?",
  "lean mora lerusit baa meakademja?",
  "aten baot meuniversita o mibayt?",
  "atem morim?",
  "morot leanglit lomdot, vehu?",
  "ani ba lesham?",
  "abim umorot lerusit lomdim?",
  "aba ba leulpan o habayta?",
  "meayn hen vehem baim lekan?",
  "atem vehen baim meulpan o mibayt?",
  "atem baim lepo, veaten?",
  "hen achshav baot mipo, vehu?",
  "ani gam mora, veat?",
  "hem achshav baim habayta, vehu?",
  "hem lo abim, veat?",
  "hen imot, vehi?",
  "hu achshav ba mikan, veatem?",
  "hen veanachnu baim mikan, veata?",
  "hi baa misham, vehem?",
  "talmid ba misham o mipo?",
  "ani lo ima, veatem?",
  "hem morim, vehu?",
  "hen talmidot o morot?",
  "ani ba mipo o misham?",
  "atem veanachnu ovdim, veat?",
  "morot leivrit ovdot?",
  "imot achshav baot misham, vehi?",
  "ani lo talmid, vehem?",
  "more leivrit ba lepo, vehi?",
  "mora baa misham lepo, vehu?",
  "ani ovedet, vehen?",
  "imot baot mipo o meulpan?",
  "talmid ba habayta mikan o misham?",
  "anachnu morim lemuzika?",
  "at baa meuniversita o mikan?",
  "hen lo morot lemuzika, veaten?",
  "morim lerusit veabim lomdim, veat?",
  "talmid ba misham habayta, veat?",
  "ani ba mipo o meulpan?",
  "abim baim lesham, veatem?",
  "hu lomed rusit, vehem?",
  "more ba misham o mipo?",
  "at baa misham lepo?",
  "meayn talmidim baim?",
  "hi lomedet muzika, vehem?",
  "ani gam talmida, vehen?",
  "ani achshav ba mikan, veaten?",
  "ani more lemuzika, veat?",
  "morim lomdim ivrit?",
  "ani baa lesham mipo?",
  "talmid ba meuniversita o misham?",
  "hi talmida, vehem?",
  "at baa misham o merechov?",
  "hem morim leanglit, vehi?",
  "more lomed ivrit im aba, vehen?",
  "hem veaten achshav baim lekan?",
  "anachnu morim, veat?",
  "ani ba lepo, vehu?",
  "meayn imot baot leuniversita?",
  "anachnu lomdot rusit?",
  "talmidim ovdim, veat?",
  "hi mora, vehen?",
  "at ovedet im imot, veatem?",
  "morot beulpan o bebayt?",
  "meayn aten vehem baim lepo?",
  "mi gar beakademja?",
  "atem veaten lomdim muzika?",
  "eyfo ani more?",
  "abim umorim ovdim?",
  "aba ba misham o merechov?",
  "at lomedet muzika verusit?",
  "ata lomed ivrit im abim, veat?",
  "atem gam morim vegam talmidim?",
  "ma morim leivrit lomdim im morot?",
  "hu achshav ba lekan, veaten?",
  "more ba lirchov o leulpan?",
  "meayn hen vehem baim lepo?",
  "hen gam morot lerusit, vehi?",
  "ata ba mikan, veaten?",
  "hen veatem lomdim muzika, veat?",
  "mora bebayt o beakademja?",
  "ma morim lemuzika lomdim im hi?",
  "imot veabim baim mipo?",
  "eyn morim beulpan?",
  "ma imot lomdot?",
  "meayn anachnu veaten baot leulpan?",
  "talmid ba meulpan lepo o lirchov?",
  "hu lomed, vehi?",
  "talmidot ovdot, vehen?",
  "morim ovdim im abim, veata?",
  "ata ba mipo, veatem?",
  "talmid lomed ivrit umuzika, vehu?",
  "abim vetalmidot ovdim, vehu?",
  "mora lomedet rusit umuzika im aba?",
  "aten baot misham, veat?",
  "mi baa mibayt lepo?",
  "ani lomed anglit, vehu?",
  "ata ba habayta mipo, veaten?",
  "at baa lekan, vehen?",
  "hi baa habayta, vehu?",
  "at lomedet rusit umuzika, vehu?",
  "hu lomed rusit veivrit, veat?",
  "abim umorim ovdim, veat?",
  "lean atem baim meulpan?",
  "anachnu achshav baim mikan, vehi?",
  "ima lomedet, veat?",
  "imot vetalmidot baot habayta?",
  "ani aba, vehu?",
  "atem baim habayta, veaten?",
  "mi lomed beakademja?",
  "hu ba mibayt lekan o habayta?",
  "eyn mora leivrit birchov?",
  "talmid oved im imot, vehi?",
  "eyfo ani gar?",
  "meayn anachnu baim leuniversita?",
  "imot lomdot anglit?",
  "mora achshav baa misham, veaten?",
  "mora baa lepo, vehu?",
  "morot umorim lerusit baim lekan?",
  "more leanglit ba habayta, vehi?",
  "morot veabim baim mipo, veat?",
  "hen achshav baot habayta, vehem?",
  "atem vehem ovdim im aba?",
  "aten lomdot rusit veivrit, veat?",
  "imot umorim lemuzika baim mikan?",
  "ma morot lomdot?",
  "talmid ba lekan, vehi?",
  "ani gam mora, vehi?",
  "morim lomdim rusit im ima?",
  "hi baa lepo o leuniversita?",
  "aba lomed ivrit im imot?",
  "lean anachnu vehen baim?",
  "talmid ba mikan lesham, vehu?",
  "at gam talmida, vehem?",
  "ma talmid lomed?",
  "morot umorim baim lepo, vehem?",
  "atem baim lepo, veat?",
  "anachnu imot, vehem?",
  "atem baim mipo, veaten?",
  "lean hen veaten baot merechov?",
  "hi baa misham lepo o lirchov?",
  "morot baot mikan habayta, veat?",
  "atem vehem beulpan o bebayt?",
  "morim leivrit lomdim, vehem?",
  "eyfo more lomed anglit umuzika?",
  "ata gam talmid?",
  "talmida baa lirchov o lepo?",
  "talmid oved, vehem?",
  "talmid lomed anglit, veat?",
  "eyfo mora lomedet ivrit?",
  "talmid ba lepo misham, vehen?",
  "more ba leulpan o leuniversita?",
  "ani lo aba, vehem?",
  "hi lo ima, vehen?",
  "hen veatem baim mipo o mibayt?",
  "hu ba habayta mikan, veatem?",
  "hem baim lirchov o leulpan?",
  "hu achshav ba mikan, veat?",
  "morim baim lepo misham, vehu?",
  "lean more ba meakademja lerusit?",
  "hi gam ima vegam mora lemuzika?",
  "hu ba mikan?",
  "hi ovedet im aba, vehem?",
  "yesh more bebayt?",
  "hen morot lemuzika?",
  "hu ba misham o mikan?",
  "mora leivrit baa mikan?",
  "atem veaten lomdim, vehu?",
  "at baa mipo o mibayt?",
  "morim lerusit ovdim?",
  "aba achshav ba lepo, vehem?",
  "hu ba mipo lesham o leulpan?",
  "hem veatem lomdim anglit im aba?",
  "mi talmidim?",
  "aba ba lesham?",
  "ani ba habayta mikan, vehem?",
  "ma talmid lomed im hu?",
  "hu lo more lemuzika, veaten?",
  "ata ba lekan, vehu?",
  "mi baa lirchov Sverdlov?",
  "imot achshav baot lesham mikan?",
  "eyfo atem lomdim?",
  "mora beulpan o beakademja?",
  "hen veatem achshav baim habayta?",
  "atem veanachnu lomdim, vehu?",
  "talmidim umorot leivrit baim lepo?",
  "hi ovedet im ima, veat?",
  "more lerusit achshav ba lepo?",
  "hi baa mikan o misham?",
  "yesh talmid beulpan?",
  "aba achshav ba lesham, vehi?",
  "morot lemuzika lomdot, veata?",
  "ima gara bebayt o beakademja?",
  "ma aba lomed birchov im hi?",
  "talmida baa lekan misham?",
  "hi lomedet muzika im ima, vehen?",
  "ata lo more leivrit, vehu?",
  "hen baot mipo, vehi?",
  "ima achshav baa lesham, vehen?",
  "ma more lomed bebayt im hi?",
  "talmida baa habayta mikan, vehem?",
  "hem baim mipo lirchov o leulpan?",
  "hen veatem lomdim muzika, vehu?",
  "ani lomedet, veaten?",
  "hi achshav baa mipo lesham, veat?",
  "morot ovdot?",
  "talmid ba habayta mikan, vehem?",
  "mora baa lepo merechov o misham?",
  "mora achshav baa lesham?",
  "imot baot merechov o misham?",
  "mora baa mipo o misham?",
  "morim beuniversita o bebayt?",
  "hu gar beakademja o bebayt?",
  "anachnu gam morot lerusit, vehen?",
  "at baa lepo?",
  "hem achshav baim lekan, veatem?",
  "hu ba misham habayta?",
  "mi ba meuniversita?",
  "morim baim lekan, vehi?",
  "hu oved im aba, vehi?",
  "aba ba merechov leulpan o lepo?",
  "talmidot ovdot, veatem?",
  "imot baot habayta, veaten?",
  "hem lomdim ivrit veanglit, veat?",
  "hem veanachnu lomdim, veat?",
  "eyn akademja birchov Sverdlov?",
  "aten vehem ovdim?",
  "aten ovdot im imot, veata?",
  "talmid lomed, vehi?",
  "talmidot umorim ovdim, vehi?",
  "hen gam morot?",
  "morot baot merechov o meulpan?",
  "ata lomed ivrit umuzika, veaten?",
  "lean ani ba meakademja?",
  "ata ba lepo mibayt o meulpan?",
  "ima ovedet im abim, veaten?",
  "more beuniversita o bebayt?",
  "morim veabim lomdim, vehu?",
  "hen baot misham?",
  "ima baa habayta misham, vehen?",
  "anachnu vehen lomdim?",
  "hem ovdim im ima, vehen?",
  "at achshav baa lekan, vehen?",
  "hu ba lesham mipo o mibayt?",
  "ani ba mipo lesham?",
  "ima baa mipo habayta, vehi?",
  "hi baa leulpan mikan o misham?",
  "hu ba mipo habayta, vehen?",
  "aten veanachnu ovdot, veat?",
  "atem ovdim im ima, veaten?",
  "yesh talmidim bebayt?",
  "ani lomed muzika im abim, vehu?",
  "mora ovedet im ima, veaten?",
  "hen lomdot rusit im ima, vehu?",
  "talmidot umorim baim misham, veat?",
  "meayn morim baim lepo?",
  "ani lomed rusit im aba, vehi?",
  "more ba mikan habayta, vehi?",
  "morot umorim baim lekan?",
  "morot lomdot rusit, vehen?",
  "aba oved im abim, veaten?",
  "aten veanachnu baim lepo o lesham?",
  "ata ba leulpan misham o merechov?",
  "ma ima lomedet im hen vehem?",
  "hi baa lekan mibayt o merechov?",
  "aten vehem baim lekan?",
  "morim umorot ovdim, vehen?",
  "morot baot misham habayta, veat?",
  "aten baot leulpan o lekan?",
  "mora baa mikan lesham, veata?",
  "ani oved bebayt o beulpan?",
  "atem morim, vehu?",
  "anachnu abim, veatem?",
  "ma abim lomdim im hem veatem?",
  "ani lo more, vehen?",
  "morot lerusit baot lekan?",
  "mi baa meulpan lekan?",
  "aten vehen baot misham, vehu?",
  "mi morim lerusit?",
  "ima baa mibayt habayta o lepo?",
  "hem veanachnu ovdim im abim?",
  "ata oved im imot, vehu?",
  "ma mora lerusit lomedet im abim?",
  "aten vehen baot lepo?",
  "hem ovdim, vehu?",
  "more ba meulpan o merechov?",
  "mora baa misham lekan, vehem?",
  "ma talmid lomed im morim lerusit?",
  "anachnu vehen baot lepo?",
  "hi mora o talmida?",
  "aba lomed rusit im imot?",
  "mi ba misham leuniversita?",
  "ani ba mikan, vehu?",
  "hem veatem baim habayta, vehu?",
  "eyfo at lomedet anglit?",
  "hem vehen baim lesham, veat?",
  "hem veaten baim lekan, veatem?",
  "aten vehem ovdim im imot, vehi?",
  "morot baot mipo, vehi?",
  "aba ba habayta?",
  "ani baa lekan?",
  "aba lomed, veata?",
  "talmid ba mikan, veatem?",
  "ani talmid, veat?",
  "aba ba lesham mipo o mibayt?",
  "talmidot umorot leanglit ovdot?",
  "hem baim habayta, veaten?",
  "aba ba misham, veaten?",
  "aba ba misham leulpan o lekan?",
  "hi baa habayta mikan, vehen?",
  "ima baa habayta misham?",
  "ima baa habayta, veaten?",
  "at ima, vehu?",
  "at baa lesham o lepo?",
  "hu aba, vehi?",
  "ima baa mibayt leulpan o lesham?",
  "hem baim habayta, vehu?",
  "imot lomdot anglit, vehi?",
  "at baa merechov lekan o lesham?",
  "talmid ba misham lekan, vehu?",
  "at lo mora lemuzika?",
  "atem baim lirchov o lepo?",
  "ima baa mipo, veat?",
  "anachnu baot lepo, veaten?",
  "aten baot lepo?",
  "talmidot ovdot?",
  "ima ovedet im aba, veaten?",
  "hu achshav ba misham, vehem?",
  "hu ba mipo habayta o lirchov?",
  "aten baot meulpan lesham o lepo?",
  "ani oved im abim, vehem?",
  "more leanglit ba lekan, vehi?",
  "ani lomed ivrit?",
  "imot veabim baim habayta o lekan?",
  "atem ovdim?",
  "aten veatem lomdim, vehu?",
  "ani baa mikan, veat?",
  "hu more?",
  "hu ba habayta, veaten?",
  "meayn aten baot lirchov?",
  "aba ba misham lepo, veat?",
  "lean hen baot merechov?",
  "at ovedet im abim, veaten?",
  "imot veabim baim misham, vehem?",
  "abim baim habayta o lekan?",
  "eyfo aten garot?",
  "talmidim baim mikan, veaten?",
  "morim leanglit lomdim, vehem?",
  "aba ba misham, vehi?",
  "ani ba habayta o lekan?",
  "more oved im abim, vehu?",
  "ata achshav ba misham?",
  "ata lomed muzika im imot, vehu?",
  "morim lemuzika umorot baim lekan?",
  "talmidot veabim baim lesham?",
  "ata gam more leivrit?",
  "aba ba lesham, veatem?",
  "hi achshav baa lesham?",
  "hi baa mipo, vehu?",
  "ani lomed muzika, veat?",
  "ima baa lepo misham, vehu?",
  "at baa mikan o meuniversita?",
  "morot lomdot ivrit, vehi?",
  "hi baa mikan?",
  "hem baim leulpan misham o mipo?",
  "more leivrit ba misham, veaten?",
  "eyfo anachnu garim?",
  "mi baa mikan?",
  "anachnu veaten baot misham lekan?",
  "hi mora, vehem?",
  "meayn anachnu vehem baim lepo?",
  "hem gam talmidim, veat?",
  "aba lomed ivrit, vehi?",
  "ma imot lomdot im atem?",
  "aba lomed ivrit im abim?",
  "talmid ba mipo o meulpan?",
  "ma morot lomdot im at?",
  "mi ba meulpan lepo?",
  "talmidot lomdot muzika, veat?",
  "ani baa habayta misham, vehen?",
  "morim baim misham leulpan o lepo?",
  "ma more lomed?",
  "ma more lomed beulpan im at?",
  "abim baim habayta mipo?",
  "hen gam morot lemuzika, veaten?",
  "hen ovdot im imot, veatem?",
  "hen baot mipo lesham o lirchov?",
  "lean talmida baa merechov?",
  "aten imot, veatem?",
  "hen veatem lomdim rusit?",
  "hu lomed ivrit umuzika?",
  "ani lo ima, veat?",
  "anachnu vehem lomdim ivrit?",
  "ani lo more lerusit, veat?",
  "morot lomdot rusit, veat?",
  "eyfo ata lomed muzika?",
  "hi lomedet muzika im ima?",
  "morim baim lepo misham?",
  "hen ovdot im abim?",
  "hu ba lesham?",
  "talmida baa mikan, vehem?",
  "talmid ba lepo, veatem?",
  "lean more leanglit ba mipo?",
  "eyfo morim garim?",
  "hem lomdim rusit veanglit?",
  "ata ba habayta?",
  "more ba habayta mikan, veaten?",
  "ata ba mipo, veat?",
  "ani lomed ivrit im aba, veatem?",
  "hu ba habayta, veatem?",
  "hi baa leulpan o lesham?",
  "anachnu morot leivrit, veata?",
  "hu ba lepo, veatem?",
  "hu ba lekan misham, vehem?",
  "ani ba misham habayta, vehen?",
  "meayn mora leivrit baa?",
  "ata gam more lerusit, veat?",
  "mora lomedet ivrit verusit, veata?",
  "more ba mipo?",
  "ima lomedet, vehem?",
  "ani ba lekan meulpan o mibayt?",
  "mi ba leulpan merechov?",
  "aten baot lekan, veata?",
  "abim baim habayta mibayt o mipo?",
  "hen imot, vehu?",
  "anachnu vehen lomdim, veata?",
  "mora ovedet im abim, vehu?",
  "morot veimot baot mipo?",
  "atem lomdim muzika, veat?",
  "hu bebayt o beulpan?",
  "mi ba meuniversita lesham?",
  "morim lomdim muzika im ima?",
  "mi lomed muzika birchov?",
  "ani baa lesham mikan o mibayt?",
  "eyn morim lerusit beulpan?",
  "abim baim mikan lesham?",
  "hem baim lesham?",
  "mora leivrit baa lesham, vehu?",
  "hem veaten baim lesham, veata?",
  "ata ba misham, veat?",
  "hi gam ima vegam mora?",
  "ima baa mikan, vehu?",
  "hem ovdim im imot, veatem?",
  "ani baa lekan, veatem?",
  "ani lomed rusit, vehi?",
  "meayn aten baot habayta?",
  "hu more lemuzika, vehi?",
  "morot baot misham, vehu?",
  "ani gam ima vegam mora?",
  "ani gam talmid, veatem?",
  "hi baa mipo leulpan o lesham?",
  "imot veabim ovdim, vehu?",
  "more ba mibayt o misham?",
  "talmidot baot lekan, vehi?",
  "aten veatem ovdim?",
  "talmidim umorim baim lekan, vehi?",
  "meayn hi baa lepo?",
  "ma ima lomedet im talmida?",
  "imot umorim baim misham lekan?",
  "hu ba habayta misham o mikan?",
  "hen veaten baot mibayt o mikan?",
  "more lomed rusit umuzika, vehi?",
  "at baa mipo lesham, vehi?",
  "imot beakademja o bebayt?",
  "more oved im imot, vehu?",
  "hu more leivrit, veatem?",
  "ima baa mikan lesham, veaten?",
  "hen baot misham lekan?",
  "anachnu vehen ovdim?",
  "at lomedet ivrit?",
  "hi baa mipo habayta o leulpan?",
  "at gam mora lemuzika, vehem?",
  "more lomed anglit?",
  "talmidim baim lesham?",
  "anachnu talmidot, vehi?",
  "ata ba meakademja habayta o lekan?",
  "morot umorim lomdim, veat?",
  "talmidot bebayt o beulpan?",
  "ani ba lekan, veaten?",
  "hu more lemuzika o talmid?",
  "eyfo aten morim lerusit?",
  "atem vehen ovdim im imot?",
  "hem baim lesham mipo, veatem?",
  "more lemuzika ba lepo misham?",
  "hu gam more lemuzika, vehi?",
  "hu ba mipo lesham?",
  "mora bebayt o beuniversita?",
  "mora leanglit ovedet im imot?",
  "ma imot lomdot bebayt im morim?",
  "at baa lesham, vehem?",
  "mi lomed birchov?",
  "abim veimot baim misham?",
  "at lomedet ivrit, vehem?",
  "ata lo more leanglit, veat?",
  "talmida lomedet anglit, vehi?",
  "aten lomdot anglit, vehem?",
  "abim umorim baim mipo, vehem?",
  "ma imot lomdot im anachnu vehem?",
  "aba ba misham leulpan o lepo?",
  "hen vehem ovdim, vehu?",
  "hi gam ima, veaten?",
  "ani more, vehen?",
  "aten baot lekan, veatem?",
  "yesh morim leanglit bebayt?",
  "imot beulpan o bebayt?",
  "atem lomdim rusit umuzika?",
  "aten veanachnu ovdim, veatem?",
  "ani talmid?",
  "aba ba mibayt lesham o lekan?",
  "abim lomdim rusit im imot, veata?",
  "aba ba misham lepo, veatem?",
  "hen vehem baim misham, vehu?",
  "ani gam mora, vehen?",
  "mora leanglit ovedet im ima?",
  "hem veaten baim mikan o meulpan?",
  "morim leivrit ovdim?",
  "anachnu baot mikan lesham, veat?",
  "ata lomed anglit im ima?",
  "more oved im imot?",
  "more ba lesham mikan, veata?",
  "morot lemuzika ovdot, veata?",
  "mora lerusit baa lekan, veata?",
  "atem lomdim, vehu?",
  "ima gara beakademja o bebayt?",
  "eyn abim birchov?",
  "aten bebayt o beulpan?",
  "morim baim lekan, veatem?",
  "talmidot umorot baot lepo, veatem?",
  "ma ima lomedet beulpan im hen?",
  "morot veabim baim mipo, vehi?",
  "lean imot veabim baim?",
  "hi baa lepo, veata?",
  "lean aba ba mibayt?",
  "hem gam abim, vehi?",
  "more lerusit lomed ivrit, veat?",
  "aten vehem lomdim anglit?",
  "atem baim lesham, vehu?",
  "hem abim, veatem?",
  "mora leivrit baa lesham mikan?",
  "morim lomdim ivrit, vehu?",
  "eyn morot birchov Sverdlov?",
  "aba ba leuniversita o leulpan?",
  "atem baim mikan, vehi?",
  "atem baim lepo o lesham?",
  "anachnu lomdot muzika, vehu?",
  "anachnu ovdot im abim, veata?",
  "imot baot leulpan mibayt o mipo?",
  "ata lomed anglit verusit, veatem?",
  "imot baot lesham mikan, vehem?",
  "meayn hem baim leulpan?",
  "eyfo abim ovdim?",
  "hu oved im ima?",
  "morot veimot baot lepo, veata?",
  "ima ovedet, vehi?",
  "morim baim lepo o leuniversita?",
  "hen veatem ovdim, veata?",
  "abim lomdim ivrit im aba, vehu?",
  "mi ba lepo?",
  "ata ba mikan o meulpan?",
  "at talmida, vehem?",
  "morim lerusit ovdim im aba, veat?",
  "anachnu gam imot, vehi?",
  "ma talmida lomedet im anachnu?",
  "meayn aten baot?",
  "aten baot lesham mipo, vehu?",
  "mi lomed ivrit veanglit bebayt?",
  "hu ba lesham, veaten?",
  "morim umorot baim mipo, veatem?",
  "eyfo atem lomdim ivrit veanglit?",
  "anachnu baim lirchov o lepo?",
  "abim veimot baim habayta o lepo?",
  "hen veatem lomdim rusit, veat?",
  "ima baa lirchov mibayt o mipo?",
  "hi achshav baa lesham, veaten?",
  "talmida baa mipo o misham?",
  "hem lomdim ivrit, vehu?",
  "hem veatem ovdim im aba?",
  "morim vetalmidot ovdim, vehu?",
  "hem vehen baim misham, veat?",
  "hem baim mikan o misham?",
  "aten vehen ovdot im aba, veata?",
  "mi ba mipo leuniversita?",
  "talmid ba habayta mipo, vehi?",
  "ima baa habayta, vehi?",
  "morot baot mipo o merechov?",
  "abim umorot lomdim, veatem?",
  "hen baot meulpan o mikan?",
  "anachnu gam talmidot, veaten?",
  "aten talmidot, vehen?",
  "hu ba mipo lesham o habayta?",
  "imot umorim baim lepo, veaten?",
  "morot leanglit lomdot, veaten?",
  "aten baot lesham mikan, vehi?",
  "talmidot bebayt o beakademja?",
  "ata more o talmid?",
  "more lerusit ba lekan misham?",
  "ma more leanglit lomed im at?",
  "ima achshav baa mipo, vehen?",
  "hi achshav baa lepo?",
  "morim lerusit lomdim anglit?",
  "hi lo mora, veatem?",
  "aten baot mikan habayta, vehi?",
  "ani baa lepo, vehu?",
  "aten morot leivrit?",
  "ma talmidim lomdim im talmida?",
  "abim umorot leanglit baim misham?",
  "hem baim mipo, vehen?",
  "imot baot habayta mipo?",
  "ani mora leivrit o ima?",
  "anachnu lo imot, vehem?",
  "mora baa misham o mikan?",
  "lean at baa mibayt?",
  "morot leivrit ovdot, veatem?",
  "lean ani ba mibayt?",
  "hen baot lepo, vehem?",
  "morim vetalmidim baim mipo?",
  "ata ba lekan misham, vehen?",
  "talmid ba lesham?",
  "hen veaten ovdot im abim, vehu?",
  "ima baa misham lepo, vehu?",
  "morim lomdim rusit im aba?",
  "ata lomed rusit im abim, vehi?",
  "more ba merechov lesham o lekan?",
  "atem achshav baim lesham, vehen?",
  "at ima o mora leanglit?",
  "morot baot mikan o misham?",
  "aten lomdot anglit im ima?",
  "hu ba lesham mibayt o mikan?",
  "at lo ima, vehem?",
  "talmid lomed ivrit, veata?",
  "aten veatem ovdim, vehem?",
  "hi mora leivrit, vehem?",
  "morim veabim baim lekan, veat?",
  "ani gam talmida, veata?",
  "hi ovedet beuniversita o beulpan?",
  "mora lemuzika baa lekan, veat?",
  "more ba lepo misham, vehem?",
  "mi morim leivrit?",
  "more ba misham, vehi?",
  "eyfo abim lomdim rusit?",
  "more lemuzika ba lepo, veata?",
  "hi lomedet rusit umuzika?",
  "hen baot lepo misham, veatem?",
  "anachnu morim?",
  "ani achshav baa lepo?",
  "ma morim lomdim bebayt im aten?",
  "ata ba lesham, vehi?",
  "anachnu lo morim lemuzika?",
  "talmidim baim lekan, veata?",
  "anachnu gam morim leanglit?",
  "atem lo morim, vehen?",
  "imot umorot baot habayta mikan?",
  "aten vehem baim habayta?",
  "ata lomed rusit im abim?",
  "hem baim mibayt o mipo?",
  "hi ima, veat?",
  "hu gam aba, vehen?",
  "ani ima, veaten?",
  "atem baim mipo, veat?",
  "aba ba misham habayta o lirchov?",
  "imot vetalmidim baim lekan, veat?",
  "aten lomdot muzika, veat?",
  "hem lomdim, veatem?",
  "eyfo hem ovdim?",
  "morim baim lepo, vehem?",
  "talmidot baot habayta o lepo?",
  "more lerusit ba mikan, vehem?",
  "aten veanachnu baim mipo, vehen?",
  "ani ba misham lekan, veat?",
  "hem abim o morim leanglit?",
  "meayn abim baim?",
  "hen morot lemuzika, vehem?",
  "ani lo aba, veatem?",
  "ani more, vehu?",
  "eyfo ani lomedet muzika veivrit?",
  "eyn talmidot birchov Sverdlov?",
  "hu aba, veatem?",
  "ma talmidot lomdot im hen?",
  "hi baa misham, vehen?",
  "atem beulpan o beuniversita?",
  "hu ba lesham mibayt o merechov?",
  "ima baa habayta mikan, vehu?",
  "ata ba mikan lesham?",
  "hi lomedet, veaten?",
  "meayn aba ba lekan?",
  "ma morot lomdot im talmid?",
  "aten veanachnu baim lepo, veat?",
  "ma talmida lomedet beakademja?",
  "hu lo more leivrit, vehem?",
  "hem lomdim anglit?",
  "mora baa habayta mikan, vehu?",
  "imot veabim ovdim im aba, vehen?",
  "ani baa misham lekan?",
  "aba ba merechov o mipo?",
  "ma talmid lomed beakademja im hu?",
  "hem baim habayta, vehen?",
  "anachnu lomdot muzika, vehem?",
  "ima baa mikan, veat?",
  "atem baim mikan habayta, vehen?",
  "morot baot lekan?",
  "anachnu baim mipo, vehi?",
  "aten lomdot ivrit im ima?",
  "ani baa lesham, vehen?",
  "meayn ata ba leakademja leivrit?",
  "ima baa lepo meulpan o mibayt?",
  "atem baim habayta o leulpan?",
  "hu oved im imot, vehem?",
  "morim veabim baim habayta, vehi?",
  "eyfo hen veaten lomdot rusit?",
  "ma more lomed im hem vehen?",
  "ata lo talmid, vehi?",
  "morim veabim baim mikan, veaten?",
  "lean hu ba meakademja leanglit?",
  "lean imot baot mibayt?",
  "morim umorot baim misham, vehi?",
  "abim ovdim im ima, veata?",
  "hen lo imot, veat?",
  "mora baa lesham mipo, veata?",
  "eyn aba beulpan?",
  "talmid ba mikan, veata?",
  "hem vehen baim mipo, vehu?",
  "talmidim lomdim, vehem?",
  "aba lomed, vehi?",
  "aba oved im abim?",
  "more lomed anglit im abim?",
  "ma ima lomedet birchov im morim?",
  "talmida lomedet ivrit, vehi?",
  "ma imot lomdot birchov im hen?",
  "hi baa misham lepo, vehen?",
  "ima baa lekan, veaten?",
  "hu lomed ivrit im ima, vehem?",
  "ani lomed, veat?",
  "ani lomed anglit, veaten?",
  "lean anachnu baim meulpan?",
  "aten veanachnu ovdot, vehi?",
  "ma talmidim lomdim im aba?",
  "anachnu lo abim?",
  "aten vehem ovdim im aba, veat?",
  "hu ba mibayt habayta o lesham?",
  "hen vehem baim lesham, veatem?",
  "ata talmid, veaten?",
  "talmida baa habayta o lepo?",
  "aba ba misham, veatem?",
  "ima baa merechov lepo o lesham?",
  "at baa lesham o lekan?",
  "eyfo hen morim leanglit?",
  "hu ba lepo, veat?",
  "more ba merechov habayta o lepo?",
  "hi baa lekan, veata?",
  "eyn talmida bebayt?",
  "ata more lemuzika?",
  "hem gam morim, veat?",
  "meayn hi baa?",
  "ani baa mibayt o mipo?",
  "hem baim mipo, vehi?",
  "atem lo morim lemuzika, veat?",
  "hen veaten achshav baot lekan?",
  "talmid ba habayta mikan?",
  "ma imot lomdot im hi?",
  "morot leivrit baot lesham, vehi?",
  "abim ovdim, veat?",
  "hem veanachnu baim lekan?",
  "ata lomed anglit, vehem?",
  "abim baim mipo, veata?",
  "ani lo ima, veaten?",
  "aba ba habayta o lekan?",
  "talmid lomed rusit, veata?",
  "hu ba leulpan mipo o mibayt?",
  "aten ovdot im imot, veatem?",
  "imot baot mipo lesham, vehen?",
  "abim umorot baim lepo misham?",
  "hem veatem ovdim im ima?",
  "aten ovdot, vehi?",
  "imot umorim lomdim, veat?",
  "anachnu lomdot anglit?",
  "hem lo morim lerusit, vehi?",
  "imot baot lekan o habayta?",
  "hem baim habayta mikan, vehen?",
  "meayn ani ba?",
  "eyn akademja leivrit birchov?",
  "mora baa habayta mikan, veaten?",
  "abim achshav baim habayta?",
  "morot leivrit baot mipo, vehu?",
  "morot lerusit lomdot?",
  "anachnu lomdim anglit im ima?",
  "hi ovedet im imot, vehu?",
  "ata ba mikan?",
  "talmida baa misham habayta?",
  "imot ovdot beulpan o beakademja?",
  "meayn abim veimot baim lepo?",
  "mora lomedet ivrit, veaten?",
  "hi gam mora vegam ima, vehu?",
  "atem beakademja o beulpan?",
  "hu more leivrit o aba?",
  "ani ba lesham mikan, veat?",
  "hu more, vehen?",
  "hi baa leuniversita o lekan?",
  "hi lo mora leivrit?",
  "hu ba leulpan o lepo?",
  "hen baot lekan, veat?",
  "more ba habayta misham, vehen?",
  "ma talmid lomed im abim?",
  "at baa mikan lesham, vehi?",
  "eyfo hen morim?",
  "morim veimot baim habayta, vehen?",
  "hem lomdim ivrit, veaten?",
  "at baa lesham mikan, vehu?",
  "anachnu talmidim, vehu?",
  "ma talmidot lomdot birchov im at?",
  "abim umorot lomdim, veata?",
  "atem vehem ovdim, vehen?",
  "ma morot lomdot im abim?",
  "morot baot habayta mipo, veaten?",
  "hu gam talmid, veat?",
  "ani lomedet ivrit?",
  "hu more lerusit?",
  "mi ba merechov lesham?",
  "morot leivrit baot lepo?",
  "more lemuzika ba mikan?",
  "at baa habayta mipo, veatem?",
  "hen vehem baim misham?",
  "meayn talmidot baot lepo?",
  "at lo ima, veatem?",
  "aba ba mibayt o mikan?",
  "more ba misham?",
  "mora baa lirchov meulpan o mipo?",
  "talmid lomed rusit im aba, veata?",
  "aten morot leivrit, vehen?",
  "talmidim veabim lomdim, vehen?",
  "hu oved, vehen?",
  "aten achshav baot mikan lesham?",
  "ani ima, veat?",
  "hi achshav baa habayta mipo?",
  "hi baa misham?",
  "mi baa mipo leulpan?",
  "mora ovedet im imot, veata?",
  "ani talmid o more lerusit?",
  "hem baim misham, vehu?",
  "imot lomdot anglit verusit, veat?",
  "more achshav ba misham habayta?",
  "ani lomed ivrit im abim, veatem?",
  "more lemuzika oved, vehi?",
  "meayn aten baot lepo?",
  "at baa habayta, vehi?",
  "at baa mipo habayta, veatem?",
  "mi lomed bebayt?",
  "morim lerusit baim lesham, vehu?",
  "hem vehen beakademja o bebayt?",
  "anachnu vehen ovdim im abim?",
  "hen baot habayta, veatem?",
  "anachnu lo morim lerusit?",
  "aten lo talmidot, veata?",
  "mora lomedet ivrit im aba, vehi?",
  "mi baa lesham mipo?",
  "ani lomed muzika im imot, veat?",
  "imot baot mibayt o mipo?",
  "morim veabim baim mipo, vehu?",
];