// The questions here are pre-generated.
// See the Python script generate_data.py for details.
let questions = [
  "hem veanachnu lomdim anglit im ata?",
  "eyfo hu more lerusit?",
  "lean hu ba misham?",
  "mi lomedet anglit im talmidim bebayt?",
  "mi oved im hu beuniversita?",
  "anachnu lomdot muzika?",
  "mi oved im ani bebayt?",
  "ma morot lerusit lomdot?",
  "lean talmidim baim mibayt?",
  "lean mora lerusit baa mipo?",
  "anachnu abim o morim lerusit?",
  "ma abim lomdim birchov Komsomolskaja?",
  "eyn akademja lerusit birchov Sverdlov?",
  "talmidot veimot lomdot?",
  "ma mora lomedet bebayt im hu?",
  "eyfo ani lomedet?",
  "lean talmidot umorot lerusit baot?",
  "ma talmid lomed bebayt im morot?",
  "mi lomedet birchov Komsomolskaja?",
  "ma mora lomedet?",
  "ma talmid lomed?",
  "mora leanglit baa merechov o misham?",
  "mi oved birchov?",
  "meayn aten veanachnu baot?",
  "hen baot mipo habayta o leulpan?",
  "mi morot?",
  "ma talmidim lomdim im hi?",
  "at baa leakademja leivrit o habayta?",
  "eyfo aten morot lerusit?",
  "hi lomedet ivrit im aba, vehen?",
  "eyfo more lemuzika oved im ani?",
  "lean imot veabim baim?",
  "meayn aba ba?",
  "mi oved im ani birchov?",
  "morot leanglit veabim lomdim, vehen?",
  "eyfo ani more lerusit?",
  "eyfo at ovedet im atem vehen?",
  "ma talmidim lomdim birchov im more lerusit?",
  "aba lomed muzika, vehem?",
  "lean ata ba mikan?",
  "hen veanachnu achshav baot leuniversita?",
  "lean ima baa merechov Sverdlov?",
  "lean morot lemuzika baot merechov Komsomolskaja?",
  "eyfo morim vetalmidim garim?",
  "hu lomed, vehem?",
  "hen talmidot o imot?",
  "ima baa habayta merechov Komsomolskaja o mikan?",
  "ma more leanglit lomed bebayt?",
  "lean aten veanachnu baim merechov Sverdlov?",
  "imot ovdot im anachnu, vehi?",
  "ma morim lomdim beuniversita?",
  "ma imot lomdot im talmida?",
  "yesh talmida birchov Sverdlov?",
  "ma morot lomdot birchov?",
  "more beakademja lemuzika o bebayt?",
  "ma mora lomedet beulpan?",
  "lean ata ba?",
  "hu gam aba, vehen?",
  "ma morim leivrit lomdim im hem veaten?",
  "ma morim lerusit lomdim?",
  "anachnu vehen lomdot?",
  "meayn talmida baa habayta?",
  "hu gar beulpan o bebayt?",
  "talmidim lomdim anglit im talmida?",
  "ma imot lomdot beulpan im hu?",
  "ma abim lomdim birchov im morot?",
  "mi imot?",
  "yesh talmida birchov Komsomolskaja?",
  "meayn ima baa?",
  "lean more leanglit ba meuniversita?",
  "ma abim lomdim beulpan im talmid?",
  "at ima o mora?",
  "ma morim lemuzika lomdim birchov im more?",
  "yesh ima beulpan?",
  "ma more lomed?",
  "morim umorot leanglit baim misham habayta o lirchov?",
  "ma morot lomdot bebayt im more lerusit?",
  "meayn atem vehem baim habayta?",
  "lean ata ba merechov Sverdlov?",
  "hi talmida o ima?",
  "hu gam talmid, veatem?",
  "ma imot lomdot bebayt im hu?",
  "ani lomed muzika verusit im hen, vehu?",
  "ata more lemuzika o talmid?",
  "eyn ulpan birchov?",
  "eyfo talmida lomedet rusit veanglit?",
  "eyfo ani talmid?",
  "mi lomedet ivrit verusit im hi birchov Sverdlov?",
  "ma more leanglit lomed im ani?",
  "meayn ani ba lepo?",
  "eyn talmidim beuniversita?",
  "mi ovedet im more leanglit birchov Sverdlov?",
  "imot ovdot, vehi?",
  "talmida lomedet rusit veanglit im hi?",
  "lean morot vetalmidim baim mikan?",
  "ma more leanglit lomed bebayt im at?",
  "talmid oved im morim leanglit, veata?",
  "anachnu abim o talmidim?",
  "meayn ata ba?",
  "imot baot leakademja mipo o merechov?",
  "morot leivrit beakademja leanglit o beulpan?",
  "anachnu ovdot im abim bebayt o beulpan?",
  "lean talmidim baim mikan?",
  "mi ovedet birchov Komsomolskaja?",
  "mi ba meuniversita leulpan?",
  "ma mora lerusit lomedet im aten veanachnu?",
  "meayn abim veimot baim?",
  "eyfo ata gar?",
  "talmida baa misham o merechov Sverdlov?",
  "anachnu lo talmidot?",
  "eyfo aba lomed muzika veivrit im hen veaten?",
  "ma mora lomedet im talmida?",
  "hen morot lemuzika?",
  "eyfo hu more leivrit?",
  "hu gar beakademja leivrit o bebayt?",
  "eyfo ata more lemuzika?",
  "ani aba o talmid?",
  "ma morim leanglit lomdim im ani?",
  "ata gar beuniversita o bebayt?",
  "ma talmid lomed bebayt im ima?",
  "abim achshav ovdim gam birchov?",
  "talmidot baot lesham o lekan?",
  "lean mora baa merechov?",
  "mi baa habayta merechov?",
  "lean mora lerusit baa merechov?",
  "anachnu ovdot im talmid?",
  "aba ba mibayt o meakademja lerusit?",
  "eyfo anachnu morot lerusit?",
  "ani mora o ima?",
  "ani lomedet, veata?",
  "anachnu vehen ovdot im ani?",
  "aten morot lerusit o imot?",
  "ma imot lomdot im hi?",
  "talmidot baot habayta?",
  "ma aba lomed im morot leivrit?",
  "ma aba lomed im talmidot?",
  "lean imot baot mipo?",
  "ma mora lemuzika lomedet im hi?",
  "eyfo atem talmidim?",
  "imot umorim baim mipo o merechov Sverdlov?",
  "mi lomedet ivrit verusit bebayt?",
  "lean talmidot vetalmidim baim misham?",
  "hi talmida o mora?",
  "mora baa lesham o habayta?",
  "talmidim umorim baim meuniversita o mibayt?",
  "anachnu vehem baim leakademja misham o merechov?",
  "talmidim baim lekan meuniversita o merechov?",
  "anachnu talmidot o morot?",
  "ma ima lomedet bebayt im hen veaten?",
  "ima baa merechov o mipo?",
  "ma talmid lomed im ima?",
  "anachnu baim merechov o mipo?",
  "ma talmid lomed beuniversita im aten vehen?",
  "mi lomedet anglit im morim veabim bebayt?",
  "mi ovedet im aba bebayt?",
  "hi gam ima?",
  "anachnu talmidot o imot?",
  "ma talmid lomed im talmida?",
  "talmidot achshav garot bebayt?",
  "hen imot o talmidot?",
  "lean imot vetalmidot baot mibayt?",
  "ma aba lomed im talmid?",
  "lean hu ba merechov Komsomolskaja?",
  "yesh ima birchov Sverdlov?",
  "meayn mora lerusit baa lekan?",
  "eyfo aten morot?",
  "meayn hu ba leulpan?",
  "ma abim lomdim im ani?",
  "meayn anachnu vehen baot leakademja?",
  "eyfo ani more?",
  "ma talmidim lomdim im morim?",
  "lean ata ba merechov?",
  "ma more leivrit lomed birchov Sverdlov im talmid?",
  "lean anachnu baim?",
  "eyn akademja lerusit birchov?",
  "ma talmidim lomdim im talmida?",
  "ma morim leivrit lomdim birchov im hen?",
  "mi baa habayta?",
  "ma imot lomdot bebayt im mora?",
  "ani ba merechov Komsomolskaja habayta o lekan?",
  "mi ba merechov Sverdlov habayta?",
  "hi lomedet, veaten?",
  "ima achshav baa mibayt, vehu?",
  "meayn morim leanglit vetalmidot baim?",
  "meayn hi baa leuniversita?",
  "ma talmida lomedet bebayt im talmidim umorim leivrit?",
  "ma abim lomdim im hu?",
  "talmidot lomdot?",
  "lean hem baim mibayt?",
  "lean anachnu baot meakademja lerusit?",
  "mi lomed anglit im ata birchov?",
  "anachnu morim lerusit o abim?",
  "meayn hem baim?",
  "imot achshav lomdot gam bebayt vegam beakademja lemuzika, veat?",
  "lean aten veanachnu baot merechov?",
  "ma morot lomdot im talmidot?",
  "lean more ba mibayt?",
  "mi lomedet muzika im aten bebayt?",
  "lean mora baa misham?",
  "eyfo talmid oved?",
  "ani lomedet muzika gam beulpan vegam beakademja leanglit?",
  "eyfo talmidim vetalmidot lomdim ivrit?",
  "lean imot baot meulpan?",
  "eyfo anachnu morim?",
  "eyfo ani mora lerusit?",
  "ma talmidim lomdim bebayt im mora leivrit?",
  "mi ba meuniversita?",
  "eyfo morim lerusit ovdim im ani?",
  "ma talmida lomedet im anachnu vehen?",
  "anachnu baim habayta mikan o merechov Komsomolskaja?",
  "meayn ima baa lirchov Komsomolskaja?",
  "ani gam aba vegam talmid, vehen?",
  "ma abim lomdim beuniversita im hem?",
  "more lemuzika achshav ba mipo lirchov Komsomolskaja, vehen?",
  "ani ovedet im mora lemuzika, vehi?",
  "talmid ba lirchov Sverdlov o lesham?",
  "aten vehen achshav garot bebayt, veatem?",
  "aba lomed gam muzika vegam rusit im talmid, vehi?",
  "hem talmidim o morim?",
  "eyn aba bebayt?",
  "mi baa mibayt?",
  "ma talmid lomed im at?",
  "mi more lerusit?",
  "yesh akademja lerusit birchov Sverdlov?",
  "eyn talmida beulpan?",
  "ani more o talmid?",
  "mi oved im anachnu birchov?",
  "mora lemuzika ovedet?",
  "mi baa lesham merechov Komsomolskaja?",
  "eyfo atem morim lerusit?",
  "yesh talmida birchov?",
  "ma ima lomedet birchov Komsomolskaja?",
  "lean ani baa merechov Komsomolskaja?",
  "lean anachnu baim mibayt?",
  "ma talmid lomed beulpan im talmida?",
  "ani gam ima, vehem?",
  "hu lomed?",
  "at ovedet bebayt o beakademja leanglit?",
  "ma morot lemuzika lomdot?",
  "ma aba lomed birchov im talmidot?",
  "atem veaten lomdim muzika, veata?",
  "meayn ima baa habayta?",
  "abim lomdim ivrit?",
  "lean mora baa mikan?",
  "mi oved im hi birchov Sverdlov?",
  "meayn talmidim umorot lerusit baim?",
  "morot lemuzika baot merechov habayta o leuniversita?",
  "lean morot leanglit baot merechov?",
  "ma aba lomed beakademja lerusit?",
  "eyfo imot veabim ovdim?",
  "ata achshav ba misham habayta?",
  "mi lomedet rusit veanglit birchov?",
  "mi morim leanglit?",
  "meayn anachnu vehem baim?",
  "ma morot lomdot im mora?",
  "eyfo anachnu lomdim ivrit verusit im hi?",
  "mi baa leuniversita?",
  "ma mora leivrit lomedet im talmid?",
  "meayn abim veimot baim leakademja lerusit?",
  "aten veanachnu achshav baot merechov Komsomolskaja lekan?",
  "lean morim baim mikan?",
  "lean hi baa mibayt?",
  "ma talmida lomedet birchov Sverdlov?",
  "anachnu abim o morim lemuzika?",
  "ani ba mipo o merechov?",
  "hi mora leivrit o ima?",
  "mi gar birchov?",
  "ma ima lomedet birchov im talmidim?",
  "lean mora lemuzika baa merechov?",
  "ani talmida o mora?",
  "ma talmid lomed birchov im hu?",
  "hem morim o abim?",
  "ma mora lemuzika lomedet?",
  "ma more leanglit lomed bebayt im talmidim veimot?",
  "meayn morot lemuzika baot habayta?",
  "mi gar beulpan?",
  "lean anachnu baim mikan?",
  "mi gara bebayt?",
  "mi morot lerusit?",
  "eyfo imot vetalmidim garim?",
  "eyn akademja lemuzika birchov Komsomolskaja?",
  "ma imot lomdot beuniversita im anachnu?",
  "mi oved im at beuniversita?",
  "eyfo atem morim?",
  "ma imot lomdot beakademja?",
  "anachnu gam talmidim, veatem?",
  "ima baa merechov Komsomolskaja leuniversita?",
  "ma morim lerusit lomdim birchov Komsomolskaja?",
  "aba ba misham o mipo?",
  "abim vetalmidot ovdim im ani, veat?",
  "talmidot bebayt o beulpan?",
  "meayn aba ba lirchov?",
  "eyfo ani mora leivrit?",
  "yesh talmidim bebayt?",
  "lean ima baa mipo?",
  "ma talmida lomedet im talmid?",
  "at ovedet birchov?",
  "ma talmid lomed birchov Sverdlov?",
  "mi mora?",
  "ani talmida o ima?",
  "ima baa lepo merechov Sverdlov, veaten?",
  "at ovedet im imot vetalmidot, veata?",
  "eyfo hem lomdim?",
  "yesh ima bebayt?",
  "meayn anachnu vehen baot lekan?",
  "eyn abim bebayt?",
  "meayn morim leanglit baim?",
  "talmidim achshav baim habayta, veatem?",
  "meayn mora baa habayta?",
  "mi ovedet im talmidim veimot birchov Komsomolskaja?",
  "mi ovedet im at birchov Komsomolskaja?",
  "lean morot leivrit baot?",
  "lean talmidot umorot lemuzika baot?",
  "ma talmida lomedet im ima?",
  "lean imot umorot baot?",
  "mi ima?",
  "ma morim leanglit lomdim?",
  "meayn imot vetalmidot baot habayta?",
  "eyfo hen morot lerusit?",
  "mi baa merechov?",
  "eyfo ani gara?",
  "abim umorot ovdim im ima?",
  "meayn talmida baa leuniversita?",
  "lean hu ba mibayt?",
  "ani ima o mora lerusit?",
  "lean talmida baa misham?",
  "lean ani baa?",
  "mi lomedet gam rusit vegam anglit im at birchov Komsomolskaja?",
  "meayn ima baa leuniversita?",
  "eyfo ani more leanglit?",
  "mi oved im talmid bebayt?",
  "talmid ba meuniversita o misham?",
  "lean morot lemuzika baot meulpan?",
  "atem gam morim, vehem?",
  "lean imot baot merechov Sverdlov?",
  "ma abim lomdim bebayt im hi?",
  "at achshav ovedet gam bebayt vegam beulpan, vehen?",
  "ma ima lomedet im more?",
  "anachnu imot, veaten?",
  "yesh akademja leanglit birchov?",
  "aten lo morot, vehu?",
  "lean morot lerusit veimot baot?",
  "mi gar bebayt?",
  "meayn hen veanachnu baim habayta?",
  "ani talmida, veaten?",
  "ani aba o more lemuzika?",
  "aten lomdot muzika im hen veanachnu, veata?",
  "anachnu baim lirchov Sverdlov o lekan?",
  "meayn hen baot leulpan?",
  "talmid achshav ba meulpan habayta?",
  "eyfo ima lomedet gam muzika vegam ivrit im talmida?",
  "ma abim lomdim im more leivrit?",
  "lean imot vetalmidim baim?",
  "lean aten baot meulpan?",
  "eyfo anachnu morot?",
  "eyn more bebayt?",
  "atem vehem ovdim im anachnu?",
  "lean morim lerusit veimot baim?",
  "yesh talmid birchov Sverdlov?",
  "ma more lemuzika lomed im ani?",
  "lean ani ba?",
  "lean anachnu veaten baot misham?",
  "yesh mora beakademja leanglit?",
  "morot baot misham, veatem?",
  "meayn anachnu baim leulpan?",
  "ma mora lomedet im ani?",
  "mi lomed birchov?",
  "lean aten veanachnu baim mikan?",
  "lean talmidot baot misham?",
  "hen gam imot?",
  "mi baa lesham mikan?",
  "mi baa merechov Komsomolskaja?",
  "anachnu veatem ovdim im abim?",
  "hi mora lemuzika o ima?",
  "ma talmida lomedet birchov?",
  "at ima, vehi?",
  "ma morim lomdim im morot lerusit?",
  "eyn talmidot beulpan?",
  "hen morot leanglit o talmidot?",
  "ma talmida lomedet im anachnu veaten?",
  "ata gam more vegam talmid?",
  "eyfo anachnu lomdot ivrit im hu?",
  "ma imot lomdot beuniversita im ani?",
  "lean talmidot umorot baot meulpan?",
  "mi ba leakademja leanglit merechov?",
  "lean hen baot mibayt?",
  "lean abim umorim lerusit baim merechov?",
  "eyn abim beulpan?",
  "meayn aba ba lesham?",
  "aba achshav ba meulpan, vehen?",
  "ima baa habayta o lesham?",
  "meayn aten veanachnu baot habayta?",
  "meayn hen veanachnu baot?",
  "anachnu morot o talmidot?",
  "ma talmidot lomdot birchov?",
  "meayn talmidot umorim lemuzika baim lirchov Komsomolskaja?",
  "imot lomdot?",
  "lean hen veanachnu baim?",
  "ma morim leivrit lomdim im anachnu?",
  "mi ba merechov Komsomolskaja leakademja?",
  "meayn ani baa leulpan?",
  "abim lomdim?",
  "hu achshav ba habayta mikan?",
  "mi ovedet im more birchov Sverdlov?",
  "eyfo morim lerusit garim?",
  "ma talmidot lomdot bebayt im imot?",
  "mi baa meuniversita lirchov?",
  "ima ovedet im atem vehen?",
  "yesh universita birchov?",
  "ma abim lomdim beulpan im ani?",
  "ma more lomed birchov Sverdlov?",
  "yesh universita birchov Sverdlov?",
  "lean atem veanachnu baim?",
  "talmidot achshav baot mibayt, veaten?",
  "anachnu baim habayta misham o merechov Sverdlov?",
  "mora leivrit baa lepo merechov Komsomolskaja, vehu?",
  "mi ba misham habayta?",
  "eyfo hen morot?",
  "yesh akademja leivrit birchov Sverdlov?",
  "meayn atem veaten baim?",
  "ani lo ima?",
  "eyn talmid beakademja?",
  "meayn imot baot?",
  "lean anachnu veaten baim?",
  "lean talmidot baot mibayt?",
  "aba achshav ba habayta?",
  "ma mora lemuzika lomedet beulpan?",
  "meayn aten vehem baim?",
  "lean anachnu baot misham?",
  "lean aten veanachnu baot meulpan?",
  "lean morim leanglit baim misham?",
  "eyfo hen morot leanglit?",
  "morot lerusit veimot ovdot im ani?",
  "mi baa merechov Sverdlov?",
  "meayn ima baa leulpan?",
  "lean mora baa mibayt?",
  "hu more leanglit o aba?",
  "lean anachnu baim merechov Sverdlov?",
  "lean ima baa mikan?",
  "anachnu baim leuniversita o leakademja?",
  "lean more leanglit ba mibayt?",
  "morot vetalmidot baot habayta o lekan?",
  "ani lomed gam muzika vegam ivrit im talmid?",
  "lean morim baim mipo?",
  "hi ima o mora?",
  "anachnu gam morot leivrit vegam imot, vehen?",
  "ani talmid o more?",
  "meayn anachnu vehen baot?",
  "anachnu abim?",
  "eyfo aba oved im aten vehen?",
  "talmidim ovdim im ani?",
  "meayn hu ba lirchov Sverdlov?",
  "ma talmidot lomdot birchov Sverdlov im atem?",
  "eyfo hu lomed anglit veivrit?",
  "anachnu imot?",
  "meayn mora lerusit baa?",
  "ma morim lomdim bebayt im aba?",
  "ma talmid lomed im imot vetalmidot?",
  "lean abim veimot baim?",
  "aten veatem baim leuniversita mikan?",
  "aba lomed ivrit im hi, veat?",
  "ma talmid lomed im hi?",
  "eyfo talmida lomedet gam muzika vegam rusit?",
  "mi gara beakademja lerusit?",
  "mi lomedet beuniversita?",
  "eyn talmidim birchov Komsomolskaja?",
  "atem morim o talmidim?",
  "eyfo hi lomedet anglit im morim?",
  "mi lomedet anglit im talmid birchov Komsomolskaja?",
  "aba lomed muzika, veata?",
  "lean morot veimot baot merechov?",
  "lean abim vetalmidot baim meakademja leanglit?",
  "mora ovedet?",
  "hi talmida?",
  "ani lomedet, vehen?",
  "lean abim baim?",
  "ma morot lomdot beakademja im aba?",
  "ani lo aba?",
  "meayn morot lemuzika baot leuniversita?",
  "ma mora leanglit lomedet beulpan im aba?",
  "lean aten vehem baim mipo?",
  "eyfo ata oved im ima?",
  "meayn abim vetalmidot baim?",
  "anachnu lo talmidot, veatem?",
  "morim lomdim anglit veivrit im hen veanachnu?",
  "ma more leivrit lomed im talmidot umorot?",
  "ma morot lemuzika lomdot birchov Komsomolskaja?",
  "yesh ulpan birchov Sverdlov?",
  "lean talmidot umorot baot meakademja leanglit?",
  "hi ovedet?",
  "ma aba lomed beulpan?",
  "ani more leanglit?",
  "ani baa habayta misham o merechov?",
  "ani oved im mora lemuzika, veat?",
  "meayn morim baim?",
  "ma talmida lomedet beuniversita?",
  "talmidim ovdim, veat?",
  "imot baot merechov, veaten?",
  "anachnu talmidim o morim leivrit?",
  "eyfo hen morot leivrit?",
  "meayn ata ba lirchov Komsomolskaja?",
  "ma abim lomdim im anachnu?",
  "hem abim o talmidim?",
  "eyfo hu oved im anachnu?",
  "mi ba meulpan habayta?",
  "yesh ima birchov?",
  "meayn aten veanachnu baim habayta?",
  "lean talmidot baot merechov Sverdlov?",
  "meayn more lemuzika ba lirchov?",
  "ma mora leanglit lomedet beuniversita?",
  "imot vetalmidot baot merechov Komsomolskaja o mipo?",
  "ma morot leanglit lomdot im atem?",
  "mi ba habayta misham?",
  "hem ovdim?",
  "mi ba meakademja leanglit?",
  "meayn anachnu vehem baim lesham?",
  "meayn morim lemuzika vetalmidot baim?",
  "atem gam morim vegam talmidim, vehen?",
  "mi more lemuzika?",
  "mi ba merechov lekan?",
  "hi baa habayta mipo o merechov?",
  "ma abim lomdim bebayt?",
  "eyfo hi lomedet?",
  "ani oved im morim vetalmidim, veat?",
  "ani talmid o more lemuzika?",
  "mi lomedet anglit im anachnu birchov?",
  "at baa merechov Sverdlov?",
  "mi lomed anglit birchov?",
  "talmidim umorot ovdim im anachnu?",
  "lean abim veimot baim meulpan?",
  "talmidim lomdim anglit verusit im imot, vehi?",
  "anachnu veaten baot merechov Komsomolskaja o mikan?",
  "talmida lomedet, vehu?",
  "eyn imot birchov?",
  "mi lomed bebayt?",
  "lean talmida baa mipo?",
  "meayn hem baim lepo?",
  "anachnu bebayt o beulpan?",
  "aten ovdot?",
  "lean morim veabim baim misham?",
  "meayn mora leanglit baa?",
  "eyfo talmidot veimot garot?",
  "ma more leanglit lomed?",
  "mi lomed rusit im talmid birchov?",
  "anachnu gam imot, veata?",
  "lean ima baa?",
  "eyn universita birchov?",
  "anachnu gam morim vegam talmidim?",
  "talmidot baot lirchov Komsomolskaja o habayta?",
  "ma talmid lomed beakademja im anachnu veaten?",
  "ma talmidim lomdim birchov Sverdlov?",
  "anachnu baim merechov o meuniversita?",
  "imot vetalmidot lomdot rusit im ima?",
  "yesh akademja lerusit birchov?",
  "morot vetalmidot baot habayta meulpan o merechov Sverdlov?",
  "mi lomed anglit umuzika bebayt?",
  "ma ima lomedet birchov?",
  "mi talmid?",
  "ani talmid o aba?",
  "meayn talmidim baim leulpan?",
  "mi lomedet ivrit verusit birchov?",
  "ma abim lomdim im aba?",
  "lean talmid ba?",
  "at ima o talmida?",
  "more ba mipo, veat?",
  "mi ba lirchov Komsomolskaja?",
  "ma morot lomdot birchov Komsomolskaja?",
  "ani baa misham leulpan o leakademja?",
  "lean aba ba mipo?",
  "meayn talmidim baim lekan?",
  "anachnu talmidot o morot leivrit?",
  "mi oved bebayt?",
  "anachnu vehen baot merechov o mikan?",
  "more oved, vehem?",
  "at mora o ima?",
  "anachnu vehem baim merechov lepo o habayta?",
  "mi baa merechov Sverdlov lesham?",
  "lean talmidot baot?",
  "ma talmidot lomdot birchov Sverdlov im ani?",
  "hen lo imot?",
  "eyn universita birchov Sverdlov?",
  "yesh ulpan birchov?",
  "ani gam mora leivrit?",
  "ima bebayt o beakademja?",
  "ma talmid lomed birchov Komsomolskaja?",
  "talmid lomed ivrit im mora, vehi?",
  "mi ovedet im abim birchov?",
  "eyfo ani mora lemuzika?",
  "lean talmida baa meakademja?",
  "ma imot lomdot birchov Komsomolskaja im aten?",
  "mi baa mipo habayta?",
  "lean imot baot meakademja lemuzika?",
  "lean anachnu veaten baot?",
  "lean hu ba merechov?",
  "anachnu lomdot, vehi?",
  "ma ima lomedet im ani?",
  "lean aten veanachnu baot meuniversita?",
  "ma morim lomdim birchov Komsomolskaja?",
  "talmidot umorim lerusit lomdim, vehem?",
  "at baa lepo mibayt o misham?",
  "yesh mora lemuzika birchov Sverdlov?",
  "mi aba?",
  "mi morim lemuzika?",
  "meayn talmid ba lirchov Sverdlov?",
  "lean talmidim veabim baim?",
  "eyn talmida birchov?",
  "mi lomedet anglit im hu birchov?",
  "ani baa habayta misham, veata?",
  "meayn at baa habayta?",
  "ma mora lomedet im aba?",
  "hi ovedet im ani?",
  "talmida lomedet, veata?",
  "lean talmidim umorim leanglit baim?",
  "lean talmidim umorot baim?",
  "eyfo imot ovdot im ani?",
  "mi baa meuniversita?",
  "yesh morim bebayt?",
  "lean hen baot meulpan?",
  "lean talmida baa?",
  "ani oved im ata, vehen?",
  "lean talmida baa merechov?",
  "meayn mora baa lirchov Sverdlov?",
  "eyfo aten morot leanglit?",
  "lean talmidim vetalmidot baim meakademja?",
  "mi gara beuniversita?",
  "mora baa lekan o habayta?",
  "talmidim veimot achshav ovdim im more gam beakademja, vehi?",
  "eyfo hi gara?",
  "lean mora lerusit baa?",
  "anachnu gam abim?",
  "ata ba mibayt o mikan?",
  "more lerusit oved, vehi?",
  "ma morim lomdim im hu?",
  "at baa meuniversita o misham?",
  "eyfo at mora?",
  "ma morim lerusit lomdim im hen?",
  "anachnu lo talmidim, vehi?",
  "ma aba lomed birchov Sverdlov im anachnu?",
  "abim vetalmidim baim meuniversita o mikan?",
  "mi lomed birchov Komsomolskaja?",
  "anachnu lomdim?",
  "anachnu abim o morim?",
  "mi lomed anglit umuzika birchov Komsomolskaja?",
  "mi oved im talmida birchov?",
  "lean hu ba?",
  "eyn morot beuniversita?",
  "morot lomdot?",
  "ani more leivrit o aba?",
  "yesh talmidot bebayt?",
  "eyfo anachnu morim lemuzika?",
  "talmid ba habayta meakademja o merechov?",
  "lean anachnu baot meuniversita?",
  "lean hi baa meakademja lemuzika?",
  "at beulpan o bebayt?",
  "at gam mora leivrit, vehem?",
  "ma imot lomdot birchov im anachnu vehen?",
  "anachnu ovdot, veaten?",
  "lean talmida baa mikan?",
  "mi baa habayta meuniversita?",
  "eyn talmidot birchov?",
  "ma more lerusit lomed beulpan?",
  "ma mora lomedet beakademja lerusit im anachnu?",
  "ma morim lerusit lomdim im talmidot vetalmidim?",
  "ma ima lomedet im talmidim?",
  "talmidim umorot leanglit baim habayta mipo o meuniversita?",
  "lean ani baa merechov?",
  "hu achshav ba merechov Komsomolskaja?",
  "ma aba lomed birchov im hem veanachnu?",
  "hu oved im morot leanglit, vehi?",
  "ani lo ima, vehu?",
  "aten morot lerusit o talmidot?",
  "ma morim lomdim beuniversita im morot vetalmidot?",
  "yesh morot lerusit bebayt?",
  "eyfo hu lomed?",
  "mi ba lekan?",
  "aten gam morot leivrit vegam talmidot, vehu?",
  "lean ani baa mipo?",
  "ma aba lomed birchov Komsomolskaja im hu?",
  "meayn anachnu veaten baim habayta?",
  "imot umorot ovdot?",
  "eyfo ani lomed ivrit?",
  "ma aba lomed im mora lemuzika?",
  "ma talmidim lomdim?",
  "lean atem vehen baim mikan?",
  "ma imot lomdot birchov im anachnu?",
  "ani lomed birchov?",
  "meayn ata ba habayta?",
  "meayn ani ba habayta?",
  "ma morot leivrit lomdot birchov Sverdlov im imot veabim?",
  "mi baa leakademja meulpan?",
  "ani mora lemuzika o ima?",
  "eyfo hem talmidim?",
  "meayn aba ba lekan?",
  "mi baa misham?",
  "lean anachnu vehen baot meulpan?",
  "talmida beuniversita o bebayt?",
  "mora lemuzika baa merechov o meuniversita?",
  "meayn more ba habayta?",
  "mi ba habayta mipo?",
  "ma mora lomedet beuniversita?",
  "eyfo talmida ovedet?",
  "mi oved beakademja lemuzika?",
  "ma talmidim lomdim im at?",
  "lean abim vetalmidim baim?",
  "yesh morot beuniversita?",
  "at mora lerusit o talmida?",
  "anachnu baim mibayt o misham?",
  "talmidim lomdim rusit veivrit?",
  "meayn morot leanglit vetalmidim baim?",
  "eyn morim beakademja?",
  "mi lomedet rusit veivrit birchov?",
  "yesh akademja lemuzika birchov Sverdlov?",
  "mi ba habayta merechov?",
  "yesh aba birchov Sverdlov?",
  "eyfo talmid oved im ani?",
  "lean hi baa misham?",
  "lean abim umorim baim mibayt?",
  "meayn hu ba habayta?",
  "eyfo atem morim leanglit?",
  "hu oved?",
  "ma abim lomdim im atem?",
  "ani lo more?",
  "ma aba lomed im ani?",
  "eyfo aten talmidot?",
  "mi lomedet ivrit beuniversita?",
  "ma talmidot lomdot im ima?",
  "mi ba leakademja merechov?",
  "lean aba ba mibayt?",
  "mi oved im ata beuniversita?",
  "ma more lemuzika lomed birchov Komsomolskaja?",
  "lean hem vehen baim?",
  "mora ovedet im talmidim veimot?",
  "yesh akademja leivrit birchov Komsomolskaja?",
  "ma abim lomdim bebayt im at?",
  "anachnu lomdim beakademja leanglit, vehen?",
  "mi ovedet im ima bebayt?",
  "ma mora lomedet bebayt im more leivrit?",
  "ani baa mipo o merechov?",
  "ani ba habayta o leulpan?",
  "ma morot leanglit lomdot bebayt?",
  "talmida ovedet?",
  "talmid oved im ima?",
  "lean abim baim merechov Komsomolskaja?",
  "ma imot lomdot birchov im ani?",
  "lean anachnu vehen baim?",
  "lean talmidot baot meakademja?",
  "ma mora lomedet im morot?",
  "mi ba misham lirchov?",
  "anachnu abim, veatem?",
  "ma more lemuzika lomed beuniversita?",
  "talmid oved, veaten?",
  "lean talmidim baim meakademja leanglit?",
  "talmidot beulpan o beuniversita?",
  "lean morot baot?",
  "ma talmida lomedet birchov Komsomolskaja im more leivrit?",
  "mi ba meulpan?",
  "ma abim lomdim birchov Sverdlov?",
  "meayn morim baim lirchov Sverdlov?",
  "eyfo hi mora lerusit?",
  "aten ovdot im abim veimot?",
  "ma imot lomdot bebayt?",
  "lean at baa mikan?",
  "lean talmida baa mibayt?",
  "ma talmid lomed bebayt im aten?",
  "ma talmidot lomdot beuniversita?",
  "hu more o aba?",
  "aba lomed rusit im hu beakademja o bebayt?",
  "talmid achshav ba merechov Sverdlov habayta?",
  "eyn universita birchov Komsomolskaja?",
  "mi lomed ivrit im talmidim bebayt?",
  "ma talmida lomedet bebayt?",
  "lean talmida baa merechov Sverdlov?",
  "ma morim leivrit lomdim im morot?",
  "ma mora lomedet birchov?",
  "meayn atem baim lekan?",
  "ma more lomed im ani?",
  "lean at baa?",
  "mi talmida?",
  "ma more leivrit lomed beakademja lerusit?",
  "eyfo hi ovedet im mora?",
  "meayn mora leanglit baa lepo?",
  "eyfo aba oved?",
  "hi baa mibayt lirchov Komsomolskaja o lesham?",
  "mi lomed muzika im atem beulpan?",
  "yesh akademja lemuzika birchov?",
  "ma morim lerusit lomdim im anachnu?",
  "meayn hu ba leakademja?",
  "ma talmidim lomdim bebayt im anachnu vehem?",
  "lean morot vetalmidot baot?",
  "meayn talmidot vetalmidim baim lirchov Komsomolskaja?",
  "eyn mora lerusit birchov Sverdlov?",
  "ma talmidot lomdot im atem veanachnu?",
  "ma aba lomed im atem?",
  "hi talmida o mora lemuzika?",
  "talmidot veimot baot habayta o leulpan?",
  "eyfo hi mora leanglit?",
  "lean aba ba merechov?",
  "mi ovedet birchov?",
  "lean hen veatem baim merechov?",
  "lean anachnu vehen baot mibayt?",
  "mi lomedet gam muzika vegam rusit im anachnu beulpan?",
  "talmida achshav lomedet muzika im ani gam bebayt vegam beuniversita, vehen?",
  "ma ima lomedet im ata?",
  "meayn more leanglit ba habayta?",
  "anachnu lomdot?",
  "mi lomed ivrit birchov Sverdlov?",
  "lean hem veanachnu baim merechov?",
  "lean at baa mipo?",
  "meayn talmidot umorot lerusit baot habayta?",
  "ma more lemuzika lomed bebayt im hen vehem?",
  "ma talmida lomedet birchov im talmidot?",
  "eyfo hi mora leivrit?",
  "lean ani ba merechov?",
  "mi ba mibayt leakademja leanglit?",
  "meayn talmidot umorot baot habayta?",
  "lean atem baim mibayt?",
  "meayn talmidim veimot baim habayta?",
  "lean anachnu baot mibayt?",
  "lean ani baa mikan?",
  "mi lomedet ivrit bebayt?",
  "lean talmidim umorim baim?",
  "eyn imot birchov Sverdlov?",
  "meayn ima baa lirchov Sverdlov?",
  "ma morot lerusit lomdot bebayt im imot?",
  "anachnu gam imot?",
  "lean morim baim?",
  "yesh more lemuzika birchov Komsomolskaja?",
  "meayn anachnu baot lepo?",
  "mi oved im talmidim birchov Komsomolskaja?",
  "talmid oved, vehem?",
  "meayn aten baot?",
  "aba oved im anachnu?",
  "ani mora o talmida?",
  "mi lomedet rusit im mora leanglit bebayt?",
  "eyfo mora gara?",
  "meayn imot umorot baot?",
  "eyfo mora leivrit gara?",
  "mi ovedet im more birchov?",
  "eyfo anachnu garot?",
  "ma talmida lomedet im morim?",
  "meayn morim baim leakademja leanglit?",
  "ma talmida lomedet birchov Sverdlov im ani?",
  "meayn ani baa lesham?",
  "ani baa lekan o leakademja leanglit?",
  "meayn ani baa lirchov?",
  "eyfo anachnu ovdot?",
  "mi more?",
  "eyfo hem morim leanglit?",
  "eyn morim leanglit birchov Komsomolskaja?",
  "lean ani baa misham?",
  "lean hen baot meuniversita?",
  "ma imot lomdot im ani?",
  "anachnu morot o imot?",
  "eyn morim birchov Sverdlov?",
  "ani baa mikan o mibayt?",
  "ma imot lomdot im morot leivrit vetalmidot?",
  "hem lo morim leanglit?",
  "meayn talmid ba?",
  "talmid achshav lomed muzika im anachnu vehen birchov, veatem?",
  "lean talmidim baim merechov Komsomolskaja?",
  "ma morim lomdim im talmidim?",
  "mi oved beuniversita?",
  "lean hem baim misham?",
  "eyfo at mora lemuzika?",
  "eyn talmidim bebayt?",
  "lean imot baot merechov?",
  "ma talmidim lomdim beakademja?",
  "atem veanachnu garim gam birchov?",
  "ma abim lomdim bebayt im mora leanglit?",
  "yesh talmidim beuniversita?",
  "eyfo hu more?",
  "lean aten vehen baot merechov?",
  "lean more lerusit ba misham?",
  "mi ba misham lekan?",
  "hen lo imot, vehu?",
  "ma talmidim lomdim birchov Sverdlov im ata?",
  "mi ba mikan lirchov?",
  "meayn hen veaten baot leulpan?",
  "mi baa mibayt lepo?",
  "lean imot vetalmidot baot mikan?",
  "ma abim lomdim im morot leanglit veimot?",
  "ma talmidot lomdot im hu?",
  "aten baot mibayt o mipo?",
  "ma mora leivrit lomedet bebayt?",
  "talmid ba lirchov Sverdlov?",
  "lean aba ba misham?",
  "meayn ani baa lirchov Komsomolskaja?",
  "talmidim baim meuniversita o misham?",
  "ma abim lomdim im more leanglit?",
  "anachnu gam talmidim?",
  "ani bebayt o beuniversita?",
  "meayn anachnu baim lirchov?",
  "ani baa lekan merechov o misham?",
  "ma mora leivrit lomedet beakademja lerusit im talmidot umorot?",
  "yesh aba bebayt?",
  "ata achshav gar gam birchov Komsomolskaja?",
  "lean talmidim veimot baim?",
  "ima ovedet im ata, vehu?",
  "eyfo anachnu morim leivrit?",
  "anachnu baot habayta o leulpan?",
  "eyn morot birchov Komsomolskaja?",
  "eyn talmid bebayt?",
  "morot leivrit veabim lomdim, veatem?",
  "lean ani ba mipo?",
  "talmida ovedet im hem, veaten?",
  "meayn talmid ba leuniversita?",
  "lean anachnu baim merechov Komsomolskaja?",
  "eyfo ima ovedet?",
  "lean ata ba mibayt?",
  "ma abim lomdim im talmidot veimot?",
  "ma morim leanglit lomdim beakademja lemuzika?",
  "ma ima lomedet im at?",
  "mi oved im anachnu beakademja lerusit?",
  "hem ovdim im morim lemuzika gam bebayt vegam beakademja, veata?",
  "mi lomed gam rusit vegam ivrit im imot vetalmidot beuniversita?",
  "ata lo aba, vehu?",
  "eyfo ani more leivrit?",
  "ma morot leanglit lomdot im talmidot?",
  "talmida lomedet gam rusit vegam anglit, veatem?",
  "meayn hi baa lepo?",
  "talmida ovedet, vehu?",
  "ma morim lomdim im aten?",
  "eyfo mora ovedet?",
  "yesh imot bebayt?",
  "mi ovedet bebayt?",
  "lean talmidot umorot baot?",
  "meayn abim umorim leanglit baim habayta?",
  "lean ata ba meuniversita?",
  "lean ani ba misham?",
  "lean mora baa merechov Komsomolskaja?",
  "ani mora lerusit o ima?",
  "ma aba lomed im mora lerusit?",
  "yesh akademja lerusit birchov Komsomolskaja?",
  "ani lomedet beakademja, veat?",
  "ma talmidim lomdim im talmid?",
  "ma talmidot lomdot beakademja lerusit?",
  "morot veimot ovdot im aten vehen, vehem?",
  "ma morot lomdot birchov im ani?",
  "mi lomedet ivrit verusit im morim veabim birchov?",
  "lean mora leanglit baa?",
  "eyn aba birchov?",
  "mi baa mipo?",
  "lean more lemuzika ba mikan?",
  "mi morot lemuzika?",
  "meayn more leivrit ba habayta?",
  "hen veanachnu baim mipo o merechov?",
  "aten baot habayta o lesham?",
  "aten vehen baot lirchov Sverdlov mibayt o mikan?",
  "meayn ani baa lekan?",
  "anachnu morot lerusit o talmidot?",
  "lean mora lemuzika baa mibayt?",
  "ma more lerusit lomed im abim umorim?",
  "meayn imot baot habayta?",
  "ima baa merechov Komsomolskaja o misham?",
  "meayn aten veanachnu baot lirchov Komsomolskaja?",
  "lean talmidim baim merechov Sverdlov?",
  "meayn more leivrit ba?",
  "eyn ulpan birchov Komsomolskaja?",
  "meayn abim umorot baim habayta?",
  "ata ba leuniversita mibayt o merechov Sverdlov?",
  "yesh universita birchov Komsomolskaja?",
  "mi lomed beuniversita?",
  "mi baa habayta mikan?",
  "eyfo ani oved?",
  "ma mora lomedet beakademja lerusit im hu?",
  "morim achshav baim habayta?",
  "eyfo ani more lemuzika?",
  "ata gam more leanglit, veat?",
  "aten veanachnu lomdim?",
  "ma mora leanglit lomedet?",
  "eyfo aba lomed anglit verusit?",
  "ma abim lomdim im ima?",
  "mi baa meakademja lerusit?",
  "eyn akademja leivrit birchov Komsomolskaja?",
  "meayn talmidot veabim baim habayta?",
  "meayn ani baa?",
  "ma mora lomedet im anachnu?",
  "ani more o aba?",
  "mi lomedet rusit veanglit bebayt?",
  "aten baot merechov Sverdlov o mibayt?",
  "talmidim ovdim?",
  "lean ima baa meakademja lerusit?",
  "mora lerusit baa mipo o merechov Komsomolskaja?",
  "mi ba merechov Komsomolskaja habayta?",
  "lean aten vehem baim merechov?",
  "mi oved im talmid birchov Komsomolskaja?",
  "mi baa mikan habayta?",
  "mi mora leanglit?",
  "hen talmidot o morot?",
  "hen baot habayta merechov o mikan?",
  "yesh akademja birchov?",
  "ma aba lomed im ima?",
  "lean talmidot baot meulpan?",
  "lean ani ba mibayt?",
  "more leivrit ba lesham mipo o merechov?",
  "ma imot lomdot beulpan?",
  "eyfo at mora lerusit?",
  "eyfo talmid lomed rusit im ata?",
  "meayn hen veaten baot?",
  "mi lomed anglit bebayt?",
  "mi ba leuniversita?",
  "lean more leivrit ba mipo?",
  "ani oved im talmida, veatem?",
  "atem gam talmidim vegam morim, veat?",
  "morot baot mibayt o mikan?",
  "lean abim baim meuniversita?",
  "hu ba meulpan habayta o lepo?",
  "ima baa habayta meuniversita o mikan?",
  "lean more ba meakademja lemuzika?",
  "ma morot leivrit lomdot beulpan im talmid?",
  "ani baa mipo o meakademja leanglit?",
  "meayn talmidim umorim baim lirchov Komsomolskaja?",
  "mi baa lekan merechov?",
  "lean abim baim mipo?",
  "ma abim lomdim im imot?",
  "meayn more lemuzika ba leuniversita?",
  "meayn morot baot habayta?",
  "hu ba mipo o merechov Sverdlov?",
  "mi lomedet anglit im atem birchov?",
  "meayn hen veanachnu baot leulpan?",
  "hem baim mikan lirchov Komsomolskaja o habayta?",
  "meayn ani baa leakademja lemuzika?",
  "anachnu morim leivrit o abim?",
  "hen veaten baot habayta o lekan?",
  "anachnu morot lemuzika o talmidot?",
  "hen imot?",
  "atem baim mibayt o merechov?",
  "lean mora leivrit baa merechov Komsomolskaja?",
  "ma more lomed beulpan im ani?",
  "imot umorot lerusit baot habayta mikan o merechov Sverdlov?",
  "more oved, vehen?",
  "meayn at baa lirchov Sverdlov?",
  "eyn imot beulpan?",
  "eyfo anachnu morim leanglit?",
  "abim vetalmidot baim meulpan habayta o lirchov?",
  "ma imot lomdot beulpan im abim?",
  "lean morim leanglit baim?",
  "mora leanglit ovedet?",
  "ma abim lomdim beulpan?",
  "mi lomed gam rusit vegam muzika birchov Komsomolskaja?",
  "ma aba lomed im more leanglit?",
  "eyfo anachnu morot leanglit?",
  "meayn aten baot habayta?",
  "ma talmidot lomdot birchov im hen?",
  "ata lomed muzika veivrit?",
  "eyfo more gar?",
  "ma mora lerusit lomedet im more?",
  "atem lo talmidim, veaten?",
  "ma talmidim lomdim birchov im mora leanglit?",
  "lean talmid ba merechov?",
  "talmida beakademja lerusit o beulpan?",
  "aba ba habayta?",
  "ani achshav gara gam birchov?",
  "lean morot lerusit vetalmidot baot misham?",
  "talmida ovedet beakademja o bebayt?",
  "ata more o aba?",
  "eyfo talmidot garot?",
  "mi baa mibayt leulpan?",
  "ma imot lomdot im morim umorot leanglit?",
  "talmidim baim meulpan o meuniversita?",
  "lean morim baim merechov Komsomolskaja?",
  "yesh morot bebayt?",
  "ma morot leivrit lomdot?",
  "hu oved im atem?",
  "mi morim?",
  "anachnu talmidim, vehen?",
  "lean talmid ba merechov Sverdlov?",
  "ata gam aba vegam talmid, vehen?",
  "eyfo hi lomedet rusit im ata?",
  "ima gara birchov, vehem?",
  "mi lomed rusit veivrit im morot veimot birchov?",
  "ima achshav gara gam birchov?",
  "eyfo mora lemuzika lomedet rusit?",
  "lean more ba?",
  "anachnu ovdot im more lemuzika?",
  "at lo mora?",
  "ani mora lerusit o talmida?",
  "ma morot leanglit lomdot im more leivrit?",
  "hu ba habayta mikan o merechov?",
  "yesh ulpan birchov Komsomolskaja?",
  "mi baa leulpan mipo?",
  "ima baa mipo habayta o lirchov?",
  "yesh morim birchov Komsomolskaja?",
  "hem morim o talmidim?",
  "lean atem baim merechov Sverdlov?",
  "mi mora lemuzika?",
  "ma mora lerusit lomedet birchov Komsomolskaja im talmidot?",
  "ma aba lomed bebayt?",
  "meayn more ba lirchov Komsomolskaja?",
  "eyfo anachnu morot leivrit?",
  "ma morot lomdot im hen?",
  "yesh abim birchov?",
  "ima baa meulpan o mikan?",
  "talmidim ovdim im imot umorot bebayt o beulpan?",
  "meayn aten vehem baim leulpan?",
  "abim lomdim ivrit im hem veanachnu?",
  "mi baa leuniversita meakademja lerusit?",
  "anachnu gam imot, veat?",
  "aten talmidot o morot leanglit?",
  "ma morim lomdim birchov im morot lerusit veimot?",
  "ma talmid lomed im hu?",
  "yesh imot birchov?",
  "mi gara birchov Sverdlov?",
  "aba ba leakademja lerusit o habayta?",
  "ani gam talmid?",
  "yesh more beakademja lemuzika?",
  "talmidim baim lepo, veata?",
  "ma morot lomdot im ata?",
  "ma abim lomdim im aten veanachnu?",
  "eyfo aten veanachnu lomdot?",
  "talmidot vetalmidim lomdim, vehen?",
  "mi ovedet birchov Sverdlov?",
  "meayn more leivrit ba leakademja leanglit?",
  "lean hu ba mikan?",
  "anachnu veatem baim merechov Sverdlov lesham o habayta?",
  "ata ba leulpan misham o merechov Sverdlov?",
  "meayn morim lemuzika baim?",
  "mora leivrit baa habayta, vehu?",
  "yesh more birchov?",
  "ata ba mibayt o merechov?",
  "mi lomed muzika verusit birchov?",
  "ma abim lomdim bebayt im morim lemuzika vetalmidim?",
  "ata ba lirchov Sverdlov meuniversita o meakademja?",
  "eyfo atem morim leivrit?",
  "ma imot lomdot bebayt im morot?",
  "mi gara beakademja lemuzika?",
  "meayn imot vetalmidot baot lepo?",
  "ma more lomed im anachnu?",
  "anachnu vehen ovdot im aten?",
  "eyn akademja lemuzika birchov Sverdlov?",
  "ma ima lomedet bebayt?",
  "lean more ba merechov?",
  "talmidim baim habayta o lesham?",
  "meayn talmidim baim?",
  "more lerusit achshav lomed ivrit birchov, veata?",
  "meayn hi baa lekan?",
  "hu more o talmid?",
  "ma more lomed birchov?",
  "mi ba misham?",
  "morot baot habayta o lepo?",
  "lean abim umorim baim misham?",
  "mi ovedet im imot birchov?",
  "mora leanglit ovedet im at?",
  "meayn hen baot habayta?",
  "ma ima lomedet im mora?",
  "ma talmidot lomdot bebayt im mora lemuzika?",
  "hen gam morot leivrit?",
  "lean morot leivrit baot merechov Sverdlov?",
  "ma imot lomdot im atem?",
  "ma ima lomedet?",
  "eyfo anachnu morot lemuzika?",
  "mi oved im ani beulpan?",
  "lean morot veabim baim merechov?",
  "hi lomedet muzika im ata?",
  "ma talmidim lomdim im talmidot?",
  "mi ba meuniversita habayta?",
  "mi gar birchov Komsomolskaja?",
  "abim baim habayta mikan o meuniversita?",
  "lean ata ba meulpan?",
  "ma aba lomed?",
  "more lerusit oved im morot leivrit gam birchov Komsomolskaja?",
  "ani ima o mora?",
  "meayn hem baim habayta?",
  "yesh more leivrit birchov Komsomolskaja?",
  "hen morot lerusit o imot?",
  "mi ovedet im ani bebayt?",
  "eyfo morot lemuzika garot?",
  "ani mora leivrit o talmida?",
  "ani oved im talmida?",
  "lean at baa mibayt?",
  "aten lo morot?",
  "ma talmida lomedet beulpan?",
  "ma mora lomedet im ima?",
  "lean abim umorot baim?",
  "mi ba habayta meakademja?",
  "mi lomed birchov Sverdlov?",
  "lean abim baim merechov?",
  "meayn talmidot baot leulpan?",
  "mi ovedet im hem birchov Komsomolskaja?",
  "atem talmidim o abim?",
  "ma more lomed bebayt im talmida?",
  "eyfo imot lomdot rusit veivrit?",
  "talmid oved?",
  "ma talmidim lomdim im hu?",
  "yesh akademja birchov Sverdlov?",
  "lean aten veanachnu baot?",
  "mi baa lirchov?",
  "meayn ani ba leuniversita?",
  "ma talmida lomedet im talmidim umorim lerusit?",
  "mi ba mikan habayta?",
  "meayn atem baim?",
  "ma abim lomdim bebayt im ima?",
  "ma morot lomdot birchov Sverdlov?",
  "ma morot lomdot birchov Komsomolskaja im anachnu vehen?",
  "lean talmidot vetalmidim baim mibayt?",
  "ma abim lomdim birchov im ima?",
  "mi baa mipo lirchov?",
  "mi lomedet anglit bebayt?",
  "lean aba ba merechov Komsomolskaja?",
  "ma morot lemuzika lomdot im hem veanachnu?",
  "ma talmida lomedet bebayt im talmidot umorot?",
  "aten morot?",
  "ma more lemuzika lomed?",
  "lean ani baa meulpan?",
  "ata lo more, vehu?",
  "ma talmid lomed beulpan?",
  "meayn imot umorot lerusit baot?",
  "mi lomedet muzika birchov?",
  "morim ovdim im abim vetalmidim, veat?",
  "ma more leivrit lomed birchov?",
  "mi baa habayta meakademja?",
  "ma aba lomed im aten veanachnu?",
  "lean morim lerusit baim mibayt?",
  "ani gam aba vegam more lerusit, vehem?",
  "mi ba merechov Komsomolskaja?",
  "hem garim gam beulpan vegam beakademja lemuzika, veatem?",
  "mi oved im aba bebayt?",
  "morot baot meuniversita o mipo?",
  "ma aba lomed im more?",
  "anachnu baot mikan o meuniversita?",
  "meayn hen veanachnu baot habayta?",
  "ma talmidot lomdot im imot?",
  "ani gar gam bebayt vegam beakademja, veaten?",
  "mi gara beulpan?",
  "aten imot o morot?",
  "ma mora lomedet birchov Sverdlov?",
  "ani more lerusit o talmid?",
  "ma imot lomdot birchov?",
  "ma talmid lomed birchov im imot?",
  "anachnu vehem ovdim?",
  "ma more leanglit lomed birchov im imot?",
  "mi lomed gam ivrit vegam muzika im talmidot bebayt?",
  "ma talmida lomedet beakademja im ani?",
  "ma mora leivrit lomedet birchov Sverdlov?",
  "ma morot lomdot im hem?",
  "eyfo hem morim?",
  "eyn mora birchov Komsomolskaja?",
  "mi baa lirchov Sverdlov?",
  "ani lomed ivrit, vehem?",
  "mi ba merechov habayta?",
  "meayn hu ba?",
  "mi baa merechov habayta?",
  "lean mora leanglit baa meulpan?",
  "morot lomdot muzika veivrit bebayt o beuniversita?",
  "eyn morot bebayt?",
  "mi baa mipo lesham?",
  "eyfo abim veimot garim?",
  "anachnu gam imot, vehen?",
  "ani achshav ba habayta?",
  "hem morim leivrit o talmidim?",
  "ma talmida lomedet beulpan im ima?",
  "meayn anachnu veatem baim lepo?",
  "mi ba habayta?",
  "anachnu baot lirchov Sverdlov o habayta?",
  "aten imot o talmidot?",
  "talmidot garot gam beuniversita vegam bebayt, veaten?",
  "yesh talmid beakademja?",
  "more lerusit oved?",
  "mi baa merechov Komsomolskaja habayta?",
  "lean hem baim mipo?",
  "abim achshav baim leuniversita?",
  "meayn talmida baa lepo?",
  "ima lomedet beakademja lemuzika o beulpan?",
  "at gam ima vegam talmida?",
  "morot veabim achshav baim mikan?",
  "mi lomed gam muzika vegam rusit birchov Sverdlov?",
  "ma more leivrit lomed?",
  "hu lomed gam rusit vegam ivrit?",
  "lean aba ba mikan?",
  "ma talmidot lomdot beulpan?",
  "morot leanglit veimot baot mikan o merechov Komsomolskaja?",
  "eyfo hu talmid?",
  "atem abim o morim?",
  "meayn hen baot?",
  "mi oved im aba birchov Komsomolskaja?",
  "aten baot merechov o mikan?",
  "ma morim lomdim beuniversita im ata?",
  "talmidot umorim baim lekan o lirchov?",
  "ma morim lomdim bebayt im hi?",
  "ma morim lerusit lomdim bebayt?",
  "meayn morot veimot baot habayta?",
  "lean anachnu vehem baim merechov Sverdlov?",
  "meayn talmidot veimot baot?",
  "mi baa lirchov Komsomolskaja mipo?",
  "ma mora lomedet birchov Komsomolskaja im hi?",
  "hu talmid o more?",
  "hen ovdot, vehem?",
  "talmid ba mipo, vehi?",
  "meayn atem veanachnu baim?",
  "ma talmid lomed birchov?",
  "morot achshav ovdot gam beakademja leivrit vegam bebayt, veatem?",
  "talmid ba merechov leuniversita o habayta?",
  "ma talmidim lomdim beuniversita im ani?",
  "mi ba mipo habayta?",
  "talmid achshav ba habayta?",
  "ma mora leivrit lomedet im ani?",
  "mi ba lesham mipo?",
  "anachnu morot leivrit o talmidot?",
  "hen beakademja leanglit o bebayt?",
  "anachnu veatem baim misham habayta, vehu?",
  "ma morim leanglit lomdim im talmida?",
  "meayn at baa lirchov?",
  "mi ba habayta meulpan?",
  "hu oved im hi?",
  "eyfo anachnu ovdim im morot lemuzika vetalmidot?",
  "ma morim lomdim im at?",
  "mi ovedet im anachnu beuniversita?",
  "mi gar beakademja?",
  "at lo ima?",
  "lean ani baa meuniversita?",
  "ma more lemuzika lomed bebayt?",
  "meayn more lerusit ba habayta?",
  "mi ovedet im imot beakademja leanglit?",
  "atem baim mipo o meulpan?",
  "hem veanachnu lomdim gam anglit vegam ivrit im mora?",
  "meayn morot baot?",
  "at lomedet, veaten?",
  "mi ba habayta merechov Sverdlov?",
  "morim lemuzika veimot ovdim, veaten?",
  "meayn ima baa lekan?",
  "atem morim lerusit o talmidim?",
  "lean atem veanachnu baim mipo?",
  "ma talmidot lomdot birchov Komsomolskaja?",
  "mi ba mipo?",
  "ma talmid lomed im aba?",
  "mi ba mikan leulpan?",
  "mi lomedet gam ivrit vegam muzika im talmidim umorot bebayt?",
  "lean more lerusit ba?",
  "ata lo aba?",
  "ma talmidot lomdot?",
  "mi lomedet gam anglit vegam ivrit im atem bebayt?",
  "morim umorot lemuzika garim beulpan o bebayt?",
  "ma morim lerusit lomdim birchov Sverdlov?",
  "mi lomed rusit bebayt?",
  "eyfo abim umorot lemuzika garim?",
  "ma ima lomedet birchov Sverdlov im ani?",
  "hen gam imot vegam morot?",
  "lean aba ba?",
  "eyn talmidim beulpan?",
  "talmidot veimot achshav baot misham lirchov Sverdlov, vehen?",
  "meayn atem veanachnu baim habayta?",
  "lean anachnu baot merechov?",
  "meayn anachnu veaten baot?",
  "ma talmida lomedet beulpan im anachnu?",
  "eyfo ani lomed?",
  "ani talmida o mora leanglit?",
  "yesh more leanglit bebayt?",
  "eyn ima birchov?",
  "mi lomed muzika birchov?",
  "talmidim baim mipo leuniversita o lirchov Sverdlov?",
  "talmidot lomdot ivrit im hen, veata?",
  "mi baa lekan merechov Komsomolskaja?",
  "lean morim baim misham?",
  "hem achshav baim misham leuniversita, veat?",
  "ani talmid?",
  "anachnu ovdot im more gam beakademja lemuzika vegam beuniversita?",
  "ma mora lomedet beuniversita im talmid?",
  "mi baa misham habayta?",
  "hen veanachnu lomdot rusit?",
  "ani ovedet im ima, vehen?",
  "talmida ovedet, veatem?",
  "hem baim habayta?",
  "anachnu lomdim anglit, vehu?",
  "mi baa lepo?",
  "lean ima baa merechov?",
  "eyfo hen veaten lomdot?",
  "ma talmid lomed bebayt im talmida?",
  "mi lomed ivrit veanglit im ani beuniversita?",
  "hu lo aba?",
  "eyfo more lomed rusit?",
  "ma talmida lomedet im ani?",
  "ma talmida lomedet birchov Komsomolskaja?",
  "morot lemuzika lomdot gam rusit vegam anglit?",
  "lean morim baim mibayt?",
  "ma aba lomed beuniversita?",
  "ma talmida lomedet birchov im ani?",
  "aten gam imot?",
  "imot ovdot, vehen?",
  "mi ba lirchov Sverdlov?",
  "meayn anachnu veatem baim lirchov?",
  "ma talmidot lomdot im hen?",
  "ma more leanglit lomed birchov Sverdlov?",
  "meayn hen veanachnu baot lekan?",
  "mi lomed beakademja?",
  "eyfo hem morim lemuzika?",
  "ata more o talmid?",
  "ma talmidot lomdot bebayt?",
  "meayn talmidim baim lirchov?",
  "meayn mora baa?",
  "meayn ata ba leulpan?",
  "more leivrit ba lepo o habayta?",
  "lean aten vehen baot?",
  "ma more lerusit lomed birchov Komsomolskaja im hen veatem?",
  "abim baim mipo o merechov Sverdlov?",
  "ma imot lomdot im anachnu?",
  "meayn morot leanglit vetalmidot baot?",
  "eyfo anachnu vehen garim?",
  "ma aba lomed birchov?",
  "eyfo talmidim vetalmidot ovdim?",
  "eyfo morot garot?",
  "mi ovedet im ani birchov Sverdlov?",
  "ma talmidot lomdot beulpan im ani?",
  "ani achshav gara gam beuniversita vegam bebayt?",
  "meayn imot umorot lemuzika baot?",
  "at ovedet im anachnu bebayt o beuniversita?",
  "eyn abim birchov Sverdlov?",
  "anachnu morim o abim?",
  "imot veabim garim bebayt o beuniversita?",
  "mi gara birchov Komsomolskaja?",
  "mi lomedet ivrit im ani birchov?",
  "lean imot umorim baim?",
  "ani talmid o more leivrit?",
  "aba lomed anglit im morot veimot birchov Sverdlov?",
  "mi lomed ivrit verusit beakademja?",
  "hen beakademja leivrit o bebayt?",
  "anachnu talmidim o morim?",
  "ma morot lemuzika lomdot im hi?",
  "lean aten baot merechov Sverdlov?",
  "meayn talmidim veabim baim lirchov Sverdlov?",
  "at lo mora, veata?",
  "meayn mora lemuzika baa?",
  "yesh morim leanglit birchov?",
  "ata ba lesham o habayta?",
  "eyfo hen lomdot?",
  "talmid achshav oved gam birchov Komsomolskaja, veatem?",
  "eyfo aten morot leivrit?",
  "ma talmidim lomdim bebayt im talmida?",
  "lean morim baim merechov?",
  "meayn ani ba lirchov Komsomolskaja?",
  "eyn akademja birchov?",
  "ma morim lomdim beuniversita im atem veaten?",
  "ma talmid lomed bebayt im abim veimot?",
  "imot ovdot im talmida, veaten?",
  "lean talmidot umorot baot misham?",
  "ma morim lomdim birchov?",
  "mora leivrit achshav lomedet rusit gam bebayt vegam beakademja?",
  "hi lomedet muzika veanglit birchov, veatem?",
  "ma talmid lomed bebayt im morim?",
  "talmidot umorot beulpan o bebayt?",
  "meayn talmidot baot lirchov Sverdlov?",
  "meayn aba ba leulpan?",
  "eyfo anachnu talmidim?",
  "eyfo anachnu morim lerusit?",
  "eyfo anachnu veatem garim?",
  "eyfo ani lomed muzika veivrit?",
  "imot baot misham habayta, veatem?",
  "ma talmida lomedet birchov im ata?",
  "anachnu ovdot gam beuniversita vegam beulpan?",
  "eyfo mora leanglit ovedet im hu?",
  "meayn imot vetalmidim baim?",
  "ma more lomed im aba?",
  "hi ovedet im hu, veatem?",
  "eyn mora beulpan?",
  "hen baot habayta o lekan?",
  "meayn anachnu vehem baim habayta?",
  "ma aba lomed bebayt im talmid?",
  "hem gam abim, vehen?",
  "eyfo hu more lemuzika?",
  "mi baa lekan?",
  "meayn ani ba lekan?",
  "lean morot umorim baim mikan?",
  "eyfo ani oved im mora leanglit?",
  "mi lomedet bebayt?",
  "lean more ba mikan?",
  "ma morim leanglit lomdim beuniversita im aba?",
  "meayn talmidim vetalmidot baim habayta?",
  "ma morot lerusit lomdot im anachnu?",
  "meayn talmidot umorot leanglit baot?",
  "lean morim vetalmidim baim?",
  "hen veanachnu achshav ovdot im talmid gam beuniversita vegam beakademja lemuzika, veaten?",
  "meayn talmidot vetalmidim baim?",
  "aten achshav baot mibayt?",
  "mi lomedet rusit im talmid bebayt?",
  "mi baa merechov Sverdlov lekan?",
  "meayn anachnu baot?",
  "lean anachnu baot?",
  "meayn ani baa lepo?",
  "mi ovedet beuniversita?",
  "lean imot baot?",
  "aba achshav oved im hen veaten birchov Komsomolskaja?",
  "ani gam ima?",
  "imot ovdot im more lerusit?",
  "anachnu gam morot lerusit?",
  "mi talmidim?",
  "imot umorot lomdot?",
  "lean atem baim?",
  "ma morot leivrit lomdot im abim?",
  "lean ima baa merechov Komsomolskaja?",
  "eyn ulpan birchov Sverdlov?",
  "ma mora lemuzika lomedet bebayt?",
  "lean aten baot mikan?",
  "lean anachnu vehem baim?",
  "ani ba mikan habayta o lesham?",
  "more ba mipo lirchov Komsomolskaja o leakademja?",
  "meayn talmidot veimot baot habayta?",
  "lean ima baa meulpan?",
  "anachnu vehen baim habayta mikan o misham?",
  "meayn anachnu baim habayta?",
  "lean morim lemuzika baim merechov Komsomolskaja?",
  "ma mora lomedet beuniversita im aten veanachnu?",
  "lean morot vetalmidim baim merechov?",
  "eyfo ani gar?",
  "mi lomedet muzika im aba birchov?",
  "ma talmid lomed birchov Sverdlov im mora?",
  "mi ba habayta merechov Komsomolskaja?",
  "meayn hi baa leakademja?",
  "mi ovedet im hen veaten beulpan?",
  "ma talmid lomed beuniversita im anachnu?",
  "ma mora lomedet im hen veaten?",
  "abim umorot lerusit achshav baim misham?",
  "ma talmidot lomdot im at?",
  "lean morot umorim baim?",
  "mora leivrit ovedet?",
  "aten talmidot o imot?",
  "lean at baa meulpan?",
  "meayn anachnu baot lirchov?",
  "ani baa lirchov Komsomolskaja, veat?",
  "eyfo aten morot lemuzika?",
  "eyn talmidot beuniversita?",
  "lean imot umorot baot mipo?",
  "eyn ima birchov Sverdlov?",
  "meayn talmidim baim habayta?",
  "eyfo anachnu lomdim ivrit veanglit?",
  "yesh morot leivrit beuniversita?",
  "mi ba lesham mibayt?",
  "ma morim lerusit lomdim bebayt im anachnu?",
  "yesh akademja birchov Komsomolskaja?",
  "ani ba misham o mibayt?",
  "ma talmida lomedet im talmidot veimot?",
  "hi ima o talmida?",
  "lean imot baot mikan?",
  "morot veimot baot mipo leulpan o lirchov Komsomolskaja?",
  "aba oved, veaten?",
  "imot ovdot gam birchov?",
  "lean mora leivrit baa?",
  "ma ima lomedet im abim veimot?",
  "ata lomed muzika?",
  "lean talmidot baot merechov?",
  "yesh imot beulpan?",
  "meayn talmidot baot?",
  "anachnu achshav baot habayta, vehu?",
  "eyfo hi talmida?",
  "lean at baa merechov Sverdlov?",
  "imot baot merechov Sverdlov o meuniversita?",
  "meayn imot umorim leanglit baim?",
  "lean talmid ba meakademja?",
  "mi lomed gam rusit vegam ivrit im ani birchov Komsomolskaja?",
  "ma morot lerusit lomdot birchov im ima?",
  "ma morot leivrit lomdot beuniversita?",
  "ma morim leivrit lomdim?",
  "eyn akademja birchov Komsomolskaja?",
  "ima achshav baa lepo?",
  "meayn atem vehen baim?",
  "lean ata ba mipo?",
  "mi ba lekan merechov Sverdlov?",
  "eyn morim bebayt?",
  "eyfo morim leivrit garim?",
  "lean ata ba misham?",
  "eyfo ata more lerusit?",
  "meayn more lerusit ba?",
  "eyfo anachnu talmidot?",
  "talmidot ovdot?",
  "meayn anachnu vehen baim habayta?",
  "ma ima lomedet beakademja lemuzika?",
  "ma talmidim lomdim bebayt im talmidot?",
  "lean ata ba merechov Komsomolskaja?",
  "ma talmidot lomdot beuniversita im mora lemuzika?",
  "meayn anachnu baim lesham?",
  "eyfo ata more?",
  "more lemuzika ba lirchov mikan o meulpan?",
  "at gam mora lerusit vegam talmida, vehi?",
  "eyfo hen talmidot?",
  "mi ba lirchov Sverdlov misham?",
  "anachnu veaten lomdot ivrit umuzika im hem birchov Komsomolskaja?",
  "lean hem veanachnu baim meulpan?",
  "mi mora leivrit?",
  "lean talmid ba mibayt?",
  "ma mora lomedet im aten?",
  "talmidot veimot achshav ovdot birchov Sverdlov?",
  "anachnu morot leanglit o talmidot?",
  "lean more leanglit ba?",
  "hu aba o talmid?",
  "anachnu abim, veata?",
  "meayn ani baa leuniversita?",
  "meayn morot veabim baim habayta?",
  "mi lomed ivrit verusit bebayt?",
  "meayn imot umorot lerusit baot habayta?",
  "ma abim lomdim bebayt im aten veanachnu?",
  "aten morot leivrit o imot?",
  "lean mora baa?",
  "eyfo ani mora?",
  "ani baa mikan habayta o lirchov Komsomolskaja?",
  "hen baot habayta mikan, veatem?",
  "ma morot lomdot beulpan?",
  "ma talmida lomedet birchov im morot leivrit?",
  "mi baa leulpan mibayt?",
  "eyn more beulpan?",
  "ma more leanglit lomed im aten?",
  "eyn abim birchov?",
  "mi ba merechov Sverdlov?",
  "ata oved?",
  "ma talmid lomed birchov Sverdlov im ani?",
  "ma ima lomedet birchov Sverdlov?",
  "ani ovedet, veat?",
  "ma abim lomdim birchov?",
  "anachnu lomdot muzika veivrit?",
  "lean at baa merechov?",
  "aten baot meulpan o meakademja lerusit?",
  "ma more lomed beuniversita im at?",
  "meayn ani ba?",
  "eyfo at mora leivrit?",
  "mi ovedet im talmidot bebayt?",
  "eyn morot leivrit beulpan?",
  "anachnu ovdim, veat?",
  "lean anachnu veaten baot mibayt?",
  "hem talmidim o morim lemuzika?",
  "ma morim lomdim?",
  "meayn talmida baa lirchov?",
  "lean talmid ba meuniversita?",
  "talmidot baot mibayt, veaten?",
  "aten baot lirchov Sverdlov o habayta?",
  "hem baim mipo lirchov Sverdlov o habayta?",
  "eyfo at mora leanglit?",
  "ata lomed?",
  "lean abim baim mibayt?",
  "mi ba meuniversita lekan?",
  "meayn hem baim lirchov Komsomolskaja?",
  "hi baa misham habayta o lirchov?",
  "eyfo ani mora leanglit?",
  "eyfo talmidim veabim lomdim gam rusit vegam ivrit?",
  "ma more leivrit lomed im morim lemuzika?",
  "mi baa meakademja lekan?",
  "lean atem baim mikan?",
  "ma abim lomdim im ata?",
  "eyn akademja leanglit birchov?",
  "ma talmid lomed im anachnu veaten?",
  "meayn hi baa habayta?",
  "lean talmida baa merechov Komsomolskaja?",
  "eyfo ani talmida?",
  "mi ba mipo lirchov Komsomolskaja?",
  "mi lomed ivrit veanglit birchov Sverdlov?",
  "eyfo hem morim leivrit?",
  "meayn talmid ba habayta?",
  "eyn more leanglit bebayt?",
  "ma abim lomdim?",
  "hi mora o talmida?",
  "morim lerusit beuniversita o beakademja?",
  "yesh abim birchov Sverdlov?",
  "mi baa merechov Sverdlov habayta?",
  "mi ovedet beulpan?",
  "hem talmidim?",
  "ma more lerusit lomed birchov?",
  "mi ba merechov Komsomolskaja leuniversita?",
  "lean ani baa mibayt?",
  "ma talmidim lomdim birchov?",
  "mi talmidot?",
  "mi ba mibayt lepo?",
  "meayn atem baim habayta?",
  "eyn abim birchov Komsomolskaja?",
  "meayn anachnu baim?",
  "yesh aba birchov?",
  "lean talmidot veimot baot merechov?",
  "ma abim lomdim im talmidot umorim leanglit?",
  "meayn morot lerusit baot?",
  "morim veabim achshav lomdim birchov?",
  "ani lo more, veat?",
  "ani more lemuzika o aba?",
  "ma talmida lomedet bebayt im morim vetalmidim?",
  "eyn mora bebayt?",
  "ani ovedet?",
  "ma talmidot lomdot beakademja leivrit?",
  "atem ovdim, veaten?",
  "ma mora lerusit lomedet?",
  "eyn akademja birchov Sverdlov?",
  "mi oved im mora leanglit birchov?",
  "meayn talmida baa?",
  "hi ovedet, vehem?",
  "talmidot umorot lemuzika baot meuniversita habayta o lirchov Sverdlov?",
  "lean mora lemuzika baa?",
  "ma morot lerusit lomdot beulpan?",
  "eyfo at gara?",
  "ma morot lomdot im aten vehen?",
  "mi oved im anachnu bebayt?",
  "ani mora leanglit o ima?",
  "meayn abim baim?",
  "mi lomed muzika im talmida birchov Sverdlov?",
  "imot ovdot?",
  "eyfo talmid gar?",
  "ani more?",
  "ma more lomed bebayt im ima?",
  "mi ba leakademja?",
  "lean talmid ba merechov Komsomolskaja?",
  "eyfo more leanglit oved?",
  "ma talmida lomedet im hu?",
  "ma morim lemuzika lomdim?",
  "ma more lerusit lomed im hu?",
  "talmidot umorot baot meuniversita?",
  "more ba leulpan o habayta?",
  "eyn akademja leivrit birchov?",
  "hen garot bebayt o beakademja?",
  "ma morot leivrit lomdot im aba?",
  "meayn talmidim veabim baim habayta?",
  "talmidot umorot baot leulpan?",
  "ma morot lomdot birchov im anachnu vehen?",
  "aba ba misham o mibayt?",
  "ani oved im talmida, vehen?",
  "lean hen veanachnu baot?",
  "anachnu veatem baim meulpan habayta o lekan?",
  "mi baa mikan?",
  "mi oved im talmida birchov Sverdlov?",
  "eyn mora birchov Sverdlov?",
  "meayn aba ba habayta?",
  "ma talmid lomed beulpan im more leivrit?",
  "meayn talmidot umorot baot?",
  "ani gam talmida?",
  "mi ovedet im anachnu vehen bebayt?",
  "ma talmida lomedet bebayt im talmid?",
  "lean abim umorot baim merechov Komsomolskaja?",
  "eyfo imot veabim lomdim gam muzika vegam ivrit?",
  "ani bebayt o beulpan?",
  "mi ba mikan?",
  "hem abim o morim?",
  "meayn talmidim umorot lerusit baim lirchov?",
  "mi gar birchov Sverdlov?",
  "more gar beakademja?",
  "hu ba mikan o merechov?",
  "meayn morim vetalmidot baim?",
  "ani aba o more?",
  "meayn abim baim lirchov?",
  "ma talmida lomedet?",
  "mi lomed anglit umuzika im hi bebayt?",
  "lean aba ba meulpan?",
  "talmidim beuniversita o bebayt?",
  "mi lomedet muzika im hem beakademja lerusit?",
  "ani ba misham lekan o lirchov Komsomolskaja?",
  "lean aten baot meakademja?",
  "eyfo aba lomed?",
  "meayn talmidot baot habayta?",
  "lean anachnu vehen baim mipo?",
  "meayn morim lerusit umorot baim?",
  "lean talmidot baot mipo?",
  "ani lo talmida?",
  "mi lomed anglit birchov Sverdlov?",
  "meayn morim baim habayta?",
  "meayn anachnu baot leulpan?",
  "ma mora lemuzika lomedet birchov Komsomolskaja?",
  "mi ovedet im atem birchov Komsomolskaja?",
  "hu aba o more?",
  "meayn ani ba lirchov?",
  "ani ovedet, vehi?",
  "yesh imot birchov Sverdlov?",
  "ma more lomed im hu?",
  "mi gar beakademja leivrit?",
  "anachnu morot lerusit o imot?",
  "ma talmidim lomdim birchov Komsomolskaja im atem vehen?",
  "talmida achshav lomedet gam birchov Sverdlov, veatem?",
  "aten gam talmidot vegam imot, vehu?",
  "ma mora lomedet birchov im talmida?",
  "lean talmidim vetalmidot baim?",
  "meayn morot lemuzika baot?",
  "meayn anachnu vehen baim lesham?",
  "lean hem baim merechov Komsomolskaja?",
  "morot baot merechov o meulpan?",
  "ma talmid lomed birchov im hi?",
  "ma morot lomdot beakademja leivrit?",
  "eyfo hen morot lemuzika?",
  "lean ima baa misham?",
  "eyn akademja leanglit birchov Sverdlov?",
  "ani more lerusit?",
  "ma ima lomedet im abim?",
  "ma imot lomdot?",
  "ani ba mibayt o mipo?",
  "ani more leivrit o talmid?",
  "eyfo ata talmid?",
  "lean talmidot baot merechov Komsomolskaja?",
  "mi ba merechov?",
  "mi ba lirchov?",
  "mi baa habayta merechov Sverdlov?",
  "ata aba o more?",
  "anachnu beakademja lerusit o bebayt?",
  "eyfo ata oved?",
  "imot umorot lemuzika baot merechov o misham?",
  "meayn hem veanachnu baim?",
  "ma imot lomdot birchov im talmidim vetalmidot?",
  "lean abim baim misham?",
  "ma abim lomdim bebayt im anachnu?",
  "mi gara birchov?",
  "mi ovedet im talmid birchov Sverdlov?",
  "hi lomedet ivrit, vehem?",
  "atem talmidim o morim lerusit?",
  "ata aba o talmid?",
  "ma more leanglit lomed im hem?",
  "eyn talmida bebayt?",
  "ma more leivrit lomed birchov im anachnu veaten?",
  "mi ba misham lirchov Sverdlov?",
  "lean morim veimot baim meakademja leanglit?",
  "eyfo ani lomed gam anglit vegam muzika im anachnu?",
  "lean anachnu baim mipo?",
  "talmidot baot merechov Sverdlov lesham o habayta?",
  "eyn mora birchov?",
  "eyfo aba gar?",
  "mi gar beuniversita?",
  "lean hen baot misham?",
  "mi baa lirchov Sverdlov misham?",
  "yesh talmidim beulpan?",
  "ma imot lomdot bebayt im talmidot veabim?",
  "ma morot lomdot?",
  "lean aten baot?",
  "lean more lerusit ba merechov Sverdlov?",
  "meayn ata ba lesham?",
  "eyn talmid birchov Sverdlov?",
  "anachnu ovdim, veaten?",
  "mi lomedet gam ivrit vegam rusit im talmida bebayt?",
  "ma aba lomed birchov Sverdlov im ani?",
  "aten lo talmidot, vehen?",
  "eyfo ata more leivrit?",
  "ma mora leivrit lomedet beulpan?",
  "mora leanglit ovedet im ima?",
  "meayn ani baa habayta?",
  "more lomed gam muzika vegam rusit?",
  "meayn hu ba lekan?",
  "lean hi baa?",
  "lean aten vehen baot mipo?",
  "atem abim o morim lemuzika?",
  "lean mora leanglit baa mibayt?",
  "anachnu veaten achshav baot meakademja?",
  "hi gam mora lerusit, veat?",
  "eyfo anachnu lomdot?",
  "yesh abim beakademja leivrit?",
  "eyn morot birchov?",
  "ma abim lomdim im talmidim vetalmidot?",
  "aten vehen lomdot?",
  "ata ba lesham merechov, vehi?",
  "meayn mora leanglit baa habayta?",
  "ma talmid lomed beuniversita?",
  "hen gam talmidot?",
  "mora baa mipo lirchov o habayta?",
  "ani baa lepo misham?",
  "meayn aten vehen baot habayta?",
  "ma mora leivrit lomedet im aba?",
  "mi ba mibayt?",
  "mi lomed beulpan?",
  "mi abim?",
  "anachnu talmidim o abim?",
  "meayn morot leivrit baot habayta?",
  "ata talmid o more?",
  "ma talmida lomedet beuniversita im hem?",
  "aba bebayt o beakademja lerusit?",
  "ma talmidim lomdim im ima?",
  "anachnu talmidim?",
  "lean ani baa merechov Sverdlov?",
  "ma more lomed beuniversita im abim vetalmidim?",
  "abim baim mikan o merechov Komsomolskaja?",
  "mi baa lirchov Komsomolskaja?",
  "lean morot lerusit baot?",
  "imot ovdot, veaten?",
  "ma talmid lomed im ani?",
  "meayn aten vehen baot?",
  "lean anachnu baim merechov?",
  "meayn anachnu vehen baot lirchov?",
  "talmidot ovdot im hem beakademja leivrit o beulpan?",
  "ma morot leivrit lomdot birchov?",
  "mi baa lesham?",
  "lean aten veatem baim?",
  "morot leanglit ovdot?",
  "ma talmida lomedet im more leivrit?",
  "ma talmida lomedet bebayt im anachnu vehen?",
  "eyfo ata more leanglit?",
  "eyn abim beuniversita?",
  "atem morim leivrit?",
  "ata more lemuzika o aba?",
  "yesh more lemuzika bebayt?",
  "eyfo hem lomdim gam rusit vegam muzika im more?",
  "lean talmidim umorot baim meuniversita?",
  "hen ovdot im ima?",
  "hi achshav ovedet gam birchov?",
  "anachnu baim merechov lesham?",
  "meayn atem baim leuniversita?",
  "meayn abim baim habayta?",
  "ani ba mibayt o merechov?",
  "at mora lemuzika o talmida?",
  "hu lomed gam muzika vegam ivrit im ani?",
  "eyfo hi mora?",
  "talmidim beulpan o bebayt?",
  "lean anachnu veaten baot mikan?",
  "ma imot lomdot birchov Sverdlov im atem?",
  "ma talmidim lomdim im hen?",
  "lean aten veanachnu baot mikan?",
  "mi lomedet ivrit umuzika bebayt?",
  "meayn imot vetalmidot baot lirchov?",
  "mi oved im more lemuzika beuniversita?",
  "ma abim lomdim im morim leivrit?",
  "hem vehen ovdim gam birchov, vehi?",
  "ma mora lerusit lomedet birchov Komsomolskaja im talmidim veabim?",
  "talmida lomedet?",
  "lean aba ba meakademja?",
  "meayn hem veaten baim?",
  "meayn anachnu vehen baot habayta?",
  "talmid oved im aba?",
  "lean morot lerusit baot misham?",
  "meayn ata ba lepo?",
  "lean talmidim baim?",
  "lean abim vetalmidot baim?",
  "meayn morot vetalmidot baot?",
  "lean hem veanachnu baim mipo?",
  "lean aten vehen baot mikan?",
  "mi oved im talmidim veabim bebayt?",
  "ma mora lerusit lomedet beuniversita?",
  "mi ba habayta meuniversita?",
  "meayn morot leanglit baot lekan?",
  "mi ba habayta mikan?",
  "ata talmid o aba?",
  "eyfo anachnu lomdim muzika im mora lerusit?",
  "lean hem baim?",
  "morot baot merechov Sverdlov leulpan, vehu?",
  "lean talmidot veimot baot?",
  "ma aba lomed bebayt im ani?",
  "anachnu talmidot o morot lerusit?",
  "ma imot lomdot im morot?",
  "abim vetalmidim achshav baim leakademja, vehi?",
  "ma more lerusit lomed?",
  "lean ani ba merechov Komsomolskaja?",
  "mora lemuzika baa habayta mikan o meulpan?",
  "ma mora lemuzika lomedet im at?",
  "meayn at baa?",
  "mi ovedet im hi bebayt?",
  "meayn more lerusit ba lirchov Komsomolskaja?",
  "mi lomed anglit umuzika birchov Sverdlov?",
  "meayn ata ba leuniversita?",
  "ma ima lomedet beulpan im anachnu veatem?",
  "ani baa merechov Sverdlov o mibayt?",
  "lean ima baa mibayt?",
  "meayn morim vetalmidim baim?",
  "lean hen baot?",
  "ma talmidim lomdim bebayt?",
  "hen veanachnu baim meulpan?",
  "ma imot lomdot im more leanglit?",
  "lean anachnu baim misham?",
  "ma talmid lomed beulpan im more?",
  "anachnu talmidot o morot lemuzika?",
  "meayn morim lerusit vetalmidim baim?",
  "meayn more ba?",
  "more leanglit oved im atem?",
  "mora ovedet beuniversita o beakademja?",
  "meayn anachnu baot habayta?",
  "at talmida o mora?",
  "ma talmidot lomdot im ani?",
  "mi gara beakademja leanglit?",
  "morim lemuzika garim gam beulpan vegam beakademja lerusit?",
  "yesh talmidim birchov Komsomolskaja?",
  "ani more lerusit o aba?",
  "mi lomed ivrit bebayt?",
  "ma ima lomedet im hen veanachnu?",
  "lean ani ba mikan?",
  "ani ima o talmida?",
  "ma talmidot lomdot birchov Sverdlov?",
  "meayn hi baa?",
  "at talmida o ima?",
  "mi lomed anglit birchov Komsomolskaja?",
  "mi lomed muzika im talmidot veimot birchov?",
  "talmidot umorim lerusit ovdim gam birchov Sverdlov, veat?",
  "mi lomedet birchov Sverdlov?",
  "anachnu lomdot anglit gam bebayt vegam beulpan, veaten?",
  "ani beuniversita o bebayt?",
  "lean hen veaten baot?",
  "meayn morim lemuzika baim lesham?",
  "ma imot lomdot birchov Sverdlov?",
  "lean hu ba meakademja?",
  "anachnu lomdot anglit umuzika, vehi?",
  "meayn aba ba lirchov Komsomolskaja?",
  "anachnu ovdot im aten, veat?",
  "ma morot lomdot beakademja leanglit?",
  "talmidim baim merechov o mibayt?",
  "ma morot leanglit lomdot?",
  "lean hi baa meuniversita?",
  "ma talmid lomed bebayt?",
  "anachnu vehem ovdim im hen?",
  "lean more ba misham?",
  "mi ba meakademja?",
  "meayn hu ba lirchov?",
  "morot veimot beakademja o bebayt?",
  "more oved im ani beakademja o beulpan?",
  "lean hu ba merechov Sverdlov?",
  "meayn morim vetalmidot baim habayta?",
  "aba ba lirchov o habayta?",
  "lean more leivrit ba?",
  "talmidot umorot baot mikan o meuniversita?",
  "ani achshav oved im mora gam bebayt vegam beakademja leanglit, vehu?",
  "more ba habayta meuniversita o misham?",
  "hem talmidim o abim?",
  "mi lomedet birchov?",
  "anachnu achshav baot mibayt, veata?",
  "mi lomedet rusit veanglit im atem veanachnu beuniversita?",
  "atem gam talmidim vegam morim?",
  "lean ani ba meuniversita?",
  "meayn anachnu veatem baim?",
  "mi gara beakademja?",
  "morim baim meuniversita habayta, veatem?",
  "more ba merechov habayta o leulpan?",
  "eyfo at talmida?",
];