// The questions here are pre-generated.
// See the Python script generate_data.py for details.
let questions = [
  "more ba mipo o merechov Sverdlov?",
  "ima baa lepo o lesham?",
  "ata lo more leanglit, vehi?",
  "ma more lomed beulpan im ani?",
  "ima baa merechov leulpan o lepo?",
  "mora leivrit baa mipo o merechov?",
  "ani ba mipo o mibayt?",
  "aba ba meakademja habayta o lekan?",
  "mora lemuzika baa misham lekan, veata?",
  "more lomed ivrit im aba?",
  "hu ba lirchov Komsomolskaja o lesham?",
  "at lomedet anglit, vehu?",
  "hi achshav baa habayta mikan, veata?",
  "ani talmid o aba?",
  "more lomed anglit veivrit, vehi?",
  "meayn hu ba leakademja lemuzika?",
  "more ba meulpan lekan o lirchov?",
  "at baa meakademja leivrit lekan o leulpan?",
  "talmida achshav baa misham, vehi?",
  "ma more lomed bebayt im ima?",
  "ani achshav ba misham, veat?",
  "more lerusit ba lepo misham?",
  "ani lomed, veata?",
  "ani gar beulpan o beakademja leivrit?",
  "ima baa lesham o lirchov?",
  "mora baa mibayt lepo o lirchov?",
  "aba lomed ivrit, vehi?",
  "at achshav baa mikan, vehu?",
  "ma talmid lomed beakademja im ani?",
  "ani lo mora lerusit?",
  "hu ba meakademja habayta o lekan?",
  "lean ata ba meulpan?",
  "talmid gar beulpan o beuniversita?",
  "ani baa lepo o leulpan?",
  "ma more lomed beuniversita im hu?",
  "more leanglit ba meulpan o merechov?",
  "ma more lomed bebayt im talmid?",
  "hi mora leanglit o ima?",
  "ata aba o more lemuzika?",
  "aba lomed rusit?",
  "ani gam aba vegam talmid?",
  "hi gara gam beulpan vegam beuniversita?",
  "more lerusit ba misham lirchov o habayta?",
  "hi gara bebayt o beulpan?",
  "talmid ba merechov o misham?",
  "at lomedet ivrit?",
  "ani baa lirchov meulpan o mipo?",
  "hu lomed anglit im ima, veat?",
  "ani ba lekan, vehi?",
  "talmida lomedet gam rusit vegam ivrit?",
  "eyfo hi more leivrit?",
  "ima baa leuniversita mibayt o misham?",
  "mi lomed gam ivrit vegam anglit beulpan?",
  "more leivrit ba lekan o lesham?",
  "at baa habayta mikan o misham?",
  "lean hu ba merechov Sverdlov?",
  "yesh mora leanglit beulpan?",
  "ata gar gam beuniversita vegam bebayt?",
  "ani lomedet ivrit verusit, vehu?",
  "ani achshav baa mipo, vehi?",
  "ata ba merechov habayta o lekan?",
  "ata lomed rusit veivrit, vehi?",
  "mi ba lesham mipo?",
  "hi lomedet gam rusit vegam anglit, veat?",
  "mi lomed anglit im aba bebayt?",
  "ata ba habayta misham?",
  "hi baa mikan leuniversita o habayta?",
  "more ba merechov Sverdlov lekan o leulpan?",
  "hu ba meulpan habayta o lekan?",
  "ima baa leakademja mibayt o mikan?",
  "more ba habayta mikan o misham?",
  "ata ba lekan misham o mibayt?",
  "meayn talmid ba leakademja leivrit?",
  "hu gam more vegam aba?",
  "at baa lepo o lirchov Komsomolskaja?",
  "ani lomedet ivrit im ima?",
  "more ba leakademja leivrit mibayt o mikan?",
  "ata lomed ivrit umuzika?",
  "ima baa habayta mipo, veata?",
  "ani baa mibayt o misham?",
  "ima baa mikan lesham o leuniversita?",
  "mora lemuzika baa lesham mipo?",
  "ani mora lerusit o ima?",
  "hi baa mipo lesham, vehu?",
  "mi oved im aba birchov Sverdlov?",
  "hu gam talmid vegam more leivrit, vehi?",
  "eyn aba birchov Sverdlov?",
  "more lomed ivrit veanglit im ima, vehi?",
  "talmid ba lepo misham o merechov?",
  "mi oved im aba beulpan?",
  "ani lomedet muzika veanglit im aba, vehu?",
  "more ba lirchov o lesham?",
  "mora baa meakademja habayta o lekan?",
  "ma ima lomedet bebayt im ani?",
  "hi gam mora leivrit, vehu?",
  "hu ba mikan, vehi?",
  "eyfo hu lomed anglit umuzika?",
  "talmid ba mikan lesham o leuniversita?",
  "talmid ba mibayt lekan o habayta?",
  "ani lomed anglit?",
  "aba ba mibayt lirchov o lekan?",
  "hi baa mipo, vehu?",
  "ani more, veat?",
  "ani ba misham habayta, vehi?",
  "ani ba meulpan lesham o lepo?",
  "ma mora lomedet birchov im ima?",
  "mora baa misham leuniversita o lepo?",
  "hu ba leuniversita mipo o misham?",
  "hi ovedet beakademja o bebayt?",
  "hu lomed bebayt o beulpan?",
  "ata ba meuniversita o mikan?",
  "more ba mibayt o mikan?",
  "ima baa mibayt habayta o leuniversita?",
  "ata ba lekan o lirchov?",
  "talmid ba lepo?",
  "eyfo hu lomed gam anglit vegam ivrit?",
  "hi baa lirchov meulpan o misham?",
  "mi ba lesham merechov Sverdlov?",
  "more lemuzika ba mikan o meulpan?",
  "aba ba lirchov Sverdlov o habayta?",
  "talmida baa lepo misham o mibayt?",
  "ani more leivrit?",
  "ma aba lomed?",
  "talmid ba merechov Sverdlov o misham?",
  "more leivrit ba lesham mipo, vehi?",
  "more ba leulpan o lepo?",
  "ani ba lekan, vehu?",
  "ani talmida?",
  "hi baa mipo, veata?",
  "ani ba leulpan meuniversita o mikan?",
  "hi baa misham?",
  "hi baa misham lekan, veat?",
  "ani aba o more lemuzika?",
  "more ba leakademja lerusit mipo o meulpan?",
  "hi baa lesham mikan, veat?",
  "ani baa leuniversita o lekan?",
  "at ovedet beuniversita o bebayt?",
  "ima gara gam bebayt vegam beulpan?",
  "hi lomedet bebayt o beakademja?",
  "ata ba lepo misham o mibayt?",
  "ani ba merechov habayta o leulpan?",
  "ata achshav ba mikan lesham?",
  "mora lerusit baa mipo lirchov o lesham?",
  "eyn more leivrit beulpan?",
  "hi baa lepo merechov o misham?",
  "hu achshav ba misham, veata?",
  "aba achshav ba lesham, vehi?",
  "ani lomed muzika beakademja o bebayt?",
  "ma mora lerusit lomedet?",
  "ata lomed anglit, vehi?",
  "ima baa leakademja meulpan o misham?",
  "ani baa mibayt lesham o lekan?",
  "meayn at baa lesham?",
  "hi gam ima, veat?",
  "hu gam more lerusit vegam talmid, veata?",
  "hu achshav ba mipo?",
  "eyfo ani lomed gam anglit vegam ivrit?",
  "mora lomedet rusit veanglit, vehu?",
  "talmid ba misham?",
  "talmid ba meuniversita lepo o lesham?",
  "ima baa lepo misham o merechov?",
  "at baa meuniversita lepo o lesham?",
  "mora baa mibayt habayta o lesham?",
  "more lomed muzika beakademja o bebayt?",
  "hu lomed ivrit veanglit im aba, veata?",
  "hu ba merechov Komsomolskaja o misham?",
  "ani ba leakademja leanglit misham o mibayt?",
  "ani lomed rusit umuzika beulpan o bebayt?",
  "mora leivrit baa misham lepo, veata?",
  "hu gar bebayt o beakademja leanglit?",
  "hi lo mora?",
  "mora lemuzika baa lesham o leulpan?",
  "meayn talmid ba leuniversita?",
  "ma mora lerusit lomedet beakademja leivrit?",
  "ani lo more, veata?",
  "more lomed ivrit umuzika?",
  "ani ba meulpan lekan o habayta?",
  "ma more lerusit lomed im hu?",
  "ani lomed gam muzika vegam anglit?",
  "mora lemuzika baa habayta mikan?",
  "ani baa mibayt o meulpan?",
  "ata ba meulpan o misham?",
  "more lerusit lomed, vehi?",
  "more lemuzika ba merechov o mibayt?",
  "eyfo ata lomed ivrit veanglit?",
  "ani ovedet beulpan o beuniversita?",
  "aba lomed rusit umuzika, veat?",
  "mora baa habayta mipo, veata?",
  "at baa lepo o lesham?",
  "ani gam mora lemuzika vegam ima?",
  "ani gam mora lemuzika, vehu?",
  "talmid ba merechov lesham o leulpan?",
  "at lo ima, vehi?",
  "ima lomedet beakademja lerusit o beulpan?",
  "hi baa habayta, veat?",
  "ma more leivrit lomed beulpan im hi?",
  "hu ba mikan habayta, vehi?",
  "ata achshav ba mipo, veat?",
  "hi baa merechov o mibayt?",
  "hi mora, veata?",
  "mi ba habayta merechov?",
  "hi lomedet muzika, veata?",
  "ma talmid lomed im mora?",
  "hu lomed gam muzika vegam ivrit?",
  "more lomed gam ivrit vegam anglit?",
  "ani ba leakademja misham o mipo?",
  "more leivrit ba misham leulpan o lepo?",
  "ata ba leulpan merechov o misham?",
  "ima baa mikan leuniversita o leulpan?",
  "mora leanglit baa mibayt lesham o habayta?",
  "ima beuniversita o beakademja?",
  "hi baa misham lekan?",
  "ata lomed gam muzika vegam anglit im aba?",
  "mora beulpan o beakademja?",
  "ata ba leakademja leanglit meulpan o mikan?",
  "hi lomedet rusit im ima, veata?",
  "ani gam more leanglit, veat?",
  "ani lomed rusit umuzika?",
  "eyfo hi more leanglit?",
  "yesh more lemuzika bebayt?",
  "ani ba habayta mikan o mibayt?",
  "ani baa leakademja meulpan o meuniversita?",
  "more lerusit ba habayta o leuniversita?",
  "ani lomedet ivrit, vehu?",
  "ani more lemuzika?",
  "hu achshav ba lesham mipo, veata?",
  "ani lomed ivrit verusit im ima, veat?",
  "eyfo hu lomed muzika veivrit?",
  "ma more leanglit lomed im aba?",
  "ani ba misham lekan?",
  "ma ima lomedet birchov im more leivrit?",
  "mi lomed rusit beulpan?",
  "mora ovedet?",
  "ata ba habayta o lesham?",
  "ani lomed rusit umuzika, vehu?",
  "mora baa mipo, vehu?",
  "more ba meulpan lirchov o lesham?",
  "ani baa habayta, vehu?",
  "talmid lomed rusit beulpan o beakademja?",
  "ani lomed anglit im ima, veat?",
  "hi baa lepo misham o meulpan?",
  "mora leivrit lomedet rusit, veat?",
  "at baa leakademja leivrit misham o mipo?",
  "mi ba lirchov Komsomolskaja?",
  "ata oved im ima, veat?",
  "ata achshav ba mipo habayta, vehi?",
  "ima lomedet rusit im aba, vehu?",
  "talmida baa lepo meuniversita o mibayt?",
  "more lemuzika ba lesham, veat?",
  "mora lerusit beakademja o bebayt?",
  "aba ba meuniversita lesham o lepo?",
  "more lerusit ba mikan habayta o leulpan?",
  "mora lomedet muzika im ima?",
  "hu gam aba vegam more?",
  "talmid ba misham o mipo?",
  "eyfo at lomedet gam ivrit vegam muzika?",
  "hi gam ima vegam mora lemuzika?",
  "talmid ba meakademja lepo o leulpan?",
  "ani baa leakademja mikan o mibayt?",
  "ani mora o talmida?",
  "ima baa habayta merechov Sverdlov o mikan?",
  "hu ba mipo habayta o leuniversita?",
  "mora baa meulpan o merechov?",
  "more leanglit ba misham habayta, vehi?",
  "ata lomed ivrit im aba, veat?",
  "ani achshav baa lekan misham?",
  "ata lo talmid?",
  "ata lomed muzika?",
  "talmida lomedet ivrit?",
  "at baa lekan misham o merechov?",
  "mora lemuzika baa lesham, vehi?",
  "ani lomed rusit veanglit, veat?",
  "aba ba mikan habayta o lesham?",
  "mora lomedet anglit im ima, vehi?",
  "ma talmida lomedet birchov im hi?",
  "ani lomed rusit im aba, veat?",
  "ima baa lirchov mibayt o misham?",
  "more leivrit ba habayta mibayt o mipo?",
  "talmida beuniversita o bebayt?",
  "ima baa lepo o habayta?",
  "aba ba leulpan merechov o misham?",
  "ata lomed gam ivrit vegam muzika im aba?",
  "ima lomedet ivrit verusit?",
  "hu gam more leanglit, veata?",
  "hu gam talmid vegam more?",
  "hu lomed ivrit verusit im ima, veat?",
  "mi ba leulpan mikan?",
  "mi ba misham leulpan?",
  "at mora, vehi?",
  "at achshav baa habayta mipo, vehi?",
  "ima baa mikan lesham?",
  "hu achshav ba mikan lesham?",
  "hi ima, veat?",
  "ima baa meakademja leivrit leulpan o lepo?",
  "hu ba meulpan leuniversita o lekan?",
  "ima beakademja o beulpan?",
  "mi ba merechov Komsomolskaja leulpan?",
  "more leanglit lomed rusit, vehi?",
  "more lemuzika ba leulpan misham o mibayt?",
  "aba gar beulpan o bebayt?",
  "hi lo mora leivrit, vehu?",
  "ani gara bebayt o beulpan?",
  "aba ba meakademja lerusit lekan o habayta?",
  "ima achshav baa lepo, vehi?",
  "ima baa leulpan mipo o misham?",
  "mi baa mibayt leulpan?",
  "ani ovedet, vehi?",
  "mora leivrit baa lesham mipo, veata?",
  "mi ba merechov Sverdlov habayta?",
  "ani gam more vegam aba?",
  "ani ovedet im ima, vehi?",
  "hi baa lirchov misham o mikan?",
  "more lerusit lomed ivrit im aba, vehu?",
  "ani ba misham o merechov?",
  "ani ba mipo, vehu?",
  "ani lomedet anglit verusit?",
  "ani mora?",
  "ata ba meulpan lekan o leuniversita?",
  "aba ba lirchov o lesham?",
  "ata achshav ba lepo misham, vehu?",
  "at baa mipo lirchov o leuniversita?",
  "ani ba mikan o merechov?",
  "ima lomedet anglit veivrit?",
  "mi ba leuniversita mipo?",
  "ani lomedet rusit im aba, vehu?",
  "eyfo ani lomed muzika veivrit?",
  "eyfo aba lomed anglit?",
  "ata oved im aba?",
  "aba lomed muzika veivrit?",
  "eyfo at lomedet muzika veanglit?",
  "more lemuzika ba habayta misham?",
  "hu ba habayta mibayt o merechov?",
  "lean hi baa mibayt?",
  "mora lomedet beulpan o bebayt?",
  "at baa misham o meulpan?",
  "ata aba, vehi?",
  "ata more leivrit o talmid?",
  "hi baa merechov Sverdlov habayta o lekan?",
  "mi ba merechov Komsomolskaja?",
  "ata ba meakademja lesham o lirchov?",
  "ani ba lekan meuniversita o misham?",
  "at baa mikan lesham, veata?",
  "at baa habayta mipo o mibayt?",
  "aba lomed muzika beuniversita o beulpan?",
  "mora lerusit baa mikan habayta, vehu?",
  "mi oved bebayt?",
  "hi achshav baa mipo habayta?",
  "more lerusit ba lekan misham, veata?",
  "mi ba lirchov Sverdlov?",
  "mora lemuzika lomedet ivrit im aba?",
  "ani more leivrit o talmid?",
  "at lomedet anglit veivrit?",
  "ani achshav baa misham lekan, vehu?",
  "talmid ba lekan o lesham?",
  "ani achshav baa lekan misham, veata?",
  "ata lo more, veat?",
  "talmid ba mikan, veata?",
  "more gar bebayt o beakademja leanglit?",
  "ma mora lomedet birchov im ani?",
  "ma talmida lomedet beuniversita im hi?",
  "eyfo more leivrit lomed rusit?",
  "more leivrit lomed, veata?",
  "more ba lekan, vehu?",
  "talmida ovedet, vehu?",
  "ima baa leakademja mikan o mibayt?",
  "at gam mora lemuzika, veata?",
  "talmid ba merechov Sverdlov o mipo?",
  "ima baa habayta, vehi?",
  "ma ima lomedet beakademja im aba?",
  "more ba lepo misham o mibayt?",
  "ima baa meuniversita lekan o lesham?",
  "ani gam more lemuzika?",
  "ani baa misham lepo o habayta?",
  "talmida lomedet rusit im aba, veata?",
  "ani lomed muzika im aba, veat?",
  "ani oved im aba, vehi?",
  "hi lomedet ivrit umuzika, veat?",
  "aba ba misham lekan?",
  "hi baa mikan habayta, veata?",
  "more lerusit ba mikan o mibayt?",
  "hi baa mibayt lirchov o lepo?",
  "ani baa habayta misham o mikan?",
  "ani baa mibayt leulpan o lekan?",
  "more ba misham, veata?",
  "ani baa lekan, veat?",
  "ima baa lekan meuniversita o meulpan?",
  "mi oved beakademja?",
  "hi baa mibayt o meulpan?",
  "more lerusit ba lesham mikan?",
  "ata ba mibayt o meuniversita?",
  "ata ba lekan o leuniversita?",
  "ani ba leulpan merechov o misham?",
  "talmid lomed muzika im aba, vehu?",
  "more lemuzika ba meuniversita o mipo?",
  "hu beakademja leanglit o beulpan?",
  "ani ba lekan o lirchov Sverdlov?",
  "mora leanglit lomedet?",
  "hu bebayt o beuniversita?",
  "talmida baa lirchov Sverdlov misham o mipo?",
  "hi baa mipo o mibayt?",
  "ani gam ima, veat?",
  "mora baa lepo, veat?",
  "more lerusit ba merechov leulpan o lekan?",
  "lean at baa meakademja leanglit?",
  "hi achshav baa mikan, vehu?",
  "hu lomed muzika?",
  "more lomed anglit umuzika im aba, veata?",
  "ima lomedet beakademja o beuniversita?",
  "hu lomed anglit umuzika im aba, vehi?",
  "ata oved, vehi?",
  "eyfo more lerusit oved?",
  "aba ba merechov Sverdlov leulpan o lepo?",
  "ani baa merechov o mikan?",
  "ima baa mipo leuniversita o leulpan?",
  "ima baa lepo o leuniversita?",
  "mora baa habayta mipo o mibayt?",
  "more lerusit ba misham, veat?",
  "ma aba lomed beulpan im mora?",
  "ani ba lirchov mibayt o mipo?",
  "mora leivrit beakademja o beulpan?",
  "lean ani ba meulpan?",
  "ma mora lomedet beulpan im at?",
  "hi achshav baa mikan, veata?",
  "mora lemuzika lomedet, veat?",
  "talmid ba misham habayta o lirchov?",
  "hu ba mikan leulpan o lirchov?",
  "ima baa mipo, veata?",
  "mora baa misham leuniversita o habayta?",
  "ani baa meulpan o misham?",
  "hu ba leakademja misham o meuniversita?",
  "mora achshav baa lepo, veat?",
  "hi gam mora lerusit, vehu?",
  "mora baa lirchov mikan o meulpan?",
  "mora leanglit baa lekan o lesham?",
  "ani mora leivrit o talmida?",
  "mora baa mipo leulpan o lirchov?",
  "hi baa meuniversita lesham o lekan?",
  "at baa meulpan lirchov o leuniversita?",
  "more ba merechov lekan o habayta?",
  "hu ba lirchov misham o mibayt?",
  "at baa habayta, vehu?",
  "hu ba mikan habayta o leulpan?",
  "ani ba habayta meuniversita o mibayt?",
  "ma talmida lomedet beulpan im at?",
  "ani baa mikan o merechov?",
  "more leanglit ba habayta, vehu?",
  "ani ba mibayt leulpan o lesham?",
  "ani lomed gam ivrit vegam rusit?",
  "ata lomed gam muzika vegam ivrit, vehu?",
  "mora lerusit baa misham lekan?",
  "mora leanglit baa mipo habayta, vehi?",
  "mi gar birchov Komsomolskaja?",
  "mora baa leulpan mibayt o misham?",
  "ani baa merechov o mipo?",
  "ani baa merechov lesham o leulpan?",
  "talmida baa mikan habayta?",
  "hi achshav baa misham, veat?",
  "meayn more leanglit ba lepo?",
  "ata ba merechov o meulpan?",
  "hu ba lekan o leulpan?",
  "mora lerusit baa leakademja mikan o mibayt?",
  "talmid lomed ivrit?",
  "ma talmid lomed beulpan im aba?",
  "talmid ba merechov lesham o lepo?",
  "lean ani baa merechov?",
  "talmida lomedet beakademja o beulpan?",
  "more ba meakademja leuniversita o habayta?",
  "ata ba lesham mipo?",
  "at baa meakademja lepo o leuniversita?",
  "at beulpan o beakademja leanglit?",
  "hi baa mipo o merechov?",
  "mora baa lekan merechov o meulpan?",
  "mora lemuzika lomedet ivrit verusit?",
  "ma talmida lomedet bebayt im ima?",
  "talmida baa merechov Sverdlov o mikan?",
  "mora lomedet, vehi?",
  "mi baa lesham merechov?",
  "ata lomed rusit, vehi?",
  "aba ba habayta meulpan o misham?",
  "eyfo hi lomedet gam muzika vegam rusit?",
  "mi ba misham?",
  "meayn at baa leulpan?",
  "at lo mora lerusit, vehi?",
  "ani lomed muzika, veata?",
  "mora lomedet muzika veivrit?",
  "more gar beakademja o bebayt?",
  "hu talmid?",
  "hi baa misham habayta?",
  "more ba meulpan lepo o habayta?",
  "mi baa lirchov?",
  "mi gara beulpan?",
  "eyn universita rechov?",
  "aba ba lesham o lirchov Komsomolskaja?",
  "at gam ima, vehu?",
  "at lomedet muzika im ima, vehi?",
  "aba lomed rusit, vehi?",
  "lean ani baa meulpan?",
  "ma mora lomedet im ima?",
  "meayn talmida baa lepo?",
  "more leanglit ba lirchov o lekan?",
  "hu more lerusit, veat?",
  "hu ba lekan o lirchov?",
  "ma mora lomedet birchov Sverdlov im hu?",
  "talmida baa leakademja mikan o misham?",
  "hu lomed rusit im ima?",
  "hi baa lekan o leulpan?",
  "ata ba misham lepo?",
  "eyfo at lomedet ivrit veanglit?",
  "mi lomed anglit verusit beulpan?",
  "hu ba habayta merechov o mibayt?",
  "aba lomed rusit, veat?",
  "ani gam talmida vegam ima, vehu?",
  "ani oved, vehi?",
  "mora leanglit baa leuniversita o lirchov?",
  "more ba lekan meulpan o mibayt?",
  "aba ba lesham mipo, veata?",
  "mora baa leulpan o leuniversita?",
  "talmida achshav baa misham lepo?",
  "mi ba lekan misham?",
  "hi baa lesham, veat?",
  "eyn aba beulpan?",
  "hi achshav baa mikan lesham?",
  "ani more lerusit, veat?",
  "more ba habayta misham, vehu?",
  "ani more leanglit, veata?",
  "more lerusit ba lepo, vehu?",
  "ani mora leanglit, vehi?",
  "aba gar beulpan o beuniversita?",
  "ima baa leuniversita meulpan o merechov?",
  "ani baa leakademja mibayt o mikan?",
  "lean more lemuzika ba mikan?",
  "mora lemuzika baa mikan o misham?",
  "ani baa meuniversita habayta o lekan?",
  "mora lerusit gara beulpan o beakademja?",
  "talmid oved im aba, vehi?",
  "mora baa meakademja lepo o habayta?",
  "ani ba meulpan habayta o lepo?",
  "hi baa meakademja habayta o lirchov?",
  "mora leivrit baa meulpan o misham?",
  "eyfo ata more lemuzika?",
  "aba beuniversita o bebayt?",
  "ani lomed ivrit, vehi?",
  "mora lemuzika achshav baa habayta, vehu?",
  "ata ba lepo, veat?",
  "ima baa meakademja lesham o lepo?",
  "ani ba leuniversita merechov o mikan?",
  "hu lomed ivrit verusit?",
  "more ba misham?",
  "hi lomedet anglit veivrit?",
  "at baa merechov Sverdlov o misham?",
  "aba ba misham o meulpan?",
  "ata more lerusit o talmid?",
  "hu ba misham lepo?",
  "hi baa habayta mipo o mibayt?",
  "hu talmid, veata?",
  "mi oved im aba birchov Komsomolskaja?",
  "mora leanglit baa mibayt leulpan o habayta?",
  "hi achshav baa mipo, vehu?",
  "ata lomed anglit im ima, vehi?",
  "ata ba lesham mipo, vehi?",
  "meayn mora lerusit baa leuniversita?",
  "ani ba habayta o lirchov?",
  "ani talmid o more?",
  "ata lomed muzika verusit?",
  "ma mora lomedet bebayt im aba?",
  "aba lomed rusit beuniversita o beulpan?",
  "mora lomedet ivrit, vehi?",
  "more lemuzika ba lesham mikan?",
  "ma ima lomedet beulpan?",
  "ani gam talmid?",
  "ma mora lerusit lomedet im ima?",
  "hi baa meakademja lesham o lekan?",
  "ata lo more leivrit?",
  "more lemuzika lomed rusit veanglit im aba?",
  "hi baa misham, vehu?",
  "at baa mibayt o merechov Komsomolskaja?",
  "ani baa leakademja mipo o meulpan?",
  "at baa habayta o lepo?",
  "ima baa merechov Sverdlov o mikan?",
  "ani lomed rusit gam bebayt vegam beulpan?",
  "ima baa misham, veat?",
  "mora leivrit bebayt o beulpan?",
  "ma aba lomed im more lemuzika?",
  "ani baa lirchov o lepo?",
  "ata ba leuniversita mibayt o mipo?",
  "at baa lesham?",
  "hu talmid o more leanglit?",
  "hu bebayt o beulpan?",
  "at baa mikan lesham, vehi?",
  "ani achshav ba lepo, veat?",
  "hu oved im ima?",
  "mora baa leulpan merechov o misham?",
  "more leanglit ba lepo merechov o meulpan?",
  "talmida baa leakademja mikan o mibayt?",
  "talmida baa lirchov o leulpan?",
  "ma talmid lomed birchov im talmida?",
  "at baa meakademja lerusit leulpan o lekan?",
  "ata gam more leanglit vegam aba, veat?",
  "hi baa meulpan o mikan?",
  "more lemuzika lomed ivrit veanglit, vehi?",
  "more achshav ba habayta mikan?",
  "at lomedet ivrit veanglit?",
  "mora ovedet im ima, veata?",
  "aba lomed gam anglit vegam ivrit, vehi?",
  "more ba lepo misham?",
  "hu ba misham?",
  "eyfo hi lomedet?",
  "aba ba lesham?",
  "aba ba lepo o lirchov?",
  "aba lomed rusit umuzika, vehu?",
  "mora lemuzika baa lepo misham, vehu?",
  "ani ba lekan merechov o meuniversita?",
  "aba achshav ba lepo, veat?",
  "ima baa mibayt lirchov o lekan?",
  "ani baa leakademja mibayt o misham?",
  "more lerusit oved im ima, veat?",
  "hi baa lesham mibayt o meulpan?",
  "ani lomedet gam rusit vegam anglit?",
  "hu lomed beulpan o beakademja?",
  "ata ba meuniversita o merechov?",
  "ma ima lomedet im talmid?",
  "ani ba mipo habayta, vehi?",
  "at gam ima?",
  "aba achshav ba mikan lesham, vehi?",
  "hu lomed anglit umuzika?",
  "ata ba meakademja leanglit habayta o lepo?",
  "hu ba lesham, vehi?",
  "ani baa misham leuniversita o lepo?",
  "more leivrit oved beulpan o bebayt?",
  "mora ovedet im aba, vehi?",
  "ima bebayt o beakademja leivrit?",
  "meayn ima baa lesham?",
  "ata ba misham leulpan o lepo?",
  "ata ba lesham meulpan o mipo?",
  "ata lomed beuniversita o bebayt?",
  "mora lerusit baa leulpan o habayta?",
  "ata ba lepo mibayt o meulpan?",
  "eyfo ata lomed?",
  "talmida baa lesham meuniversita o mipo?",
  "ma talmid lomed beakademja im hu?",
  "more leivrit ba habayta, vehu?",
  "mora lerusit lomedet anglit, vehi?",
  "more lerusit lomed, veat?",
  "at gam talmida, vehu?",
  "aba lomed ivrit?",
  "aba ba meulpan o mikan?",
  "talmid ba leulpan o lesham?",
  "ani ba mipo, veat?",
  "at lomedet muzika veivrit?",
  "hi baa merechov o meulpan?",
  "mi ba lesham meuniversita?",
  "talmid ba mikan o misham?",
  "ma more lemuzika lomed im ima?",
  "at lo mora lemuzika, vehi?",
  "aba ba meakademja lepo o habayta?",
  "more lerusit beulpan o beakademja?",
  "eyn ima bebayt?",
  "eyn mora leivrit bebayt?",
  "talmid ba leakademja misham o mipo?",
  "ata ba mipo lirchov o habayta?",
  "mora baa meakademja lekan o habayta?",
  "talmid lomed anglit, veat?",
  "more lomed ivrit umuzika im aba?",
  "hu ba misham habayta, vehi?",
  "mora baa leulpan mipo o mibayt?",
  "mora baa mikan o mibayt?",
  "aba ba lekan misham, veata?",
  "talmid ba mipo lesham?",
  "talmid oved im aba, veat?",
  "more lomed ivrit veanglit, vehu?",
  "ima baa lepo merechov o mibayt?",
  "hu ba merechov habayta o lepo?",
  "ma talmida lomedet bebayt im ata?",
  "ani lomedet rusit umuzika im ima?",
  "more ba lirchov o lekan?",
  "more ba lekan, vehi?",
  "talmid ba leuniversita misham o mibayt?",
  "at lomedet rusit beulpan o beakademja?",
  "mi lomedet beakademja leivrit?",
  "more leanglit lomed muzika im ima?",
  "ata ba misham lirchov o habayta?",
  "hi gam mora vegam ima, vehu?",
  "more ba mikan leuniversita o lesham?",
  "talmida baa merechov leulpan o lepo?",
  "ma more lemuzika lomed im ani?",
  "ma more lomed im ima?",
  "more ba meuniversita lekan o lirchov?",
  "talmida baa lepo misham?",
  "ima baa mikan o misham?",
  "ani oved im ima?",
  "ani gam mora leanglit?",
  "ima baa mikan, vehu?",
  "eyn more lerusit bebayt?",
  "hu ba leuniversita misham o meulpan?",
  "hi baa leuniversita mipo o mibayt?",
  "hi gara beulpan o beakademja leanglit?",
  "ani lomed ivrit, vehu?",
  "ima baa habayta, veata?",
  "talmid ba habayta, veat?",
  "aba ba habayta merechov o mipo?",
  "more lomed muzika im ima, veat?",
  "more lerusit lomed ivrit im aba?",
  "aba lomed ivrit veanglit, vehu?",
  "ata ba habayta mikan, veat?",
  "ata lomed muzika veivrit, vehu?",
  "meayn more leanglit ba?",
  "mora lomedet muzika, veata?",
  "yesh talmid bebayt?",
  "more leanglit ba leulpan o lesham?",
  "meayn ani ba leakademja lemuzika?",
  "ata lomed muzika veanglit im aba?",
  "more lerusit achshav ba mipo, vehu?",
  "mi lomedet anglit umuzika beakademja?",
  "more ba mipo o meulpan?",
  "ani ba mipo lesham, veata?",
  "lean ani baa meakademja lerusit?",
  "hi lomedet rusit veivrit?",
  "more ba mipo lesham?",
  "hu ba lekan o lesham?",
  "at beakademja leivrit o bebayt?",
  "hu gam aba?",
  "ani lomedet bebayt o beakademja?",
  "meayn ani baa leakademja?",
  "talmida baa lesham merechov o mikan?",
  "lean ani baa meakademja?",
  "lean mora lerusit baa mikan?",
  "mi oved im aba beakademja lerusit?",
  "ima baa mipo habayta, vehi?",
  "ani lomed muzika, vehu?",
  "aba ba misham leulpan o lepo?",
  "mora lemuzika baa mipo habayta?",
  "ma more lerusit lomed beakademja im at?",
  "ani lomed ivrit umuzika im ima?",
  "ani baa lesham mikan o meulpan?",
  "ani baa mibayt lesham o habayta?",
  "ani baa misham o mikan?",
  "mi lomedet muzika veanglit beulpan?",
  "talmida baa lesham mipo o merechov?",
  "hi lo mora lemuzika, veat?",
  "mora lerusit baa mikan o meulpan?",
  "ani ba lesham?",
  "ani ba mikan lesham, vehi?",
  "hi mora leanglit, veat?",
  "hu gam aba, veat?",
  "aba ba meuniversita habayta o lepo?",
  "ma more leivrit lomed beakademja im ima?",
  "ani ovedet, veat?",
  "talmid oved im ima, vehi?",
  "mi baa meuniversita?",
  "ata ba lekan misham o merechov?",
  "talmid ba merechov leulpan o habayta?",
  "mi gara beakademja lerusit?",
  "talmid lomed rusit, veat?",
  "ima lomedet anglit im aba, vehi?",
  "hu achshav ba lepo misham?",
  "talmid ba mibayt lesham o leulpan?",
  "mi oved im ima beulpan?",
  "hu gam talmid, vehi?",
  "ata ba mipo leuniversita o leulpan?",
  "mora lomedet?",
  "mi ba merechov leuniversita?",
  "hi lomedet, veat?",
  "aba ba habayta mipo?",
  "ima baa lirchov mipo o misham?",
  "mi baa lepo misham?",
  "ani ba misham o mibayt?",
  "more ba meulpan o misham?",
  "mora lemuzika baa meulpan o mibayt?",
  "hu ba lesham mikan?",
  "meayn hu ba lepo?",
  "talmida baa lepo o habayta?",
  "hu ba leuniversita merechov o mikan?",
  "lean mora baa merechov?",
  "hu ba habayta merechov o meulpan?",
  "ata more lerusit, vehi?",
  "more ba mipo leulpan o lesham?",
  "ima baa misham, veata?",
  "at baa merechov lekan o leulpan?",
  "hu beakademja o beulpan?",
  "ani achshav ba misham habayta?",
  "mora baa habayta, veat?",
  "ima baa misham leulpan o lirchov?",
  "at baa lepo?",
  "hi baa misham lepo o leulpan?",
  "ani ba meuniversita lepo o habayta?",
  "ani lo mora leanglit?",
  "mora baa lepo o lirchov Sverdlov?",
  "at achshav baa lesham?",
  "ani ba mibayt leulpan o lekan?",
  "aba oved im ima?",
  "more lerusit ba mibayt lirchov o lekan?",
  "hi baa lekan misham o merechov?",
  "ani ba habayta o leulpan?",
  "ani lomed beulpan o beuniversita?",
  "hi baa merechov lepo o leuniversita?",
  "lean mora lemuzika baa mipo?",
  "hi mora lerusit, veata?",
  "mora baa lepo o lirchov?",
  "talmida bebayt o beulpan?",
  "aba achshav ba lepo?",
  "ani baa lirchov o leulpan?",
  "mora ovedet im aba, veat?",
  "mora leivrit baa lepo misham, vehu?",
  "hu achshav ba mipo, veata?",
  "talmid lomed beulpan o beuniversita?",
  "mi gar birchov Sverdlov?",
  "mora lerusit achshav baa mipo, vehu?",
  "ata lomed ivrit?",
  "mi baa leuniversita mipo?",
  "hu ba habayta mipo?",
  "mora leanglit baa lirchov misham o mibayt?",
  "ma mora lerusit lomedet im more lemuzika?",
  "mora baa lesham mipo, vehu?",
  "more leivrit ba mipo o meulpan?",
  "ani baa habayta misham, veata?",
  "mi ovedet im ima beakademja lemuzika?",
  "meayn ani baa lekan?",
  "more achshav ba misham?",
  "more lerusit ba misham lepo o leulpan?",
  "ata ba leakademja mibayt o mipo?",
  "at baa misham habayta, veata?",
  "mora baa mikan o meulpan?",
  "ima ovedet im aba, veata?",
  "talmid achshav ba habayta, vehu?",
  "ima lomedet muzika im aba?",
  "mora lemuzika baa mibayt o merechov?",
  "ata ba mikan lesham?",
  "at baa mipo lesham o habayta?",
  "hi gam mora lerusit, veat?",
  "ani ba meakademja habayta o lekan?",
  "ma aba lomed im ani?",
  "ma aba lomed beakademja im talmid?",
  "ani achshav ba lekan?",
  "ata ba misham habayta?",
  "ma more lerusit lomed im talmida?",
  "ima baa meulpan lesham o lepo?",
  "hu lomed anglit veivrit im ima, vehi?",
  "hi baa lesham merechov Sverdlov o mipo?",
  "talmida lomedet muzika im aba, vehu?",
  "hu lomed rusit veivrit, veata?",
  "lean more leivrit ba mikan?",
  "ani baa mipo lesham, veata?",
  "ata ba habayta meulpan o merechov?",
  "hu ba misham, veat?",
  "ani lomedet muzika im ima?",
  "ani baa lesham o lirchov?",
  "at baa mibayt lepo o habayta?",
  "ani lo mora leanglit, vehu?",
  "mora lemuzika baa lesham o leuniversita?",
  "ani more lerusit?",
  "ani ba mibayt o merechov?",
  "mora baa lekan o habayta?",
  "hu achshav ba lesham, veat?",
  "hi lomedet ivrit?",
  "at baa merechov Komsomolskaja o mibayt?",
  "mi lomed anglit verusit im aba beakademja?",
  "hu ba lekan misham, vehi?",
  "more oved, veat?",
  "ata achshav ba lesham mikan, vehu?",
  "meayn more leivrit ba lirchov Sverdlov?",
  "hu ba merechov leulpan o lepo?",
  "hu lomed rusit?",
  "talmid ba mikan leuniversita o leulpan?",
  "mora lomedet muzika verusit im ima, veata?",
  "ani ba mikan lirchov o lesham?",
  "ma talmid lomed im ata?",
  "meayn more lemuzika ba?",
  "ani ba lepo mibayt o merechov?",
  "ani ba lesham meuniversita o merechov?",
  "hi baa mipo lesham?",
  "more ba misham lepo, veata?",
  "ata achshav ba lepo, vehu?",
  "hi baa mikan o mibayt?",
  "ani baa merechov Komsomolskaja o mibayt?",
  "hu ba meuniversita leulpan o lekan?",
  "more ba lepo meuniversita o merechov?",
  "meayn hu ba lekan?",
  "ata ba habayta mikan o meuniversita?",
  "ata ba leuniversita o habayta?",
  "ani lomedet?",
  "at baa lekan?",
  "at lomedet rusit bebayt o beulpan?",
  "more lerusit lomed gam anglit vegam ivrit?",
  "hi baa leuniversita mikan o merechov?",
  "ani beakademja leivrit o beulpan?",
  "ani baa misham o merechov Sverdlov?",
  "hu ba meuniversita lepo o habayta?",
  "ani lomedet muzika veivrit?",
  "at lomedet rusit, vehu?",
  "ani baa lesham mipo, veat?",
  "ani lomedet rusit veanglit?",
  "hu more lemuzika, vehi?",
  "hi lomedet muzika im ima, veat?",
  "ima baa meakademja leulpan o lirchov?",
  "mora lemuzika lomedet anglit im aba?",
  "mi lomed anglit veivrit im ima beulpan?",
  "ma more lomed birchov im talmid?",
  "ani ba leakademja mipo o mibayt?",
  "ani baa mipo lesham o lirchov Sverdlov?",
  "ma talmid lomed beakademja lerusit im hu?",
  "hi lomedet gam muzika vegam rusit im ima?",
  "ata lomed ivrit verusit?",
  "ani lomedet ivrit verusit?",
  "mora leivrit baa misham o merechov?",
  "ani gam mora leanglit vegam talmida, vehu?",
  "more lomed ivrit im ima, vehu?",
  "hu oved, veat?",
  "ma ima lomedet birchov im ani?",
  "talmida lomedet muzika?",
  "more leivrit ba mikan leulpan o lirchov?",
  "mi gara birchov Sverdlov?",
  "aba ba lekan o lirchov?",
  "hi baa lirchov meuniversita o mikan?",
  "at lomedet rusit veanglit, veata?",
  "more lerusit ba misham, vehu?",
  "eyfo hu more?",
  "ani ba misham, veata?",
  "ima beakademja lerusit o beuniversita?",
  "eyfo mora leanglit lomedet rusit umuzika?",
  "at baa misham lirchov o lekan?",
  "hu lomed muzika im ima, veata?",
  "ani ba merechov Sverdlov lekan o habayta?",
  "aba ba mibayt leulpan o lepo?",
  "aba ba lepo misham, vehi?",
  "more lomed muzika im aba, vehu?",
  "meayn ani baa?",
  "hi baa lesham mikan o meulpan?",
  "more lomed rusit umuzika, veat?",
  "ima lomedet rusit, veat?",
  "hu ba meuniversita o mibayt?",
  "aba ba mibayt lepo o lirchov?",
  "hi baa mikan lesham o lirchov?",
  "more lomed gam rusit vegam muzika, veata?",
  "mora leivrit achshav baa misham?",
  "ata gam talmid, veat?",
  "ima baa leulpan o lirchov Sverdlov?",
  "ima achshav baa misham lepo, vehu?",
  "ani ba misham lepo o habayta?",
  "more ba mikan, vehu?",
  "more lerusit ba lirchov Sverdlov o leulpan?",
  "talmid ba misham leulpan o habayta?",
  "aba achshav ba lesham mipo, vehu?",
  "mora lemuzika ovedet im ima, veata?",
  "hu ba mikan?",
  "more ba mipo lesham o lirchov?",
  "hi baa lirchov Sverdlov o lesham?",
  "mi baa mipo habayta?",
  "at gam mora?",
  "lean mora lemuzika baa meuniversita?",
  "talmid ba lepo misham o meulpan?",
  "lean hu ba?",
  "more lomed ivrit verusit?",
  "hu more, vehi?",
  "ani baa mibayt habayta o lirchov?",
  "more lemuzika ba lesham mipo?",
  "more lomed beuniversita o bebayt?",
  "aba achshav ba lekan, veat?",
  "mora baa merechov lekan o lesham?",
  "lean more lemuzika ba meulpan?",
  "hi lomedet muzika veanglit im ima, veata?",
  "mora baa habayta mikan o meuniversita?",
  "hi lomedet ivrit verusit im ima, veata?",
  "hu more leanglit, veata?",
  "lean mora leanglit baa misham?",
  "mi ba lirchov Sverdlov mipo?",
  "hu lomed rusit umuzika im ima?",
  "hi baa mikan habayta o lesham?",
  "eyfo ani more?",
  "hi mora leivrit, veata?",
  "talmid ba mibayt o merechov Sverdlov?",
  "ma mora lomedet?",
  "at lomedet muzika veanglit, vehu?",
  "ani beakademja leivrit o bebayt?",
  "more leanglit achshav ba lepo misham?",
  "eyn more lemuzika beulpan?",
  "ima baa mikan leuniversita o lirchov?",
  "ma mora lemuzika lomedet im more lerusit?",
  "hu more leanglit?",
  "ani gar gam bebayt vegam beulpan?",
  "ata ba merechov lepo o leulpan?",
  "ata ba leakademja mikan o misham?",
  "hi lomedet rusit?",
  "meayn talmida baa habayta?",
  "talmid ba lesham mibayt o merechov?",
  "ma ima lomedet bebayt im more lerusit?",
  "mora lerusit baa lesham merechov o mipo?",
  "ata ba mibayt leulpan o lepo?",
  "hi baa lesham mipo, veata?",
  "mora lomedet muzika verusit im ima?",
  "lean more ba meakademja?",
  "mora lerusit baa lirchov o lepo?",
  "mora leanglit baa leuniversita o habayta?",
  "hi baa mibayt lekan o habayta?",
  "more ba lirchov o habayta?",
  "hi baa meakademja leulpan o habayta?",
  "eyfo aba lomed anglit umuzika?",
  "aba achshav ba mipo lesham?",
  "aba ba mibayt lepo o leuniversita?",
  "hu ba lekan meulpan o misham?",
  "at achshav baa misham?",
  "aba ba mipo leulpan o habayta?",
  "at beulpan o beakademja lemuzika?",
  "eyfo at lomedet anglit umuzika?",
  "talmid lomed anglit, vehu?",
  "ma mora lomedet im hu?",
  "more leanglit ba misham?",
  "hu achshav ba lesham?",
  "ata ba meulpan o mipo?",
  "more achshav ba misham habayta, veata?",
  "ani ba merechov lesham o lepo?",
  "ima baa lesham merechov o mibayt?",
  "at baa habayta mipo, veata?",
  "mora lemuzika baa mipo, veat?",
  "at gam mora leivrit?",
  "ata ba meuniversita lirchov o lesham?",
  "aba ba leulpan mibayt o misham?",
  "ma ima lomedet im more?",
  "ani gar beakademja lerusit o bebayt?",
  "ani achshav ba lesham mipo?",
  "more lomed, veat?",
  "more ba mibayt o mipo?",
  "ani ba habayta misham, vehi?",
  "mora baa mibayt lepo o lesham?",
  "ma ima lomedet bebayt im hu?",
  "ima baa misham lepo, veat?",
  "talmid ba mipo o merechov?",
  "ima lomedet rusit?",
  "more lomed muzika im aba?",
  "talmida baa mikan lesham?",
  "mora leanglit baa habayta, veat?",
  "aba ba merechov lekan o lesham?",
  "more leanglit lomed rusit, veat?",
  "ani achshav ba habayta misham?",
  "ima gara beulpan o beakademja leanglit?",
  "ima lomedet, veat?",
  "mi lomedet anglit veivrit birchov?",
  "ata aba o talmid?",
  "ata lomed ivrit im ima, vehi?",
  "ma mora lemuzika lomedet?",
  "ata gam talmid vegam aba, veat?",
  "hi ima, veata?",
  "talmid lomed rusit im aba, veata?",
  "more ba leulpan mibayt o merechov?",
  "eyfo hu lomed anglit verusit?",
  "at baa lesham mikan, vehi?",
  "ata lomed anglit?",
  "more beulpan o beuniversita?",
  "ima baa mipo habayta?",
  "mora baa lekan mibayt o meulpan?",
  "mi baa mipo leuniversita?",
  "ata ba meulpan o mibayt?",
  "hi lomedet muzika bebayt o beakademja?",
  "aba lomed rusit veivrit im ima, vehi?",
  "ani gam mora, vehu?",
  "aba achshav ba misham lepo, veat?",
  "more lerusit bebayt o beuniversita?",
  "mi baa leulpan merechov?",
  "at baa misham habayta o lirchov?",
  "mora achshav baa mipo, vehu?",
  "mora lerusit achshav baa mipo?",
  "hi lo talmida?",
  "hi gam mora leanglit, veat?",
  "mora lemuzika baa lepo mibayt o merechov?",
  "mora gara beakademja o bebayt?",
  "ani oved beulpan o beakademja?",
  "at baa misham, veata?",
  "hu gam aba, veata?",
  "hi lo mora leivrit, veata?",
  "ata beuniversita o beakademja leanglit?",
  "mora leivrit lomedet rusit, veata?",
  "hu ba mibayt o mipo?",
  "hu gam more?",
  "hi baa habayta misham, veata?",
  "aba ba lepo, veat?",
  "lean talmida baa mikan?",
  "hi achshav baa lepo, vehu?",
  "at beuniversita o bebayt?",
  "ata gam more leanglit?",
  "lean at baa?",
  "meayn hu ba lirchov?",
  "aba ba lirchov o habayta?",
  "at lomedet anglit verusit, vehi?",
  "talmida achshav baa mipo habayta?",
  "ma more leanglit lomed beuniversita?",
  "aba lomed muzika verusit, veat?",
  "more leivrit lomed anglit verusit, veat?",
  "more ba habayta mikan, veat?",
  "ma mora leivrit lomedet im more?",
  "at baa lepo misham, vehi?",
  "aba achshav ba misham habayta, vehi?",
  "ata gam more leivrit?",
  "ma mora lerusit lomedet birchov im hi?",
  "ani ba lepo o lesham?",
  "more lemuzika ba mipo lesham, vehi?",
  "lean mora leanglit baa mibayt?",
  "at baa mibayt lekan o habayta?",
  "ani lo talmid, veata?",
  "ani lo mora?",
  "aba ba lirchov Sverdlov mipo o meulpan?",
  "mi ba lirchov?",
  "at ovedet beulpan o beakademja?",
  "more leivrit ba misham o mibayt?",
  "hu ba merechov Sverdlov o mibayt?",
  "at gam talmida, vehi?",
  "mi gara beuniversita?",
  "at baa meakademja lirchov o lesham?",
  "ani lomedet rusit im ima, vehi?",
  "mora leivrit gara bebayt o beulpan?",
  "mora baa lekan misham o merechov?",
  "ani baa mikan lesham o habayta?",
  "ima baa mikan lirchov o habayta?",
  "lean talmid ba?",
  "more ba lirchov o leulpan?",
  "mora leanglit baa meulpan o mibayt?",
  "ata ba mipo lirchov Sverdlov o leulpan?",
  "mi ba lesham merechov?",
  "more lerusit ba misham habayta, veata?",
  "at achshav baa lepo, veata?",
  "mora baa leuniversita merechov o meulpan?",
  "ani ba mipo leulpan o lesham?",
  "more lomed muzika im aba, veat?",
  "ima baa habayta o leulpan?",
  "ani ba lesham meulpan o mibayt?",
  "more leivrit ba habayta mipo, veat?",
  "more leanglit achshav ba mikan, vehu?",
  "mora leivrit baa mipo lesham?",
  "ma mora lomedet bebayt im ata?",
  "hi baa lesham o lirchov?",
  "hu ba merechov o meuniversita?",
  "at baa lirchov mibayt o meuniversita?",
  "hu lomed muzika im aba, veata?",
  "ata oved bebayt o beulpan?",
  "lean at baa merechov Sverdlov?",
  "more leivrit ba lesham?",
  "ma mora lomedet im ani?",
  "aba ba lekan meulpan o mibayt?",
  "ani gam aba, veat?",
  "ata ba mipo leulpan o lesham?",
  "more lomed ivrit beuniversita o bebayt?",
  "hi baa leakademja mibayt o mipo?",
  "talmida baa mipo?",
  "ma ima lomedet birchov im at?",
  "meayn ima baa leakademja lerusit?",
  "hi baa mipo lesham o habayta?",
  "aba ba lirchov Sverdlov mipo o misham?",
  "at achshav baa lepo?",
  "ani lo mora, veat?",
  "ani baa misham, veat?",
  "hi beakademja o bebayt?",
  "ani gam talmida vegam mora, vehu?",
  "ani lomed anglit veivrit, vehi?",
  "ani ima o mora?",
  "ani achshav ba mikan lesham?",
  "talmid ba mikan leulpan o lesham?",
  "more leanglit ba mikan lirchov o habayta?",
  "hu ba habayta, veat?",
  "talmida baa leulpan mibayt o mipo?",
  "ani baa mikan o misham?",
  "hu ba misham lekan?",
  "more oved beulpan o beakademja?",
  "talmida ovedet gam beulpan vegam bebayt?",
  "ata ba mikan habayta o leulpan?",
  "talmida baa lirchov mibayt o meuniversita?",
  "mi lomedet rusit im ima birchov Sverdlov?",
  "ma mora leivrit lomedet im hi?",
  "hu oved gam bebayt vegam beulpan?",
  "ima baa meulpan lekan o leuniversita?",
  "mora lemuzika baa lesham, vehu?",
  "aba ba lekan o leuniversita?",
  "ma talmid lomed im at?",
  "mora lomedet ivrit verusit im ima?",
  "more leanglit lomed ivrit im aba, vehu?",
  "ata oved?",
  "ani ba mipo lesham, vehu?",
  "ata ba meulpan lirchov o lekan?",
  "at baa mibayt habayta o lepo?",
  "at talmida?",
  "ata ba lirchov o lepo?",
  "at lo mora lerusit, veata?",
  "mi lomedet muzika veivrit beakademja?",
  "mora lemuzika lomedet rusit, vehu?",
  "ma more leivrit lomed beulpan im ima?",
  "ata ba habayta mipo, veat?",
  "hu ba lekan, veata?",
  "ma talmida lomedet bebayt im aba?",
  "eyfo ani lomedet ivrit umuzika?",
  "ani baa leulpan mibayt o mikan?",
  "eyn more leanglit birchov Sverdlov?",
  "eyfo aba lomed ivrit umuzika?",
  "ani lomedet muzika veivrit, vehi?",
  "at mora lerusit?",
  "lean ata ba meuniversita?",
  "more lerusit ba meuniversita o mibayt?",
  "aba oved beakademja o bebayt?",
  "talmida lomedet beuniversita o bebayt?",
  "more lomed anglit umuzika, vehi?",
  "mi lomedet anglit birchov?",
  "hi achshav baa mipo, veat?",
  "mora achshav baa lekan, veata?",
  "talmida lomedet ivrit, vehu?",
  "ani lomedet muzika veanglit im aba?",
  "ani gam aba vegam more, veata?",
  "more ba mipo lesham, veat?",
  "mora leivrit achshav baa misham, vehu?",
  "talmid achshav ba misham lekan, vehu?",
  "at baa habayta mikan o meulpan?",
  "ani achshav ba lepo misham, vehi?",
  "talmid ba mibayt lekan o lesham?",
  "hi baa misham, veat?",
  "hu ba lirchov Sverdlov meulpan o mikan?",
  "ani gam talmida, veat?",
  "more leanglit oved im ima, vehi?",
  "talmida baa meulpan lekan o lirchov?",
  "eyfo ani lomed ivrit?",
  "ma ima lomedet im hi?",
  "ani baa mibayt lirchov o leulpan?",
  "ata lomed ivrit im ima, vehu?",
  "at lomedet muzika veivrit im ima?",
  "ani baa lirchov misham o mipo?",
  "more ba leulpan mipo o meuniversita?",
  "at lomedet muzika veivrit, vehi?",
  "talmida achshav baa misham lekan, veata?",
  "yesh ima bebayt?",
  "mora lomedet muzika im aba, vehi?",
  "mi ba meulpan leuniversita?",
  "ma more leivrit lomed birchov Sverdlov?",
  "eyn more leivrit bebayt?",
  "more leanglit ba merechov o mipo?",
  "aba ba misham leulpan o habayta?",
  "ata lomed rusit veanglit im aba?",
  "hu ba lekan o habayta?",
  "ani lomed anglit verusit?",
  "mora baa mipo habayta o lirchov?",
  "mora achshav baa mikan, veat?",
  "mi lomed ivrit im aba bebayt?",
  "mi oved im ima birchov?",
  "hu ba mikan o misham?",
  "talmid ba misham, vehi?",
  "ani achshav baa mipo habayta, veat?",
  "more leanglit oved, veata?",
  "talmida beakademja lerusit o beulpan?",
  "talmida baa mipo o misham?",
  "aba ba habayta misham, veat?",
  "ani more leivrit o aba?",
  "ata ba mibayt lesham o lirchov?",
  "hu ba leuniversita mibayt o mikan?",
  "more lerusit lomed ivrit im ima?",
  "mi baa lesham mibayt?",
  "ata ba habayta mipo?",
  "aba achshav ba lesham mipo?",
  "talmid achshav ba misham lepo, veat?",
  "hu ba lirchov mipo o mibayt?",
  "mi lomed ivrit beuniversita?",
  "more ba misham lepo?",
  "ma mora lomedet beulpan im more?",
  "aba ba lekan o habayta?",
  "hi baa habayta misham o mikan?",
  "mi baa habayta mipo?",
  "ani baa misham o mipo?",
  "meayn more ba lirchov Sverdlov?",
  "ani lomedet rusit beulpan o bebayt?",
  "at baa mipo lesham?",
  "hi achshav baa habayta mipo, vehu?",
  "at gam mora, vehu?",
  "mora achshav baa lepo, veata?",
  "mi baa leuniversita?",
  "at baa merechov leuniversita o lesham?",
  "mi gar birchov?",
  "hi baa mipo o misham?",
  "hi lomedet ivrit umuzika?",
  "mora achshav baa lekan misham?",
  "at achshav baa misham lepo, vehi?",
  "at baa lesham o leulpan?",
  "ani ba lesham meulpan o mipo?",
  "eyfo ata lomed ivrit verusit?",
  "ima baa lesham o lekan?",
  "hu ba meulpan lirchov o lekan?",
  "hi baa merechov lepo o lesham?",
  "eyfo ani lomed muzika?",
  "at baa lirchov Sverdlov o lekan?",
  "talmid ba meakademja habayta o lekan?",
  "ani baa mipo?",
  "talmid oved?",
  "ima baa lirchov o lesham?",
  "mora leivrit baa misham habayta, vehu?",
  "at baa misham o meuniversita?",
  "ani gam aba vegam more leanglit, vehi?",
  "mora achshav baa lepo misham?",
  "ani ba lesham mipo, veata?",
  "more lerusit ba lesham mikan, vehu?",
  "more leanglit ba meulpan lesham o habayta?",
  "more leanglit ba mikan, vehi?",
  "aba ba meulpan lepo o habayta?",
  "eyfo hi lomedet anglit?",
  "mora leanglit baa meulpan lepo o lesham?",
  "ata achshav ba mipo lesham?",
  "ani baa lesham mipo o merechov Sverdlov?",
  "hi lomedet rusit bebayt o beulpan?",
  "aba lomed anglit beuniversita o bebayt?",
  "at gam ima, vehi?",
  "mora lerusit baa habayta, vehu?",
  "mi lomed rusit veivrit im aba bebayt?",
  "hu ba habayta mibayt o mikan?",
  "hi mora lemuzika o talmida?",
  "yesh talmid beulpan?",
  "mora baa leuniversita o leulpan?",
  "mora leivrit lomedet rusit im aba?",
  "ma aba lomed birchov im more leivrit?",
  "hu ba mipo habayta, veat?",
  "mi baa leuniversita misham?",
  "eyn ulpan rechov?",
  "ani ba leulpan o lirchov Sverdlov?",
  "hu ba lekan merechov o meulpan?",
  "talmid beulpan o beuniversita?",
  "hu ba meuniversita leulpan o habayta?",
  "talmid ba mibayt lesham o lirchov?",
  "eyfo ani lomedet?",
  "yesh more leivrit bebayt?",
  "more lemuzika ba mikan habayta, vehi?",
  "ani ba leakademja mibayt o mikan?",
  "ani baa lekan o lirchov?",
  "mora leivrit baa lepo misham?",
  "ata more leanglit, vehu?",
  "at lo mora leivrit?",
  "ani baa lekan misham o meulpan?",
  "ani gam ima vegam mora leanglit?",
  "ani ba misham lirchov o leulpan?",
  "ata ba meuniversita lesham o leulpan?",
  "ani baa lesham, veat?",
  "more achshav ba habayta misham, vehu?",
  "mora leivrit baa mikan habayta o lesham?",
  "ani lomedet ivrit verusit im aba?",
  "hu gam talmid?",
  "ima lomedet ivrit veanglit im aba?",
  "hi baa leulpan mibayt o merechov?",
  "ani baa mibayt lekan o habayta?",
  "aba ba misham lepo, veat?",
  "more leivrit lomed muzika im ima, veata?",
  "ata ba habayta misham, vehu?",
  "aba oved?",
  "ani lomedet beakademja leivrit o bebayt?",
  "ima lomedet anglit im aba, vehu?",
  "ata lomed anglit verusit, vehi?",
  "ani ba mibayt lepo o habayta?",
  "yesh akademja rechov?",
  "eyfo more gar?",
  "ani lomed anglit verusit, vehi?",
  "aba ba lekan o lirchov Sverdlov?",
  "mi baa merechov Sverdlov lesham?",
  "ata lomed rusit im ima, vehi?",
  "mi lomed ivrit umuzika im ima beakademja?",
  "eyn talmid beuniversita?",
  "more leanglit lomed rusit umuzika?",
  "ani baa mipo habayta o leulpan?",
  "aba ba habayta meulpan o merechov?",
  "ma mora lemuzika lomedet beulpan im ima?",
  "ani baa habayta mikan o merechov?",
  "meayn ata ba leakademja?",
  "talmid ba lirchov mibayt o mipo?",
  "ani ba mipo habayta o leulpan?",
  "aba achshav ba mipo habayta?",
  "mora baa misham lepo o lirchov?",
  "mora baa meulpan lesham o habayta?",
  "more ba mikan o misham?",
  "aba achshav ba habayta misham?",
  "talmid ba lepo, veat?",
  "meayn more ba leulpan?",
  "ata ba lepo meulpan o mibayt?",
  "ani ba misham leuniversita o lekan?",
  "eyfo talmid gar?",
  "ani baa lepo misham o mibayt?",
  "mi lomed ivrit im ima beakademja?",
  "talmida lomedet anglit veivrit, vehi?",
  "more lerusit ba misham?",
  "more leanglit ba meulpan habayta o lesham?",
  "hu lomed muzika im ima?",
  "mora lomedet ivrit, veat?",
  "eyfo more leanglit lomed ivrit verusit?",
  "talmid lomed muzika veanglit im ima?",
  "lean mora leanglit baa meulpan?",
  "ani more leanglit, vehu?",
  "more lemuzika achshav ba habayta mipo?",
  "ima baa lesham meuniversita o merechov?",
  "ma mora leanglit lomedet?",
  "ata ba mikan lirchov o leuniversita?",
  "more ba lekan meulpan o misham?",
  "talmida lomedet anglit veivrit, veata?",
  "at ima o talmida?",
  "more lomed muzika verusit im aba?",
  "more leivrit lomed bebayt o beakademja?",
  "ani ba misham lekan o lirchov Sverdlov?",
  "ani gam more vegam talmid?",
  "ani lomedet muzika verusit?",
  "hi lomedet anglit im aba, vehu?",
  "talmida baa mibayt lekan o lesham?",
  "mora lomedet muzika, vehu?",
  "mora lemuzika lomedet ivrit, vehu?",
  "ma mora lomedet beulpan im talmid?",
  "at baa meakademja habayta o lepo?",
  "mora lerusit ovedet im ima, vehi?",
  "hi baa lepo meulpan o meuniversita?",
  "at baa mibayt o mipo?",
  "more ba mipo, vehi?",
  "mora lomedet ivrit im ima, vehu?",
  "mi lomedet muzika veanglit im aba beulpan?",
  "ani lomedet rusit im ima, vehu?",
  "aba oved, veata?",
  "ima lomedet muzika, vehu?",
  "ani ba mibayt o mipo?",
  "ma mora lemuzika lomedet beakademja?",
  "mora baa leulpan merechov o mibayt?",
  "mi lomed rusit veanglit beulpan?",
  "ata beulpan o beakademja lerusit?",
  "ani achshav ba mipo lesham, veata?",
  "at lomedet gam rusit vegam ivrit?",
  "aba ba lesham, veat?",
  "hi baa merechov lekan o leulpan?",
  "meayn mora baa leulpan?",
  "ma aba lomed beulpan im talmid?",
  "more ba meuniversita lepo o lirchov?",
  "ata ba misham leuniversita o lepo?",
  "aba ba habayta misham?",
  "more leivrit ba lepo o leulpan?",
  "mora lomedet muzika, vehi?",
  "more lerusit ba lesham mipo o meulpan?",
  "aba lomed rusit im ima, veata?",
  "more leanglit ba lekan?",
  "mora achshav baa lekan, veat?",
  "hu ba lepo meuniversita o mibayt?",
  "talmida achshav baa mikan habayta, vehi?",
  "ani lomedet ivrit, veata?",
  "at lomedet rusit umuzika im ima?",
  "talmid achshav ba lesham?",
  "at ovedet, vehi?",
  "more ba mipo o merechov?",
  "ima baa mibayt habayta o lirchov Sverdlov?",
  "hu ba lekan, veat?",
  "hi achshav baa habayta, vehu?",
  "at lomedet rusit veivrit?",
  "ma aba lomed bebayt?",
  "hi lomedet beakademja o bebayt?",
  "more lemuzika ba lepo o habayta?",
  "eyn ima beulpan?",
  "ma mora lomedet beulpan im aba?",
  "ima baa lesham mipo, vehi?",
  "aba achshav ba habayta, veat?",
  "ani gam mora leanglit vegam ima, vehi?",
  "hi lo mora lemuzika?",
  "mora lomedet anglit im aba, vehu?",
  "at baa meulpan lirchov o lesham?",
  "talmid lomed rusit?",
  "hu ba leuniversita misham o mipo?",
  "at baa misham o mibayt?",
  "lean ata ba mibayt?",
  "ma ima lomedet birchov im hi?",
  "at achshav baa misham habayta?",
  "more leivrit ba habayta mikan?",
  "mora leivrit baa mipo habayta?",
  "mora lemuzika baa leulpan mipo o mibayt?",
  "eyfo aba gar?",
  "aba ba mipo lirchov Sverdlov o leulpan?",
  "meayn talmida baa leakademja?",
  "ata lo more leanglit, veat?",
  "ma aba lomed beakademja lerusit?",
  "talmida lomedet anglit, vehi?",
  "ima baa lekan merechov o meuniversita?",
  "talmida ovedet?",
  "hi lo mora lerusit, veata?",
  "aba ba mibayt lekan o habayta?",
  "aba ba mikan leuniversita o lirchov?",
  "hi lomedet ivrit im ima, veat?",
  "more lomed gam muzika vegam ivrit?",
  "at gam mora lerusit, veata?",
  "ima baa misham lekan, veat?",
  "talmid ba mibayt lepo o leuniversita?",
  "mora leanglit baa merechov o misham?",
  "ima baa meulpan lepo o lesham?",
  "talmid lomed anglit umuzika?",
  "more leivrit ba misham habayta, veata?",
  "at baa meuniversita leulpan o habayta?",
  "mora baa meuniversita lekan o lesham?",
  "aba ba lekan?",
  "mi baa meuniversita lepo?",
  "ani baa meulpan lekan o leuniversita?",
  "talmid achshav ba lepo, vehi?",
  "more ba lesham o leulpan?",
  "mi lomed gam anglit vegam ivrit beakademja?",
  "mora baa meakademja lirchov o lepo?",
  "mi ba leuniversita misham?",
  "ani ba lirchov o habayta?",
  "yesh ima birchov?",
  "hi baa meakademja lesham o lepo?",
  "ani lomedet rusit veivrit, veat?",
  "ani lomedet muzika, vehi?",
  "ma ima lomedet im more leivrit?",
  "ata gam talmid?",
  "hi baa habayta mikan, vehu?",
  "mora baa lesham merechov o mipo?",
  "talmid lomed gam ivrit vegam muzika?",
  "ani lomedet muzika im ima, vehu?",
  "more ba mikan lesham o leuniversita?",
  "ani ba habayta misham, veata?",
  "at baa habayta meulpan o mipo?",
  "hi baa mikan leuniversita o lesham?",
  "ani gam aba vegam talmid, vehi?",
  "ata ba mibayt leulpan o lesham?",
  "ima baa merechov Sverdlov o misham?",
  "ata ba meakademja lerusit leulpan o lepo?",
  "ani baa misham o merechov Komsomolskaja?",
  "ima baa merechov o meuniversita?",
  "ima baa lekan meuniversita o merechov?",
  "mora baa misham lekan?",
  "at baa meulpan lirchov o lekan?",
  "at lomedet anglit im ima, veata?",
  "mora baa habayta mikan, veata?",
  "mora lerusit baa misham, vehu?",
  "at baa lesham mipo o mibayt?",
  "eyfo aba lomed?",
  "aba lomed muzika?",
  "more leanglit lomed, veat?",
  "ata ba mibayt leulpan o lekan?",
  "ima baa meuniversita lepo o habayta?",
  "ata lomed gam ivrit vegam anglit im aba?",
  "ani lomed, vehi?",
  "mi lomed anglit birchov Komsomolskaja?",
  "mora baa mibayt lesham o leuniversita?",
  "more ba mikan leulpan o lesham?",
  "mora lomedet anglit, veat?",
  "ani gara beuniversita o bebayt?",
  "ima lomedet ivrit, veat?",
  "aba lomed anglit bebayt o beulpan?",
  "talmida ovedet im aba, vehi?",
  "mora baa meuniversita lesham o lirchov?",
  "ani talmid?",
  "hu oved beulpan o beuniversita?",
  "ani lo aba, vehi?",
  "aba ba lepo, vehu?",
  "more lomed anglit veivrit im aba, vehu?",
  "more achshav ba lesham mikan, veata?",
  "mi lomed anglit beulpan?",
  "at baa mikan lesham?",
  "eyfo at lomedet ivrit verusit?",
  "mora baa lirchov mikan o mibayt?",
  "ani baa mipo lesham, vehi?",
  "ani beulpan o beakademja lerusit?",
  "hu lomed rusit veivrit?",
  "hu ba lepo meuniversita o meulpan?",
  "more leivrit ba misham?",
  "talmida baa misham o mibayt?",
  "ata ba meakademja habayta o leulpan?",
  "at ima, vehi?",
  "talmid ba lepo misham, vehu?",
  "ani lo ima, vehi?",
  "aba ba lepo meuniversita o misham?",
  "ima baa lesham?",
  "ani ba merechov habayta o lesham?",
  "talmid oved bebayt o beakademja?",
  "at baa habayta misham?",
  "hu ba lesham meulpan o merechov Sverdlov?",
  "ima achshav baa lekan?",
  "mi lomed anglit im aba beakademja?",
  "aba ba leakademja mibayt o mipo?",
  "more ba meakademja leuniversita o lesham?",
  "hu oved im aba?",
  "mi gar beuniversita?",
  "hu ba leuniversita o lepo?",
  "ata ba habayta mibayt o mikan?",
  "mora leanglit baa habayta mibayt o mikan?",
  "ma more lemuzika lomed bebayt?",
  "ani baa misham lepo?",
  "talmida baa mibayt o misham?",
  "aba ba mibayt o mikan?",
  "ani gam aba?",
  "more ba mikan leulpan o habayta?",
  "ata gam more leivrit, vehi?",
  "meayn ata ba lepo?",
  "more leanglit lomed ivrit im ima?",
  "at baa leuniversita misham o mikan?",
  "ani achshav ba lekan misham, veat?",
  "ima achshav baa habayta misham, vehu?",
  "talmida baa lesham o leuniversita?",
  "more oved im ima, vehu?",
  "talmida baa mipo habayta, vehi?",
  "talmida achshav baa lesham mipo?",
  "more lomed anglit verusit, veata?",
  "ani achshav ba lepo?",
  "mora leivrit baa misham lekan, veat?",
  "hi lomedet ivrit, veat?",
  "at beakademja lerusit o beulpan?",
  "mora lemuzika bebayt o beakademja?",
  "more ba mipo lesham o leulpan?",
  "more ba leulpan meuniversita o mikan?",
  "more ba habayta, vehi?",
  "more oved im aba, veata?",
  "hu ba merechov lekan o habayta?",
  "ani gam mora?",
  "talmida lomedet beulpan o beakademja?",
  "mi lomedet muzika beakademja?",
  "lean talmida baa meakademja leanglit?",
  "ima achshav baa habayta mikan?",
  "more achshav ba lekan, vehu?",
  "aba ba lepo meulpan o misham?",
  "ata ba misham lekan o lirchov Sverdlov?",
  "more ba leakademja misham o mikan?",
  "hi baa misham leulpan o lekan?",
  "ima baa misham habayta o lirchov?",
  "meayn hu ba?",
  "ma more lerusit lomed im ani?",
  "hi achshav baa misham, veata?",
  "mora lerusit lomedet, veata?",
  "aba lomed muzika verusit, vehi?",
  "mi baa lekan mibayt?",
  "ima baa leakademja meulpan o mikan?",
  "hu ba habayta mikan o merechov?",
  "more leanglit lomed?",
  "mi lomed rusit veivrit birchov?",
  "ata oved, vehu?",
  "mora leanglit baa lekan, veata?",
  "hi ovedet, veata?",
  "at baa mikan lesham o habayta?",
  "ima lomedet muzika veanglit, vehu?",
  "hu lomed gam anglit vegam muzika?",
  "ata ba habayta, vehi?",
  "ani mora leivrit?",
  "mi ba leulpan misham?",
  "ima baa leakademja mikan o meulpan?",
  "at baa lesham o lepo?",
  "ani gam ima?",
  "talmid lomed muzika im ima, vehu?",
  "eyfo talmida lomedet rusit veivrit?",
  "at baa misham leuniversita o lepo?",
  "more lerusit ba habayta mipo o misham?",
  "more lemuzika ba mibayt lirchov o lepo?",
  "hu achshav ba lekan, veat?",
  "hu lomed anglit?",
  "mora leivrit baa meulpan o mikan?",
  "aba ba habayta o lesham?",
  "mora leanglit baa habayta o lepo?",
  "aba ba habayta o lekan?",
  "mi baa lirchov mipo?",
  "talmida baa lekan?",
  "ani lomed anglit im aba?",
  "eyfo more lerusit lomed anglit umuzika?",
  "ani ba habayta misham o meuniversita?",
  "ata ba mipo lesham, vehi?",
  "ani ba meulpan lekan o lesham?",
  "at baa mibayt lepo o lirchov?",
  "at achshav baa mipo, vehu?",
  "hu ba lirchov Sverdlov o lekan?",
  "mora lemuzika baa misham lepo o habayta?",
  "mora leanglit achshav baa mipo, veata?",
  "more lemuzika lomed ivrit verusit im aba?",
  "more achshav ba lepo misham, vehi?",
  "ata oved bebayt o beakademja leanglit?",
  "mora baa lirchov meulpan o mipo?",
  "more ba meakademja lesham o leuniversita?",
  "ma aba lomed birchov Komsomolskaja?",
  "more lemuzika ba lekan, veat?",
  "aba ba leuniversita meulpan o merechov?",
  "hi baa habayta mipo, vehu?",
  "aba ba leakademja mikan o merechov?",
  "mora leivrit baa lepo misham, veat?",
  "hi lomedet rusit veanglit?",
  "ani lo ima?",
  "hu lomed anglit verusit, veata?",
  "hi baa lekan, veat?",
  "talmid achshav ba misham lepo?",
  "ata ba mibayt o mipo?",
  "ma more lomed birchov Komsomolskaja im at?",
  "ma more lomed birchov im ata?",
  "ata lomed anglit veivrit im ima, veat?",
  "talmida achshav baa mipo lesham?",
  "mora achshav baa habayta?",
  "ani ba lesham mikan?",
  "ani lomed anglit verusit im aba, veat?",
  "meayn more leivrit ba lekan?",
  "more ba leakademja lerusit mibayt o mipo?",
  "ani lomed rusit veivrit, vehi?",
  "more lerusit ba merechov habayta o lepo?",
  "ani baa meuniversita lesham o lepo?",
  "eyfo ani lomed muzika verusit?",
  "hu ba habayta merechov o mipo?",
  "ata more lerusit, veat?",
  "more lerusit ba leakademja meulpan o mikan?",
  "ima baa mikan leulpan o leuniversita?",
  "hu lomed rusit veanglit im aba, vehi?",
  "ani lomed muzika verusit, vehu?",
  "eyfo hi lomedet rusit umuzika?",
  "more lerusit ba lepo o lirchov Sverdlov?",
  "more ba mipo o misham?",
  "aba lomed anglit verusit, veata?",
  "ani ba lesham, veata?",
  "ani ba lirchov meulpan o mipo?",
  "ani gam aba vegam talmid, vehu?",
  "aba achshav ba lekan misham, veat?",
  "ata ba lesham o leuniversita?",
  "mora leivrit baa lesham mipo, vehu?",
  "at baa lesham meulpan o mipo?",
  "eyn mora lemuzika bebayt?",
  "ani achshav ba misham habayta, veat?",
  "talmida baa mikan o meulpan?",
  "meayn talmida baa lekan?",
  "ima achshav baa mikan habayta, veat?",
  "hu ba lekan misham, veat?",
  "more lemuzika oved im ima?",
  "more lemuzika ba misham o mipo?",
  "more ba lirchov mibayt o misham?",
  "mora lemuzika baa lepo o habayta?",
  "aba ba mipo habayta?",
  "ata lomed anglit bebayt o beakademja?",
  "hu ba leakademja mibayt o mipo?",
  "eyn mora beulpan?",
  "ata aba, vehu?",
  "mora leivrit baa lesham o lekan?",
  "ani baa lepo meulpan o misham?",
  "ani baa habayta merechov o mibayt?",
  "ata lomed anglit umuzika im ima, vehi?",
  "talmid lomed ivrit verusit im ima, veat?",
  "hu ba habayta o lekan?",
  "hi lomedet muzika veanglit, vehu?",
  "mora leanglit achshav baa misham, veat?",
  "talmida lomedet muzika im ima?",
  "hu ba mipo habayta o leulpan?",
  "at gam mora leivrit, vehi?",
  "mi ba lirchov Komsomolskaja mibayt?",
  "more lerusit ba mipo habayta?",
  "ima baa meulpan lekan o lesham?",
  "ani gam mora leanglit, veat?",
  "aba lomed muzika veivrit im ima, vehi?",
  "mora baa mibayt leuniversita o habayta?",
  "at lomedet rusit veanglit im aba?",
  "talmid achshav ba lekan, veat?",
  "mi talmida?",
  "aba lomed muzika veanglit, vehi?",
  "mora lomedet muzika im aba?",
  "at gam mora leanglit?",
  "ani lomed muzika im aba, vehu?",
  "more ba mipo, veata?",
  "more lemuzika achshav ba habayta, vehi?",
  "mora lerusit baa habayta, veata?",
  "hu ba habayta o lirchov?",
  "mora lemuzika baa merechov o meulpan?",
  "mora baa lekan, vehu?",
  "mora lemuzika lomedet anglit, veat?",
  "more ba merechov o mibayt?",
  "ma aba lomed birchov Komsomolskaja im ima?",
  "talmida lomedet, veat?",
  "mi gara bebayt?",
  "mi ba mipo lirchov Sverdlov?",
  "yesh ima beulpan?",
  "ani ba mikan lirchov o leulpan?",
  "ata ba lekan misham, vehu?",
  "hi achshav baa lesham, vehu?",
  "more achshav ba lepo misham?",
  "at baa leuniversita meulpan o mibayt?",
  "lean more leanglit ba meuniversita?",
  "more lemuzika ba mikan, veat?",
  "ani baa meuniversita lekan o habayta?",
  "at lomedet gam muzika vegam anglit, vehu?",
  "hu gar beakademja o beulpan?",
  "mora leivrit baa misham habayta?",
  "mi ba lepo?",
  "mora baa habayta mipo o merechov Sverdlov?",
  "hu more, veat?",
  "more lemuzika ba misham habayta?",
  "mi baa habayta meuniversita?",
  "aba ba leulpan o lirchov?",
  "ata lomed anglit umuzika, vehi?",
  "ani ba misham lekan o leulpan?",
  "hi baa lesham o leuniversita?",
  "aba lomed anglit verusit, vehi?",
  "talmid achshav ba habayta mipo, vehi?",
  "more leanglit ba mikan?",
  "mora beulpan o beakademja lerusit?",
  "ma talmida lomedet?",
  "mora achshav baa lekan, vehi?",
  "lean ani ba?",
  "at lomedet ivrit veanglit im ima, vehu?",
  "ani lomedet anglit verusit im ima?",
  "hi gam mora lerusit vegam ima, veat?",
  "more lerusit lomed muzika, veat?",
  "mora leivrit lomedet muzika?",
  "ani baa lepo, vehi?",
  "hu aba?",
  "hu ba meulpan lirchov o lesham?",
  "ata gam more?",
  "more lemuzika ba mipo leulpan o habayta?",
  "hu ba lirchov mipo o meulpan?",
  "lean more leivrit ba merechov Sverdlov?",
  "ima lomedet anglit, veata?",
  "hi baa lirchov o leulpan?",
  "ani lomedet ivrit veanglit?",
  "ani baa lekan, vehu?",
  "ani ba mibayt lirchov Sverdlov o lepo?",
  "ani lomed muzika veanglit?",
  "ani baa lesham merechov o meulpan?",
  "aba ba mipo lirchov o lesham?",
  "talmida baa misham lekan o habayta?",
  "ata lomed ivrit umuzika beulpan o bebayt?",
  "hu lomed anglit veivrit im ima, veata?",
  "ani gar beakademja o bebayt?",
  "mora lomedet rusit veanglit im aba?",
  "aba ba misham o merechov?",
  "ma talmid lomed?",
  "at baa merechov lepo o habayta?",
  "ata achshav ba mipo habayta?",
  "hi beuniversita o bebayt?",
  "mora leanglit lomedet ivrit, vehi?",
  "mora ovedet, veata?",
  "more lerusit ba lesham o lekan?",
  "ani achshav baa mipo, veat?",
  "at lomedet rusit veivrit, veata?",
  "hu ba merechov lekan o leulpan?",
  "mora leanglit baa lesham, vehu?",
  "at achshav baa lesham mikan?",
  "aba ba habayta merechov o misham?",
  "aba ba meakademja leulpan o lirchov?",
  "ani ima?",
  "ima ovedet bebayt o beakademja lemuzika?",
  "hi gam ima vegam talmida?",
  "ani gam mora vegam ima, veata?",
  "ata ba misham leulpan o habayta?",
  "hi baa lirchov meulpan o mibayt?",
  "hu aba o more?",
  "talmida lomedet rusit veanglit im ima?",
  "ima lomedet rusit, vehu?",
  "mi baa misham lekan?",
  "ata more, vehu?",
  "more lerusit ba lepo, veata?",
  "mora baa lekan, vehi?",
  "more leivrit ba leulpan o habayta?",
  "ima baa leuniversita merechov o mipo?",
  "mi ba mibayt?",
  "more gar beuniversita o beakademja?",
  "mora lerusit baa lesham, vehi?",
  "mora leanglit baa habayta mikan, vehi?",
  "ma aba lomed birchov im ata?",
  "mora leivrit lomedet anglit im aba?",
  "ata ba habayta misham o mipo?",
  "hi gam mora leivrit vegam ima, veat?",
  "hi gara beulpan o beakademja lerusit?",
  "more ba meulpan lirchov Sverdlov o lesham?",
  "ima baa mikan lesham, veat?",
  "ata gam talmid vegam more lemuzika?",
  "ma more lomed beulpan im aba?",
  "hi gara beakademja o bebayt?",
  "hu ba mibayt lesham o lepo?",
  "ata achshav ba mipo, vehi?",
  "talmid ba habayta mibayt o mikan?",
  "aba ba merechov leuniversita o lepo?",
  "ma aba lomed beulpan im ima?",
  "mi lomedet muzika veanglit birchov?",
  "ima baa misham leuniversita o leulpan?",
  "at baa habayta merechov o mipo?",
  "at lo ima?",
  "ima lomedet gam bebayt vegam beulpan?",
  "ata ba habayta mipo o merechov Sverdlov?",
  "mora achshav baa misham?",
  "at baa meuniversita lesham o habayta?",
  "more leanglit lomed muzika, veat?",
  "at baa leakademja lerusit misham o mibayt?",
  "talmid ba habayta o lirchov?",
  "hu lomed, vehi?",
  "at baa habayta?",
  "ata lomed gam muzika vegam ivrit, veat?",
  "more oved im aba, vehi?",
  "mora baa meuniversita lesham o lepo?",
  "more ba meakademja lekan o lirchov?",
  "ma more lomed beuniversita im ata?",
  "more leivrit ba mipo habayta o lesham?",
  "mora leanglit achshav baa lesham mipo?",
  "more leanglit achshav ba misham?",
  "ata bebayt o beakademja?",
  "hu lomed muzika bebayt o beulpan?",
  "ani baa mipo lesham?",
  "ata ba lirchov Sverdlov meulpan o mikan?",
  "ima lomedet muzika veanglit?",
  "hu more o talmid?",
  "mora baa lesham mipo, vehi?",
  "hu ba leulpan misham o merechov?",
  "mi lomedet ivrit verusit beakademja?",
  "at baa habayta mipo o meulpan?",
  "aba lomed bebayt o beulpan?",
  "eyfo ani gara?",
  "hu lomed ivrit, veat?",
  "mora lemuzika baa leulpan misham o mipo?",
  "eyn ima birchov Komsomolskaja?",
  "ani lomedet gam anglit vegam rusit?",
  "hi achshav baa habayta mipo?",
  "ani lomed ivrit?",
  "mora baa mikan, veata?",
  "ani baa lekan, vehi?",
  "eyfo more lerusit lomed anglit?",
  "hu ba mipo o merechov?",
  "ma more lomed beakademja im ima?",
  "ani baa mikan?",
  "mi ba misham leuniversita?",
  "eyfo hi more?",
  "mora lemuzika beakademja lerusit o bebayt?",
  "hi baa misham lepo?",
  "hu ba leulpan o habayta?",
  "aba ba mibayt leulpan o leuniversita?",
  "ata ba lekan misham, veat?",
  "more ba misham habayta o leuniversita?",
  "more ba lepo?",
  "more leivrit ba habayta mipo?",
  "at baa meakademja lekan o lesham?",
  "ani baa leakademja merechov o mibayt?",
  "eyn talmid beulpan?",
  "hu lomed muzika veivrit im aba, veat?",
  "ima baa lesham o lepo?",
  "at gara beulpan o beakademja?",
  "eyfo hi lomedet anglit veivrit?",
  "at gara beuniversita o beakademja?",
  "hu ba leakademja leivrit mipo o mibayt?",
  "mi baa leuniversita meulpan?",
  "ata more o talmid?",
  "ani baa mikan leulpan o habayta?",
  "ani more?",
  "hu lomed ivrit verusit im ima, veata?",
  "mora baa lesham mikan, vehi?",
  "ma more lemuzika lomed im mora?",
  "more ba mibayt o merechov Komsomolskaja?",
  "at gam talmida, veata?",
  "ani lomedet rusit umuzika, vehi?",
  "ima baa lirchov Sverdlov o leuniversita?",
  "ani lomedet ivrit verusit im ima, vehu?",
  "ma aba lomed beakademja lemuzika?",
  "more ba merechov o mipo?",
  "ani baa leulpan meuniversita o misham?",
  "at mora, veata?",
  "aba ba merechov o mikan?",
  "hu ba meuniversita lesham o lepo?",
  "ima baa merechov habayta o leulpan?",
  "at gam mora vegam talmida?",
  "meayn hu ba leuniversita?",
  "at lomedet ivrit im aba, vehi?",
  "hu ba meuniversita lesham o habayta?",
  "at lomedet ivrit im aba, vehu?",
  "eyfo ima lomedet anglit?",
  "ma aba lomed beuniversita im ima?",
  "aba ba lirchov mipo o misham?",
  "mora lerusit baa mibayt lepo o leulpan?",
  "ata more leivrit, vehi?",
  "talmida baa mikan o mibayt?",
  "ani lo more leanglit, vehi?",
  "ata beuniversita o beulpan?",
  "ani gam more, vehu?",
  "hi baa meakademja leivrit leulpan o lekan?",
  "more lemuzika ba mikan o meuniversita?",
  "aba ba misham habayta o leulpan?",
  "ma ima lomedet bebayt im talmid?",
  "more oved im ima, vehi?",
  "more ba misham habayta, vehi?",
  "lean ani baa?",
  "more ba lirchov mibayt o mipo?",
  "talmida baa habayta misham o meulpan?",
  "hu ba mipo, vehi?",
  "yesh more birchov Sverdlov?",
  "ani baa mikan lesham, veata?",
  "talmid ba leulpan mipo o misham?",
  "more leanglit lomed ivrit verusit, vehi?",
  "ani baa leakademja lerusit misham o mipo?",
  "at baa lepo misham?",
  "ani ba mikan, veata?",
  "ani baa misham leulpan o lirchov?",
  "talmida baa mipo o mibayt?",
  "at ovedet bebayt o beulpan?",
  "ani ba mipo, veata?",
  "more achshav ba lekan, veata?",
  "ata beakademja leivrit o bebayt?",
  "mora leanglit baa mikan lesham, vehi?",
  "hu lomed muzika beuniversita o bebayt?",
  "at gam mora leivrit, veata?",
  "ima achshav baa habayta?",
  "more leivrit ba lesham, veata?",
  "at baa meakademja leivrit lepo o lesham?",
  "hu lomed?",
  "mora leanglit baa misham lekan, vehu?",
  "more lemuzika ba mipo o meulpan?",
  "hu gam more, vehi?",
  "mora leanglit baa mipo lesham?",
  "aba lomed, veat?",
  "hi baa mipo o meuniversita?",
  "ata talmid?",
  "mora gara beakademja o beuniversita?",
  "ani baa mikan habayta, vehu?",
  "ata lomed gam muzika vegam ivrit?",
  "ani more leivrit, veat?",
  "more lerusit oved, veata?",
  "hu gam aba vegam talmid, veata?",
  "aba ba lirchov mibayt o mipo?",
  "talmid ba lekan merechov o meulpan?",
  "more lomed ivrit?",
  "more lomed rusit veanglit im aba, veata?",
  "lean more lerusit ba mikan?",
  "ma aba lomed im hi?",
  "ani ovedet im ima?",
  "ani beakademja lerusit o bebayt?",
  "talmid ba meulpan lepo o lesham?",
];